/**
 * @license
 * CONSCORE ERP IA - FASE 14: AUTOMATIZACIÓN EMPRESARIAL + BPM + WORKFLOWS + RPA
 * Initial Data & Reference Catalog (A01 - A25, BPM Workflows, Rules, RPA Bots, 3-Way Match, DLQ)
 */

import {
  BpmWorkflowDefinition,
  BusinessRule,
  PreconfiguredAutomation,
  AutomationExecutiveAction,
  ThreeWayMatchRecord,
  OmniNotification,
  EscalationIncident,
  RpaRobotTask,
  DeadLetterQueueItem,
  AutomationObservabilityMetrics,
  ChaosTestScenario,
  EnterpriseEvent,
} from '../types/automationBpmTypes';

// ============================================================================
// 25 PRECONFIGURED AUTOMATIONS (A01 - A25)
// ============================================================================

export const INITIAL_PRECONFIGURED_AUTOMATIONS: PreconfiguredAutomation[] = [
  {
    automationId: 'A01',
    code: 'A01',
    title: 'Lead Comercial sin Seguimiento',
    module: 'CRM',
    triggerEvent: 'LEAD_UNATTENDED',
    ruleSummary: 'IF lead.status == "NUEVO" AND hoursWithoutFollowUp > 4 THEN reassign & notify supervisor',
    workflowSummary: 'Auto-reasignación ponderada a vendedor disponible + push alert a Gerencia de Ventas.',
    requiresHumanApproval: false,
    requiredRole: 'GERENTE_VENTAS',
    financialRiskLevel: 'LOW',
    enabled: true,
    stats: {
      executionsCount: 42,
      approvedCount: 42,
      rejectedCount: 0,
      timeSavedMinutes: 320,
      financialImpactMxn: 480000,
      lastExecutedAt: '2026-08-27T09:15:00Z',
    },
  },
  {
    automationId: 'A02',
    code: 'A02',
    title: 'Cotización Próxima a Vencer (T-24h)',
    module: 'VENTAS',
    triggerEvent: 'QUOTE_EXPIRING_SOON',
    ruleSummary: 'IF quote.status == "ENVIADA" AND hoursUntilExpiration <= 24 THEN trigger dunning & task',
    workflowSummary: 'Envío de recordatorio omnicanal al cliente y generación de tarea urgente para el ejecutivo.',
    requiresHumanApproval: false,
    requiredRole: 'VENDEDOR',
    financialRiskLevel: 'LOW',
    enabled: true,
    stats: {
      executionsCount: 68,
      approvedCount: 68,
      rejectedCount: 0,
      timeSavedMinutes: 510,
      financialImpactMxn: 1250000,
      lastExecutedAt: '2026-08-27T08:30:00Z',
    },
  },
  {
    automationId: 'A03',
    code: 'A03',
    title: 'Cotización Vencida con Oportunidad Activa',
    module: 'VENTAS',
    triggerEvent: 'QUOTE_EXPIRED',
    ruleSummary: 'IF quote.expirationDate < TODAY AND quote.status == "ENVIADA" THEN update status to VENCIDA',
    workflowSummary: 'Cierre de vigencia de precios, liberación de inventario apartado condicional y aviso a CRM.',
    requiresHumanApproval: false,
    requiredRole: 'VENDEDOR',
    financialRiskLevel: 'MEDIUM',
    enabled: true,
    stats: {
      executionsCount: 29,
      approvedCount: 29,
      rejectedCount: 0,
      timeSavedMinutes: 180,
      financialImpactMxn: 340000,
      lastExecutedAt: '2026-08-26T23:59:00Z',
    },
  },
  {
    automationId: 'A04',
    code: 'A04',
    title: 'Inventario en Punto de Reorden (Stock Bajo)',
    module: 'INVENTARIOS',
    triggerEvent: 'STOCK_LOW',
    ruleSummary: 'IF product.availableStock <= product.reorderPoint THEN generate purchase proposal',
    workflowSummary: 'Cálculo de lote económico de compra + sugerencia de proveedor preferente con cotización base.',
    requiresHumanApproval: true,
    requiredRole: 'COMPRAS',
    financialRiskLevel: 'MEDIUM',
    enabled: true,
    stats: {
      executionsCount: 84,
      approvedCount: 79,
      rejectedCount: 5,
      timeSavedMinutes: 1260,
      financialImpactMxn: 3950000,
      lastExecutedAt: '2026-08-27T07:45:00Z',
    },
  },
  {
    automationId: 'A05',
    code: 'A05',
    title: 'Inventario Crítico / Ruptura Inminente de Stock',
    module: 'INVENTARIOS',
    triggerEvent: 'STOCK_CRITICAL',
    ruleSummary: 'IF product.availableStock <= product.minStock THEN trigger CRITICAL alert & priority PO',
    workflowSummary: 'Alerta roja a Compras y Operaciones + bloqueo preventivo de cotizaciones con entrega inmediata.',
    requiresHumanApproval: true,
    requiredRole: 'COMPRAS',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 16,
      approvedCount: 16,
      rejectedCount: 0,
      timeSavedMinutes: 480,
      financialImpactMxn: 890000,
      lastExecutedAt: '2026-08-26T14:20:00Z',
    },
  },
  {
    automationId: 'A06',
    code: 'A06',
    title: 'Pedido Bloqueado por Límite de Crédito',
    module: 'FINANZAS',
    triggerEvent: 'ORDER_CREDIT_BLOCKED',
    ruleSummary: 'IF customer.creditAvailable < order.total THEN hold order & request Credit Committee review',
    workflowSummary: 'Bloqueo automático de surtido + apertura de expediente de excepción de crédito con historial de pagos.',
    requiresHumanApproval: true,
    requiredRole: 'FINANZAS',
    financialRiskLevel: 'CRITICAL',
    enabled: true,
    stats: {
      executionsCount: 18,
      approvedCount: 11,
      rejectedCount: 7,
      timeSavedMinutes: 360,
      financialImpactMxn: 2450000,
      lastExecutedAt: '2026-08-27T09:00:00Z',
    },
  },
  {
    automationId: 'A07',
    code: 'A07',
    title: 'Factura CXC Próxima a Vencer (T-5 días)',
    module: 'CXC',
    triggerEvent: 'INVOICE_ISSUED',
    ruleSummary: 'IF invoice.status == "PENDING" AND daysUntilDue == 5 THEN dispatch preventive statement',
    workflowSummary: 'Envío cordial de estado de cuenta y archivos XML/PDF al portal de tesorería del cliente.',
    requiresHumanApproval: false,
    requiredRole: 'FINANZAS',
    financialRiskLevel: 'LOW',
    enabled: true,
    stats: {
      executionsCount: 112,
      approvedCount: 112,
      rejectedCount: 0,
      timeSavedMinutes: 890,
      financialImpactMxn: 6800000,
      lastExecutedAt: '2026-08-27T06:00:00Z',
    },
  },
  {
    automationId: 'A08',
    code: 'A08',
    title: 'Factura CXC Vencida (Cobranza Escalonada)',
    module: 'CXC',
    triggerEvent: 'CUSTOMER_OVERDUE',
    ruleSummary: 'IF invoice.daysOverdue >= 1 THEN initiate multi-stage dunning workflow based on aging bucket',
    workflowSummary: 'Etapa 1 (1-7d): Recordatorio ejecutivo. Etapa 2 (8-30d): Llamada cobranza. Etapa 3 (+31d): Bloqueo de nuevos pedidos.',
    requiresHumanApproval: false,
    requiredRole: 'FINANZAS',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 54,
      approvedCount: 54,
      rejectedCount: 0,
      timeSavedMinutes: 650,
      financialImpactMxn: 1870000,
      lastExecutedAt: '2026-08-27T07:15:00Z',
    },
  },
  {
    automationId: 'A09',
    code: 'A09',
    title: 'Promesa de Pago Incumplida',
    module: 'CXC',
    triggerEvent: 'PAYMENT_PROMISE_BROKEN',
    ruleSummary: 'IF paymentPromise.date < TODAY AND payment.status != "PAID" THEN escalate to Finance Manager',
    workflowSummary: 'Aviso prioritario al Gerente de Finanzas + suspensión cautelar de condiciones de crédito.',
    requiresHumanApproval: true,
    requiredRole: 'FINANZAS',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 12,
      approvedCount: 10,
      rejectedCount: 2,
      timeSavedMinutes: 240,
      financialImpactMxn: 920000,
      lastExecutedAt: '2026-08-26T16:00:00Z',
    },
  },
  {
    automationId: 'A10',
    code: 'A10',
    title: 'Factura de Proveedor (CXP) Próxima a Vencer',
    module: 'CXP',
    triggerEvent: 'AP_BILL_RECEIVED',
    ruleSummary: 'IF bill.status == "PENDING" AND daysUntilDue <= 3 THEN enqueue in weekly payment schedule',
    workflowSummary: 'Validación de flujo de caja proyectado + programación en propuesta de dispersión bancaria.',
    requiresHumanApproval: true,
    requiredRole: 'FINANZAS',
    financialRiskLevel: 'MEDIUM',
    enabled: true,
    stats: {
      executionsCount: 76,
      approvedCount: 74,
      rejectedCount: 2,
      timeSavedMinutes: 610,
      financialImpactMxn: 5120000,
      lastExecutedAt: '2026-08-27T08:10:00Z',
    },
  },
  {
    automationId: 'A11',
    code: 'A11',
    title: 'Detección de Factura de Proveedor Duplicada',
    module: 'CXP',
    triggerEvent: 'AP_BILL_DUPLICATE_DETECTED',
    ruleSummary: 'IF newBill.uuid == existingBill.uuid OR (supplierId == existing AND invoiceFolio == existing) THEN reject & quarantine',
    workflowSummary: 'Rechazo inmediato de registro contable + alerta antifraude a Auditoría Interna y Contabilidad.',
    requiresHumanApproval: true,
    requiredRole: 'ADMINISTRADOR',
    financialRiskLevel: 'CRITICAL',
    enabled: true,
    stats: {
      executionsCount: 5,
      approvedCount: 0,
      rejectedCount: 5,
      timeSavedMinutes: 150,
      financialImpactMxn: 630000,
      lastExecutedAt: '2026-08-25T11:40:00Z',
    },
  },
  {
    automationId: 'A12',
    code: 'A12',
    title: 'Discrepancia en Validación 3-Way Match',
    module: 'CXP',
    triggerEvent: 'THREE_WAY_MATCH_DISCREPANCY',
    ruleSummary: 'IF abs(invoice.total - po.total) > $50 MXN OR invoice.qty != goodsReceipt.qty THEN hold payment',
    workflowSummary: 'Bloqueo estricto del pago al proveedor + solicitud de refacturación o nota de crédito.',
    requiresHumanApproval: true,
    requiredRole: 'COMPRAS',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 23,
      approvedCount: 4,
      rejectedCount: 19,
      timeSavedMinutes: 460,
      financialImpactMxn: 1340000,
      lastExecutedAt: '2026-08-27T09:30:00Z',
    },
  },
  {
    automationId: 'A13',
    code: 'A13',
    title: 'Documento o Certificación RH por Vencer',
    module: 'RH',
    triggerEvent: 'HR_DOCUMENT_EXPIRING',
    ruleSummary: 'IF employee.document.expiresInDays <= 30 THEN create renewal task for HR & employee alert',
    workflowSummary: 'Generación de ticket de renovación para DC-3, examen médico o licencia de chofer.',
    requiresHumanApproval: false,
    requiredRole: 'RH',
    financialRiskLevel: 'LOW',
    enabled: true,
    stats: {
      executionsCount: 38,
      approvedCount: 38,
      rejectedCount: 0,
      timeSavedMinutes: 290,
      financialImpactMxn: 120000,
      lastExecutedAt: '2026-08-27T06:30:00Z',
    },
  },
  {
    automationId: 'A14',
    code: 'A14',
    title: 'Advertencia Preventiva de SLA de Ticket (80%)',
    module: 'SERVICIO',
    triggerEvent: 'TICKET_SLA_WARNING',
    ruleSummary: 'IF ticket.elapsedTime >= 0.80 * ticket.slaLimitMinutes AND status != "RESUELTO" THEN send push alert',
    workflowSummary: 'Alerta directa al agente asignado y al supervisor de soporte para priorización de ticket.',
    requiresHumanApproval: false,
    requiredRole: 'SERVICIO_CLIENTE',
    financialRiskLevel: 'LOW',
    enabled: true,
    stats: {
      executionsCount: 47,
      approvedCount: 47,
      rejectedCount: 0,
      timeSavedMinutes: 380,
      financialImpactMxn: 260000,
      lastExecutedAt: '2026-08-27T09:10:00Z',
    },
  },
  {
    automationId: 'A15',
    code: 'A15',
    title: 'Incumplimiento de SLA de Ticket (100% Breached)',
    module: 'SERVICIO',
    triggerEvent: 'TICKET_SLA_BREACHED',
    ruleSummary: 'IF ticket.elapsedTime > ticket.slaLimitMinutes AND status != "RESUELTO" THEN escalate to Manager',
    workflowSummary: 'Escalamiento automático a Dirección de Operaciones + registro de penalización de SLA para reporte mensual.',
    requiresHumanApproval: false,
    requiredRole: 'CALIDAD',
    financialRiskLevel: 'MEDIUM',
    enabled: true,
    stats: {
      executionsCount: 9,
      approvedCount: 9,
      rejectedCount: 0,
      timeSavedMinutes: 180,
      financialImpactMxn: 150000,
      lastExecutedAt: '2026-08-26T18:05:00Z',
    },
  },
  {
    automationId: 'A16',
    code: 'A16',
    title: 'Detección y Recuperación de Cliente Detractor (NPS ≤ 6)',
    module: 'CALIDAD',
    triggerEvent: 'CUSTOMER_DETRACTOR_DETECTED',
    ruleSummary: 'IF csatSurvey.score <= 6 OR npsScore <= 6 THEN trigger Customer Recovery Protocol within 2h',
    workflowSummary: 'Apertura de caso de calidad + asignación de llamada de desagravio por parte del Director Comercial.',
    requiresHumanApproval: true,
    requiredRole: 'DIRECTOR',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 14,
      approvedCount: 14,
      rejectedCount: 0,
      timeSavedMinutes: 280,
      financialImpactMxn: 1850000,
      lastExecutedAt: '2026-08-25T15:20:00Z',
    },
  },
  {
    automationId: 'A17',
    code: 'A17',
    title: 'Riesgo Empresarial Crítico Detectado (ERM)',
    module: 'RIESGOS',
    triggerEvent: 'ENTERPRISE_RISK_TRIGGERED',
    ruleSummary: 'IF risk.residualSeverity == "CRITICO" OR kpiDeviation >= 25% THEN alert Risk Committee',
    workflowSummary: 'Inclusión inmediata en orden del día del Comité de Riesgos + activación de plan de mitigación.',
    requiresHumanApproval: true,
    requiredRole: 'DIRECTOR',
    financialRiskLevel: 'CRITICAL',
    enabled: true,
    stats: {
      executionsCount: 7,
      approvedCount: 7,
      rejectedCount: 0,
      timeSavedMinutes: 210,
      financialImpactMxn: 4200000,
      lastExecutedAt: '2026-08-26T11:00:00Z',
    },
  },
  {
    automationId: 'A18',
    code: 'A18',
    title: 'Conflicto de Segregación de Funciones (SoD Block)',
    module: 'GOBIERNO',
    triggerEvent: 'SOD_CONFLICT_DETECTED',
    ruleSummary: 'IF user.action violates SoDConflictMatrix THEN block transaction instantly & log security incident',
    workflowSummary: 'Bloqueo transaccional preventivo + notificación a Auditoría Interna con captura de auditoría forense.',
    requiresHumanApproval: true,
    requiredRole: 'ADMINISTRADOR',
    financialRiskLevel: 'CRITICAL',
    enabled: true,
    stats: {
      executionsCount: 6,
      approvedCount: 0,
      rejectedCount: 6,
      timeSavedMinutes: 120,
      financialImpactMxn: 1500000,
      lastExecutedAt: '2026-08-27T08:50:00Z',
    },
  },
  {
    automationId: 'A19',
    code: 'A19',
    title: 'Alerta Preventiva de Presupuesto Consumido (>80%)',
    module: 'FINANZAS',
    triggerEvent: 'BUDGET_THRESHOLD_REACHED',
    ruleSummary: 'IF department.spentBudget / department.allocatedBudget >= 0.80 THEN notify Area Manager',
    workflowSummary: 'Envío de resumen de ejecución presupuestal y advertencia de saldo disponible restante.',
    requiresHumanApproval: false,
    requiredRole: 'FINANZAS',
    financialRiskLevel: 'MEDIUM',
    enabled: true,
    stats: {
      executionsCount: 31,
      approvedCount: 31,
      rejectedCount: 0,
      timeSavedMinutes: 250,
      financialImpactMxn: 780000,
      lastExecutedAt: '2026-08-27T07:00:00Z',
    },
  },
  {
    automationId: 'A20',
    code: 'A20',
    title: 'Presupuesto de Área Excedido (100% Locked)',
    module: 'FINANZAS',
    triggerEvent: 'BUDGET_EXCEEDED',
    ruleSummary: 'IF newExpense.total + department.spentBudget > department.allocatedBudget THEN hold requisition',
    workflowSummary: 'Bloqueo de nuevas órdenes de compra del departamento hasta autorización expresa de Dirección.',
    requiresHumanApproval: true,
    requiredRole: 'DIRECTOR',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 11,
      approvedCount: 6,
      rejectedCount: 5,
      timeSavedMinutes: 220,
      financialImpactMxn: 1150000,
      lastExecutedAt: '2026-08-26T17:30:00Z',
    },
  },
  {
    automationId: 'A21',
    code: 'A21',
    title: 'Margen Comercial por Debajo del Mínimo Autorizado',
    module: 'VENTAS',
    triggerEvent: 'ORDER_DISCOUNT_EXCEPTION',
    ruleSummary: 'IF quote.grossMarginPct < minimumThreshold (18%) THEN require Executive Committee Sign-off',
    workflowSummary: 'Retención de la cotización en estado PENDIENTE_APROBACION_MARGEN con análisis de rentabilidad.',
    requiresHumanApproval: true,
    requiredRole: 'GERENTE_VENTAS',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 22,
      approvedCount: 14,
      rejectedCount: 8,
      timeSavedMinutes: 330,
      financialImpactMxn: 870000,
      lastExecutedAt: '2026-08-27T09:25:00Z',
    },
  },
  {
    automationId: 'A22',
    code: 'A22',
    title: 'Comisión de Venta Pendiente de Aprobación',
    module: 'RH',
    triggerEvent: 'COMMISSION_PENDING_APPROVAL',
    ruleSummary: 'IF invoice.status == "PAGADA" AND commission.status == "CALCULADA" THEN send to HR approval queue',
    workflowSummary: 'Verificación de cobranza efectiva del pedido antes de liberar la comisión en prenómina.',
    requiresHumanApproval: true,
    requiredRole: 'RH',
    financialRiskLevel: 'MEDIUM',
    enabled: true,
    stats: {
      executionsCount: 58,
      approvedCount: 58,
      rejectedCount: 0,
      timeSavedMinutes: 460,
      financialImpactMxn: 620000,
      lastExecutedAt: '2026-08-27T08:00:00Z',
    },
  },
  {
    automationId: 'A23',
    code: 'A23',
    title: 'Incidente Crítico de Operación / Logística',
    module: 'LOGISTICA',
    triggerEvent: 'TICKET_SLA_BREACHED',
    ruleSummary: 'IF routeStop.status == "INCIDENCIA_CRITICA" OR delayHours > 4 THEN alert Control Center & Client',
    workflowSummary: 'Reasignación de unidad de transporte o reprogramación de entrega con aviso transparente al cliente.',
    requiresHumanApproval: false,
    requiredRole: 'LOGISTICA',
    financialRiskLevel: 'MEDIUM',
    enabled: true,
    stats: {
      executionsCount: 19,
      approvedCount: 19,
      rejectedCount: 0,
      timeSavedMinutes: 280,
      financialImpactMxn: 450000,
      lastExecutedAt: '2026-08-26T13:40:00Z',
    },
  },
  {
    automationId: 'A24',
    code: 'A24',
    title: 'Obligación de Compliance Próxima a Vencer',
    module: 'COMPLIANCE',
    triggerEvent: 'COMPLIANCE_OBLIGATION_EXPIRING',
    ruleSummary: 'IF obligation.dueDate - TODAY <= 10 days AND status != "CUMPLIDO" THEN trigger Compliance Task',
    workflowSummary: 'Requerimiento formal al responsable del área para subir evidencia digital a la bóveda SHA-256.',
    requiresHumanApproval: false,
    requiredRole: 'ADMINISTRADOR',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 26,
      approvedCount: 26,
      rejectedCount: 0,
      timeSavedMinutes: 390,
      financialImpactMxn: 1900000,
      lastExecutedAt: '2026-08-27T06:15:00Z',
    },
  },
  {
    automationId: 'A25',
    code: 'A25',
    title: 'Acción Ejecutiva de Gobierno Vencida',
    module: 'GOBIERNO',
    triggerEvent: 'EXECUTIVE_ACTION_OVERDUE',
    ruleSummary: 'IF executiveAction.dueDate < TODAY AND status != "COMPLETED" THEN notify Director General',
    workflowSummary: 'Escalamiento directo a Dirección General y registro de desviación en el Health Score de Gobierno.',
    requiresHumanApproval: true,
    requiredRole: 'DIRECTOR',
    financialRiskLevel: 'HIGH',
    enabled: true,
    stats: {
      executionsCount: 8,
      approvedCount: 8,
      rejectedCount: 0,
      timeSavedMinutes: 160,
      financialImpactMxn: 750000,
      lastExecutedAt: '2026-08-26T19:00:00Z',
    },
  },
];

// ============================================================================
// BPM WORKFLOW DEFINITIONS
// ============================================================================

export const INITIAL_BPM_WORKFLOWS: BpmWorkflowDefinition[] = [
  {
    workflowId: 'WF-COMMERCIAL-E2E-01',
    version: 3,
    name: 'Flujo Maestro Cotización a Cobro (Quote-to-Cash)',
    category: 'VENTAS',
    owner: 'Dirección Comercial & Finanzas',
    status: 'ACTIVE',
    triggerEvent: 'QUOTE_ACCEPTED',
    triggerConditionDescription: 'Cotización aceptada por cliente formal con orden de compra adjunta',
    slaMinutes: 1440,
    steps: [
      {
        stepId: 'ST-01',
        name: 'Validación de Margen y Descuento',
        type: 'VALIDATION',
        description: 'Verifica si el margen bruto supera el 18% y el descuento no excede el límite del vendedor.',
        nextStepId: 'ST-02',
        failureStepId: 'ST-01-APP',
        isAutomated: true,
      },
      {
        stepId: 'ST-01-APP',
        name: 'Aprobación Excepcional de Margen',
        type: 'APPROVAL',
        description: 'Requiere firma del Gerente de Ventas para proceder con precio con descuento especial.',
        nextStepId: 'ST-02',
        failureStepId: 'ST-REJECT',
        assignedRole: 'GERENTE_VENTAS',
        requiresHumanValidation: true,
        humanActionPrompt: 'Autorizar cotización con margen inferior al umbral estándar de la política.',
      },
      {
        stepId: 'ST-02',
        name: 'Evaluación de Línea de Crédito',
        type: 'VALIDATION',
        description: 'Comprueba que saldo insoluto + monto de pedido <= crédito asignado.',
        nextStepId: 'ST-03',
        failureStepId: 'ST-02-APP',
        isAutomated: true,
      },
      {
        stepId: 'ST-02-APP',
        name: 'Aprobación de Crédito Extraordinario',
        type: 'APPROVAL',
        description: 'Revisión por Gerente de Finanzas para extender crédito transitorio.',
        nextStepId: 'ST-03',
        failureStepId: 'ST-REJECT',
        assignedRole: 'FINANZAS',
        requiresHumanValidation: true,
        humanActionPrompt: 'Autorizar pedido que excede el límite de crédito vigente del cliente.',
      },
      {
        stepId: 'ST-03',
        name: 'Reserva Atómica de Inventario WMS',
        type: 'EXECUTION',
        description: 'Apartado de existencias en almacén central con actualización del saldo disponible.',
        nextStepId: 'ST-04',
        failureStepId: 'ST-ROLLBACK',
        isAutomated: true,
      },
      {
        stepId: 'ST-04',
        name: 'Orden de Despacho Logístico',
        type: 'TASK',
        description: 'Generación de guía de embarque y asignación de ruta de entrega.',
        nextStepId: 'ST-05',
        assignedRole: 'LOGISTICA',
      },
      {
        stepId: 'ST-05',
        name: 'Emisión de Factura Fiscal CFDI',
        type: 'EXECUTION',
        description: 'Timbrado de factura y creación de registro contable en cuentas por cobrar.',
        nextStepId: 'ST-06',
        isAutomated: true,
      },
      {
        stepId: 'ST-06',
        name: 'Cierre y Registro en Bitácora Transversal',
        type: 'AUDIT',
        description: 'Sellado criptográfico con Master Transaction ID y cálculo de contribución EBITDA.',
        nextStepId: 'ST-END',
        isAutomated: true,
      },
      {
        stepId: 'ST-REJECT',
        name: 'Rechazo Notificado',
        type: 'REJECTION',
        description: 'Notificación al vendedor y al cliente con motivo formal de declinación.',
      },
      {
        stepId: 'ST-ROLLBACK',
        name: 'Compensación y Rollback Atómico',
        type: 'COMPENSATION',
        description: 'Liberación de inventario y cancelación de apartados temporales.',
      },
      {
        stepId: 'ST-END',
        name: 'Fin de Proceso Exitoso',
        type: 'END',
        description: 'Transacción concluida con éxito.',
      },
    ],
    escalationRules: [
      { unattendedHours: 4, targetRole: 'GERENTE_VENTAS', notificationMessage: 'Pedido en espera de validación > 4 horas' },
      { unattendedHours: 12, targetRole: 'DIRECTOR', notificationMessage: 'Pedido de alto valor detenido > 12 horas' },
    ],
    rollbackStrategy: {
      enabled: true,
      compensatingSteps: [
        { stepId: 'ST-03', action: 'RELEASE_STOCK_RESERVATION', undoEndpoint: '/api/wms/release-hold' },
        { stepId: 'ST-05', action: 'VOID_UNPOSTED_INVOICE', undoEndpoint: '/api/finance/void-draft' },
      ],
      onRollbackNotificationRole: 'ADMINISTRADOR',
    },
    auditPolicy: 'FULL_TRACE',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-08-20T14:30:00Z',
    versionHistoryNotes: 'v3: Incorporada validación automática de límite de crédito y doble firma mancomunada.',
  },
  {
    workflowId: 'WF-3WAY-MATCH-02',
    version: 2,
    name: 'Proceso de Validación 3-Way Match (CXP)',
    category: 'CXP',
    owner: 'Cuentas por Pagar & Compras',
    status: 'ACTIVE',
    triggerEvent: 'AP_BILL_RECEIVED',
    triggerConditionDescription: 'Recepción de factura de proveedor XML/PDF para pago',
    slaMinutes: 2880,
    steps: [
      {
        stepId: 'ST-3W-01',
        name: 'Comprobación Antifraude & Duplicidad UUID',
        type: 'VALIDATION',
        description: 'Valida validez del CFDI ante el SAT y asegura que el UUID no fue registrado previamente.',
        nextStepId: 'ST-3W-02',
        failureStepId: 'ST-3W-BLOCK',
        isAutomated: true,
      },
      {
        stepId: 'ST-3W-02',
        name: 'Cruce Automatizado 3-Way Match',
        type: 'VALIDATION',
        description: 'Compara Cantidades y Precios Unitarios entre Orden de Compra, Recepción WMS y Factura.',
        nextStepId: 'ST-3W-03',
        failureStepId: 'ST-3W-DISCREPANCY',
        isAutomated: true,
      },
      {
        stepId: 'ST-3W-03',
        name: 'Programación Automática de Pago a Proveedor',
        type: 'EXECUTION',
        description: 'Calendarización del pago en fecha límite de descuento por pronto pago.',
        nextStepId: 'ST-3W-END',
        isAutomated: true,
      },
      {
        stepId: 'ST-3W-DISCREPANCY',
        name: 'Revisión Humana de Discrepancia',
        type: 'APPROVAL',
        description: 'Requiere dictamen del Comprador y Gerente de Finanzas ante variaciones de precio o cantidad.',
        nextStepId: 'ST-3W-03',
        failureStepId: 'ST-3W-REJECT',
        assignedRole: 'COMPRAS',
        requiresHumanValidation: true,
        humanActionPrompt: 'Aprobar pago con discrepancia material o solicitar refacturación/nota de crédito al proveedor.',
      },
      {
        stepId: 'ST-3W-BLOCK',
        name: 'Bloqueo Antifraude Inmediato',
        type: 'REJECTION',
        description: 'Registro de incidente en Bóveda de Auditoría y rechazo de la factura.',
      },
      {
        stepId: 'ST-3W-REJECT',
        name: 'Rechazo Formal de Pago',
        type: 'REJECTION',
        description: 'Notificación automática al proveedor detallando diferencias encontradas.',
      },
      {
        stepId: 'ST-3W-END',
        name: '3-Way Match Conciliado',
        type: 'END',
        description: 'Factura lista para dispersión programada.',
      },
    ],
    escalationRules: [
      { unattendedHours: 24, targetRole: 'FINANZAS', notificationMessage: 'Factura con discrepancia sin resolver por > 24h' },
    ],
    rollbackStrategy: {
      enabled: true,
      compensatingSteps: [
        { stepId: 'ST-3W-03', action: 'CANCEL_PAYMENT_SCHEDULE', undoEndpoint: '/api/treasury/cancel-schedule' },
      ],
      onRollbackNotificationRole: 'FINANZAS',
    },
    auditPolicy: 'FULL_TRACE',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-08-15T09:00:00Z',
  },
  {
    workflowId: 'WF-INVENTORY-REORDER-03',
    version: 1,
    name: 'Reabastecimiento Inteligente de Inventario',
    category: 'INVENTARIOS',
    owner: 'Almacén & Compras',
    status: 'ACTIVE',
    triggerEvent: 'STOCK_LOW',
    triggerConditionDescription: 'Existencia disponible menor o igual al punto de reorden',
    slaMinutes: 720,
    steps: [
      {
        stepId: 'ST-RE-01',
        name: 'Cálculo de Demanda y Lote Óptimo',
        type: 'EXECUTION',
        description: 'Calcula EOQ (Economic Order Quantity) y lead time del proveedor histórico.',
        nextStepId: 'ST-RE-02',
        isAutomated: true,
      },
      {
        stepId: 'ST-RE-02',
        name: 'Autorización Humana de Orden de Compra',
        type: 'APPROVAL',
        description: 'CONSCORE AI sugiere la orden, pero un comprador humano debe validar y firmar.',
        nextStepId: 'ST-RE-03',
        failureStepId: 'ST-RE-DISCARD',
        assignedRole: 'COMPRAS',
        requiresHumanValidation: true,
        humanActionPrompt: 'Autorizar creación de Orden de Compra para reabastecer stock crítico.',
      },
      {
        stepId: 'ST-RE-03',
        name: 'Transmisión de Orden al Proveedor',
        type: 'NOTIFICATION',
        description: 'Envío de PDF y archivo EDI de Orden de Compra al correo del proveedor.',
        nextStepId: 'ST-RE-END',
        isAutomated: true,
      },
      {
        stepId: 'ST-RE-DISCARD',
        name: 'Descarte de Sugerencia',
        type: 'REJECTION',
        description: 'Registro del motivo por el cual el comprador declinó reabastecer.',
      },
      {
        stepId: 'ST-RE-END',
        name: 'Reorden En Proceso',
        type: 'END',
        description: 'Seguimiento asignado a logística de recepción.',
      },
    ],
    escalationRules: [
      { unattendedHours: 8, targetRole: 'COMPRAS', notificationMessage: 'Stock crítico sin orden de reorden colocada' },
    ],
    rollbackStrategy: {
      enabled: false,
      compensatingSteps: [],
      onRollbackNotificationRole: 'COMPRAS',
    },
    auditPolicy: 'FULL_TRACE',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
  },
];

// ============================================================================
// BUSINESS RULES ENGINE
// ============================================================================

export const INITIAL_BUSINESS_RULES: BusinessRule[] = [
  {
    ruleId: 'RUL-001',
    code: 'RUL-CREDIT-CHECK',
    name: 'Validación Estricta de Línea de Crédito',
    module: 'FINANZAS',
    description: 'Bloquea órdenes que excedan la línea de crédito disponible o clientes con facturas vencidas > 30 días.',
    priority: 1,
    conditionGroups: [
      {
        logicalOperator: 'OR',
        conditions: [
          { field: 'customer.creditAvailable', operator: 'LESS_THAN', value: '$order.total' },
          { field: 'customer.maxDaysOverdue', operator: 'DAYS_OVERDUE_GREATER', value: 30 },
        ],
      },
    ],
    actions: [
      {
        type: 'BLOCK_TRANSACTION',
        severity: 'CRITICAL',
        payloadTemplate: { reason: 'Crédito insuficiente o mora superior a 30 días' },
      },
      {
        type: 'REQUEST_EXECUTIVE_APPROVAL',
        targetRole: 'FINANZAS',
        payloadTemplate: { approvalType: 'CREDIT_OVERRIDE_REQUEST' },
      },
    ],
    isEnabled: true,
    executionCount: 148,
    lastEvaluatedAt: '2026-08-27T09:00:00Z',
    lastTriggeredAt: '2026-08-27T09:00:00Z',
  },
  {
    ruleId: 'RUL-002',
    code: 'RUL-STOCK-REORDER',
    name: 'Gatillo Automático de Reorden de Inventario',
    module: 'INVENTARIOS',
    description: 'Genera recomendación de compra cuando el stock disponible es menor o igual al punto de reorden.',
    priority: 2,
    conditionGroups: [
      {
        logicalOperator: 'AND',
        conditions: [
          { field: 'product.availableStock', operator: 'LESS_EQUAL', value: '$product.reorderPoint' },
          { field: 'product.status', operator: 'EQUALS', value: 'ACTIVO' },
        ],
      },
    ],
    actions: [
      {
        type: 'SUGGEST_PURCHASE_ORDER',
        severity: 'WARNING',
        payloadTemplate: { calculationEngine: 'EOQ_AI_RECOMMENDATION' },
      },
      {
        type: 'CREATE_ENTERPRISE_ALERT',
        targetRole: 'COMPRAS',
        severity: 'WARNING',
        payloadTemplate: { title: 'Punto de Reorden Alcanzado' },
      },
    ],
    isEnabled: true,
    executionCount: 512,
    lastEvaluatedAt: '2026-08-27T07:45:00Z',
    lastTriggeredAt: '2026-08-27T07:45:00Z',
  },
  {
    ruleId: 'RUL-003',
    code: 'RUL-3WAY-MATCH-AUTO',
    name: 'Discrepancia en 3-Way Match CXP',
    module: 'CXP',
    description: 'Detecta discrepancias de precio unitario (>1%) o de cantidad física recibida.',
    priority: 1,
    conditionGroups: [
      {
        logicalOperator: 'OR',
        conditions: [
          { field: 'variance.amountPct', operator: 'GREATER_THAN', value: 0.01 },
          { field: 'variance.quantity', operator: 'NOT_EQUALS', value: 0 },
        ],
      },
    ],
    actions: [
      {
        type: 'BLOCK_TRANSACTION',
        severity: 'HIGH',
        payloadTemplate: { blockReason: 'Discrepancia material en 3-Way Match' },
      },
      {
        type: 'DISPATCH_NOTIFICATION',
        targetRole: 'COMPRAS',
        payloadTemplate: { channel: 'SYSTEM', message: 'Factura bloqueada por discrepancia vs Orden de Compra' },
      },
    ],
    isEnabled: true,
    executionCount: 89,
    lastEvaluatedAt: '2026-08-27T09:30:00Z',
    lastTriggeredAt: '2026-08-27T09:30:00Z',
  },
  {
    ruleId: 'RUL-004',
    code: 'RUL-MIN-MARGIN-APPROVAL',
    name: 'Control de Margen Bruto Mínimo de Venta',
    module: 'VENTAS',
    description: 'Requiere visto bueno de Gerencia si el margen bruto de la cotización es inferior al 18%.',
    priority: 2,
    conditionGroups: [
      {
        logicalOperator: 'AND',
        conditions: [
          { field: 'quote.grossMarginPct', operator: 'LESS_THAN', value: 0.18 },
        ],
      },
    ],
    actions: [
      {
        type: 'REQUEST_EXECUTIVE_APPROVAL',
        targetRole: 'GERENTE_VENTAS',
        payloadTemplate: { minimumAllowedMargin: 0.18 },
      },
    ],
    isEnabled: true,
    executionCount: 204,
    lastEvaluatedAt: '2026-08-27T09:25:00Z',
    lastTriggeredAt: '2026-08-27T09:25:00Z',
  },
];

// ============================================================================
// THREE-WAY MATCH INITIAL RECORDS
// ============================================================================

export const INITIAL_THREE_WAY_MATCH_RECORDS: ThreeWayMatchRecord[] = [
  {
    id: '3WM-2026-001',
    masterTransactionId: 'TRX-2026-98101',
    purchaseOrderId: 'OC-2026-108',
    poTotal: 450000,
    poQuantity: 1000,
    supplierName: 'Aceros y Prefabricados del Norte S.A. de C.V.',
    goodsReceiptId: 'REC-2026-094',
    receivedQuantity: 1000,
    supplierInvoiceId: 'FAC-PROV-88219',
    invoiceTotal: 450000,
    invoiceQuantity: 1000,
    varianceQuantity: 0,
    varianceAmount: 0,
    variancePct: 0,
    matchStatus: 'PERFECT_MATCH',
    status: 'AUTO_MATCHED',
    timestamp: '2026-08-27T08:00:00Z',
  },
  {
    id: '3WM-2026-002',
    masterTransactionId: 'TRX-2026-98102',
    purchaseOrderId: 'OC-2026-109',
    poTotal: 180000,
    poQuantity: 500,
    supplierName: 'Tubos y Conexiones Industriales de México',
    goodsReceiptId: 'REC-2026-095',
    receivedQuantity: 450,
    supplierInvoiceId: 'FAC-PROV-44120',
    invoiceTotal: 180000,
    invoiceQuantity: 500,
    varianceQuantity: -50,
    varianceAmount: 18000,
    variancePct: 10.0,
    matchStatus: 'DISCREPANCY_QUANTITY',
    discrepancyNotes: 'El proveedor facturó 500 unidades ($180,000) pero en almacén solo ingresaron 450 unidades. Faltante físico de 50 piezas.',
    status: 'DISCREPANCY_BLOCKED',
    timestamp: '2026-08-27T08:30:00Z',
  },
  {
    id: '3WM-2026-003',
    masterTransactionId: 'TRX-2026-98103',
    purchaseOrderId: 'OC-2026-110',
    poTotal: 320000,
    poQuantity: 800,
    supplierName: 'Química Especializada y Polímeros S.A.',
    goodsReceiptId: 'REC-2026-096',
    receivedQuantity: 800,
    supplierInvoiceId: 'FAC-PROV-11980',
    invoiceTotal: 345000,
    invoiceQuantity: 800,
    varianceQuantity: 0,
    varianceAmount: 25000,
    variancePct: 7.81,
    matchStatus: 'DISCREPANCY_PRICE',
    discrepancyNotes: 'Precio unitario facturado ($431.25) excede el pactado en la Orden de Compra ($400.00). Variación sin orden de cambio autorizada.',
    status: 'DISCREPANCY_BLOCKED',
    timestamp: '2026-08-27T09:15:00Z',
  },
];

// ============================================================================
// EXECUTIVE ACTION CENTER (HOY, URGENTE, ESTA_SEMANA, etc.)
// ============================================================================

export const INITIAL_AUTOMATION_ACTIONS: AutomationExecutiveAction[] = [
  {
    id: 'ACT-AUTO-01',
    category: 'HOY',
    title: 'Aprobación Excepcional de Límite de Crédito (Construcciones Delta)',
    description: 'El cliente solicitó pedido por $450,000 MXN con línea de crédito agotada. Cuenta con histórico de pago puntual a 28 días.',
    module: 'FINANZAS',
    owner: 'Lic. Mariana Garza (Gerente de Finanzas)',
    ownerRole: 'FINANZAS',
    priority: 'CRITICAL',
    dueDate: '2026-08-27T18:00:00Z',
    financialImpact: 450000,
    riskLevel: 'HIGH',
    approvalRequired: true,
    requiresHumanValidation: true,
    humanValidationNotice: 'REQUIERE VALIDACIÓN HUMANA: Aprobación de ampliación temporal de crédito comercial.',
    status: 'PENDING_APPROVAL',
    auditId: 'AUD-ACT-9901',
    masterTransactionId: 'TRX-2026-9901',
  },
  {
    id: 'ACT-AUTO-02',
    category: 'URGENTE',
    title: 'Resolución de Discrepancia 3-Way Match (Tubos Industriales)',
    description: 'Factura con 50 piezas no recibidas en almacén. Requiere nota de crédito por $18,000 MXN antes de autorizar pago.',
    module: 'CXP',
    owner: 'Ing. Roberto Méndez (Jefe de Compras)',
    ownerRole: 'COMPRAS',
    priority: 'HIGH',
    dueDate: '2026-08-27T14:00:00Z',
    financialImpact: 180000,
    riskLevel: 'HIGH',
    approvalRequired: true,
    requiresHumanValidation: true,
    humanValidationNotice: 'REQUIERE VALIDACIÓN HUMANA: Dictamen de refacturación o aceptación con nota de crédito.',
    status: 'PENDING_APPROVAL',
    auditId: 'AUD-ACT-9902',
    masterTransactionId: 'TRX-2026-98102',
  },
  {
    id: 'ACT-AUTO-03',
    category: 'ESTA_SEMANA',
    title: 'Renovación de Certificaciones DC-3 Operadores de Montacargas',
    description: '3 constancias de competencias laborales DC-3 vencen en 14 días. Programar curso de recertificación STPS.',
    module: 'RH',
    owner: 'Lic. Andrea Morales (Coordinadora de RH)',
    ownerRole: 'RH',
    priority: 'MEDIUM',
    dueDate: '2026-08-30T17:00:00Z',
    financialImpact: 45000,
    riskLevel: 'MEDIUM',
    approvalRequired: false,
    requiresHumanValidation: false,
    humanValidationNotice: 'Notificación informativa generada por motor de cumplimiento RH.',
    status: 'IN_PROGRESS',
    auditId: 'AUD-ACT-9903',
  },
  {
    id: 'ACT-AUTO-04',
    category: 'EN_APROBACION',
    title: 'Autorización de Orden de Compra Reabastecimiento Crítico (Resina Epóxica)',
    description: 'Stock por debajo del mínimo de seguridad (120 kg vs 250 kg mínimo). Lote sugerido: 500 kg ($285,000 MXN).',
    module: 'INVENTARIOS',
    owner: 'Lic. Fernando Ortiz (Director de Operaciones)',
    ownerRole: 'COMPRAS',
    priority: 'HIGH',
    dueDate: '2026-08-28T12:00:00Z',
    financialImpact: 285000,
    riskLevel: 'MEDIUM',
    approvalRequired: true,
    requiresHumanValidation: true,
    humanValidationNotice: 'REQUIERE VALIDACIÓN HUMANA: Firma de colocación de orden de compra formal.',
    status: 'PENDING_APPROVAL',
    auditId: 'AUD-ACT-9904',
  },
];

// ============================================================================
// OMNICHANNEL NOTIFICATIONS
// ============================================================================

export const INITIAL_OMNI_NOTIFICATIONS: OmniNotification[] = [
  {
    notificationId: 'NOT-001',
    recipientId: 'USR-FIN-01',
    recipientRole: 'FINANZAS',
    channel: 'APP',
    severity: 'HIGH',
    title: 'Excepción de Crédito Requerida',
    message: 'Pedido PED-2026-088 por $450,000 MXN requiere autorización por exceder línea de crédito.',
    entityType: 'Order',
    entityId: 'PED-2026-088',
    timestamp: '2026-08-27T09:00:00Z',
    actionLabel: 'Revisar Solicitud',
    status: 'DELIVERED',
    masterTransactionId: 'TRX-2026-9901',
  },
  {
    notificationId: 'NOT-002',
    recipientId: 'USR-COM-01',
    recipientRole: 'COMPRAS',
    channel: 'EMAIL',
    severity: 'WARNING',
    title: 'Stock Crítico Detectado: Resina Epóxica',
    message: 'Existencia actual (120 kg) se encuentra por debajo del stock mínimo de seguridad (250 kg).',
    entityType: 'Product',
    entityId: 'PROD-RES-01',
    timestamp: '2026-08-27T07:45:00Z',
    actionLabel: 'Ver Orden Sugerida',
    status: 'READ',
  },
  {
    notificationId: 'NOT-003',
    recipientId: 'USR-AUD-01',
    recipientRole: 'ADMINISTRADOR',
    channel: 'SYSTEM',
    severity: 'CRITICAL',
    title: 'Alerta Antifraude: Intento de Factura Duplicada',
    message: 'El sistema bloqueó el registro de la factura FAC-PROV-9941 con UUID SAT ya existente.',
    entityType: 'AP_Bill',
    entityId: 'FAC-PROV-9941',
    timestamp: '2026-08-25T11:40:00Z',
    actionLabel: 'Ver Registro de Auditoría',
    status: 'READ',
  },
];

// ============================================================================
// ESCALATION INCIDENTS
// ============================================================================

export const INITIAL_ESCALATION_INCIDENTS: EscalationIncident[] = [
  {
    incidentId: 'ESC-2026-01',
    sourceModule: 'SERVICIO',
    entityType: 'Ticket',
    entityId: 'TCK-2026-114',
    title: 'Ticket de Garantía Urgente sin Atender > 4 horas',
    slaMinutes: 240,
    elapsedMinutes: 290,
    currentLevel: 'SUPERVISOR',
    nextEscalationAt: '2026-08-27T13:00:00Z',
    history: [
      { tier: 'TIER_1', notifiedRole: 'SERVICIO_CLIENTE', timestamp: '2026-08-27T05:00:00Z', note: 'Ticket asignado' },
      { tier: 'SUPERVISOR', notifiedRole: 'CALIDAD', timestamp: '2026-08-27T09:00:00Z', note: 'Escalado por superar 4h sin contacto inicial' },
    ],
    resolved: false,
  },
];

// ============================================================================
// RPA CONTROLLED ROBOT BOTS
// ============================================================================

export const INITIAL_RPA_BOTS: RpaRobotTask[] = [
  {
    taskId: 'RPA-BOT-01',
    robotName: 'Bot de Conciliación Preliminar SAT-Bancos',
    category: 'DRAFT_RECONCILIATION',
    description: 'Descarga metadatos de CFDI emitidos/recibidos y propone pre-pólizas contables de conciliación bancaria.',
    scheduledCron: '0 4 * * *', // Daily 4 AM
    lastRunAt: '2026-08-27T04:00:00Z',
    status: 'COMPLETED',
    allowedAutonomous: true,
    sensitiveGuardrailsVerified: true,
    executionCount: 238,
    timeSavedPerRunMinutes: 45,
    logs: [
      '04:00:01Z - Iniciando lectura de repositorio CFDI SAT',
      '04:02:15Z - Procesados 142 comprobantes fiscales',
      '04:04:30Z - Generadas 138 sugerencias de conciliación exacta (97.1%)',
      '04:05:00Z - 4 registros con diferencia enviados a bandeja humana. Guardrails OK.',
    ],
  },
  {
    taskId: 'RPA-BOT-02',
    robotName: 'Bot de Clasificación y Extracción de Documentos',
    category: 'DOC_CLASSIFICATION',
    description: 'Lee facturas PDF de proveedores mediante OCR inteligente y extrae UUID, RFC, Subtotal e Impuestos.',
    scheduledCron: '*/15 * * * *', // Every 15 min
    lastRunAt: '2026-08-27T09:30:00Z',
    status: 'IDLE',
    allowedAutonomous: true,
    sensitiveGuardrailsVerified: true,
    executionCount: 1420,
    timeSavedPerRunMinutes: 8,
    logs: [
      '09:30:00Z - Monitoreando buzón fiscal de compras',
      '09:30:12Z - 3 nuevos archivos XML/PDF detectados y clasificados con éxito',
      '09:30:45Z - Validación de listas negras SAT 69-B completada: 0 coincidencias',
    ],
  },
  {
    taskId: 'RPA-BOT-03',
    robotName: 'Bot Preparador de Pre-Nómina y Asistencias',
    category: 'PRE_PAYROLL_PREPARATION',
    description: 'Consolida checadas de reloj biométrico, incidencias justificadas y horas extra para revisión de RH.',
    scheduledCron: '0 6 * * 1', // Weekly Monday
    lastRunAt: '2026-08-24T06:00:00Z',
    status: 'COMPLETED',
    allowedAutonomous: true,
    sensitiveGuardrailsVerified: true,
    executionCount: 34,
    timeSavedPerRunMinutes: 120,
    logs: [
      '06:00:00Z - Extracción de 145 expedientes de colaboradores',
      '06:02:30Z - Cálculo preliminar de comisiones y bonos de puntualidad',
      '06:03:00Z - Pre-nómina compilada y enviada a autorización de Dirección de RH. No transferencias autónomas.',
    ],
  },
  {
    taskId: 'RPA-BOT-04',
    robotName: 'Bot Guardián de Pagos (Bloqueo Autónomo)',
    category: 'REPORT_GENERATION',
    description: 'Verifica que ninguna dispersión bancaria proceda sin firma digital humana autorizada.',
    scheduledCron: '*/5 * * * *',
    lastRunAt: '2026-08-27T09:40:00Z',
    status: 'RUNNING',
    allowedAutonomous: true,
    sensitiveGuardrailsVerified: true,
    executionCount: 8920,
    timeSavedPerRunMinutes: 2,
    logs: [
      '09:40:00Z - Verificación de cola de pagos de tesorería',
      '09:40:02Z - 100% transacciones bancarias cuentan con firma mancomunada válida',
      '09:40:05Z - Bloqueo de transferencias autónomas activo y certificado',
    ],
  },
];

// ============================================================================
// DEAD LETTER QUEUE (DLQ)
// ============================================================================

export const INITIAL_DEAD_LETTER_QUEUE: DeadLetterQueueItem[] = [
  {
    id: 'DLQ-2026-001',
    eventId: 'EVT-ERR-901',
    eventType: 'TICKET_SLA_WARNING',
    correlationId: 'CORR-88129',
    payload: { ticketId: 'TCK-UNKNOWN-999', recipientWebhook: 'https://api.external-helpdesk.com/v1/webhook' },
    errorReason: 'HTTP 503 Service Unavailable: Endpoint del conector externo de tickets no respondió en 5000ms',
    failureTimestamp: '2026-08-27T03:14:22Z',
    retryCount: 3,
    maxRetries: 3,
    workflowId: 'WF-SERVICE-01',
    stackReference: 'AutomationEngine.dispatchWebhook:line 412 -> TimeoutError',
    resolutionStatus: 'UNRESOLVED',
    resolutionNotes: 'Agotados los 3 intentos con backoff progresivo (1s, 2s, 4s). Esperando reanudación de API externa.',
  },
];

// ============================================================================
// OBSERVABILITY & HEALTH METRICS
// ============================================================================

export const INITIAL_OBSERVABILITY_METRICS: AutomationObservabilityMetrics = {
  activeWorkflows: 14,
  completedWorkflows: 842,
  failedWorkflows: 1,
  pendingApprovals: 4,
  totalEventsProcessed: 14920,
  duplicateEventsBlocked: 38,
  totalRollbacks: 3,
  p50LatencyMs: 42,
  p95LatencyMs: 118,
  p99LatencyMs: 245,
  operationalHoursSaved: 385.5,
  totalFinancialValueImpactedMxn: 32450000,
  throughputEventsPerMin: 185,
  healthyServicesPct: 99.98,
};

// ============================================================================
// CHAOS TESTING SCENARIOS (10 Resilience Tests)
// ============================================================================

export const INITIAL_CHAOS_SCENARIOS: ChaosTestScenario[] = [
  {
    id: 'CHAOS-01',
    code: 'CH-API-DROP',
    title: 'Caída Abrupta de API Externa de Timbrado / Webhook',
    failureInjected: 'Inyección de timeout HTTP 504 simulado en llamada a microservicio de facturación.',
    expectedBehavior: 'Activación de Retry con Backoff Exponencial (1s, 2s, 4s) -> Si persiste, captura en Dead Letter Queue sin perder estado del pedido.',
    observedResult: 'PASS',
    recoveryStrategy: 'DLQ_CAPTURE',
    auditProof: 'HASH-CH01-8812-PASS: Transacción preservada en estado PENDIENTE_REINTENTO en Bóveda.',
    latencyMs: 145,
    details: 'El sistema capturó el payload íntegro y envió alerta al administrador sin bloquear la interfaz del usuario.',
  },
  {
    id: 'CHAOS-02',
    code: 'CH-DB-TIMEOUT',
    title: 'Timeout de Base de Datos en Reserva de Inventario',
    failureInjected: 'Bloqueo simulado de conexión SQL/ORM durante la reserva de 100 unidades en Almacén.',
    expectedBehavior: 'Rollback atómico integral del pedido. Cero inventario huérfano ni reservas parciales.',
    observedResult: 'PASS',
    recoveryStrategy: 'ROLLBACK_ATOMIC',
    auditProof: 'HASH-CH02-9931-PASS: Rollback ejecutado en 28ms. Stock previo restaurado a 500 unidades.',
    latencyMs: 32,
    details: 'Patrón BEGIN -> VALIDATE -> EXECUTE -> ROLLBACK verificado exitosamente.',
  },
  {
    id: 'CHAOS-03',
    code: 'CH-DUPLICATE-WEBHOOK',
    title: 'Duplicación de Webhook de Notificación de Cobro Bancario',
    failureInjected: 'Envío de 2 webhooks idénticos con mismo eventId y payload en un intervalo de 10ms.',
    expectedBehavior: 'Bloqueo inmediato por IdempotencyKey. Solo se aplica el pago una vez en CXC y Tesorería.',
    observedResult: 'PASS',
    recoveryStrategy: 'IDEMPOTENCY_DEDUPLICATION',
    auditProof: 'HASH-CH03-1102-PASS: Segundo evento rechazado con código IDEMPOTENT_DUPLICATE_BLOCKED.',
    latencyMs: 12,
    details: 'Se evitó el doble abono en la cuenta contable y la duplicidad de comisiones del vendedor.',
  },
  {
    id: 'CHAOS-04',
    code: 'CH-DOUBLE-CLICK',
    title: 'Doble Clic / Concurrencia Extrema en Autorización de Compra',
    failureInjected: 'Peticiones simultáneas concurrentes desde dos pestañas para autorizar la misma orden de compra.',
    expectedBehavior: 'Bloqueo optimista y control de idempotencia impiden doble generación de la orden.',
    observedResult: 'PASS',
    recoveryStrategy: 'IDEMPOTENCY_DEDUPLICATION',
    auditProof: 'HASH-CH04-5541-PASS: Bloqueo de estado concurrente exitoso.',
    latencyMs: 18,
    details: 'La segunda petición recibió estado 409 Conflict: Operación ya procesada por otro hilo.',
  },
  {
    id: 'CHAOS-05',
    code: 'CH-ROW-LOCK',
    title: 'Bloqueo de Registro (Row Lock) en Actualización de Saldo Cliente',
    failureInjected: 'Simulación de concurrencia en actualización de línea de crédito simultánea.',
    expectedBehavior: 'Cola serializada de mutación con verificación de consistencia transaccional.',
    observedResult: 'PASS',
    recoveryStrategy: 'PROGRESSIVE_RETRY',
    auditProof: 'HASH-CH05-7721-PASS: Reintento automático en 50ms con éxito.',
    latencyMs: 58,
    details: 'El saldo final coincidió con exactitud matemática tras la resolución de la contención.',
  },
  {
    id: 'CHAOS-06',
    code: 'CH-DUPLICATE-EVENT',
    title: 'Re-emisión de Evento LEAD_CREATED con Mismo Lead ID',
    failureInjected: 'Inyección de evento duplicado proveniente de conector de campañas publicitarias.',
    expectedBehavior: 'Deduplicación por correlación de entidad y descarte silencioso seguro.',
    observedResult: 'PASS',
    recoveryStrategy: 'IDEMPOTENCY_DEDUPLICATION',
    auditProof: 'HASH-CH06-3390-PASS: Evento duplicado marcado como DUPLICATE_SKIPPED.',
    latencyMs: 8,
    details: 'No se crearon leads gemelos ni se reasignó el vendedor original.',
  },
  {
    id: 'CHAOS-07',
    code: 'CH-INTERRUPTED-WF',
    title: 'Workflow Interrumpido a la Mitad por Reinicio del Sistema',
    failureInjected: 'Simulación de corte de energía durante el paso 3 de 6 del Workflow Comercial.',
    expectedBehavior: 'Recuperación del estado persistente desde el último punto de control auditado.',
    observedResult: 'PASS',
    recoveryStrategy: 'ROLLBACK_ATOMIC',
    auditProof: 'HASH-CH07-8842-PASS: Workflow reanudado en ST-03 sin pérdida de contexto.',
    latencyMs: 89,
    details: 'El motor de BPM continuó la ejecución a partir de la firma digital previa.',
  },
  {
    id: 'CHAOS-08',
    code: 'CH-FAILED-NOTIF',
    title: 'Fallo en Servicio SMTP / Push Omnicanal',
    failureInjected: 'Corte simulado del gateway de mensajería push/email.',
    expectedBehavior: 'La transacción principal culmina exitosamente; la notificación se encola para reintento diferido.',
    observedResult: 'PASS',
    recoveryStrategy: 'PROGRESSIVE_RETRY',
    auditProof: 'HASH-CH08-2210-PASS: Notificación desacoplada en cola asíncrona.',
    latencyMs: 25,
    details: 'El desacoplamiento del bus de eventos garantizó que el fallo de entrega no abortara el pedido.',
  },
  {
    id: 'CHAOS-09',
    code: 'CH-AUTONOMOUS-PAY-BLOCK',
    title: 'Intento de Inyección de Pago Bancario Autónomo por Script',
    failureInjected: 'Invocación forzada a endpoint de dispersión bancaria sin token de firma humana.',
    expectedBehavior: 'Bloqueo instantáneo con rechazo 403 Forbidden y disparo de incidente de seguridad.',
    observedResult: 'PASS',
    recoveryStrategy: 'ROLLBACK_ATOMIC',
    auditProof: 'HASH-CH09-0019-PASS: Guardrail Human-in-the-Loop activo. Transferencia denegada.',
    latencyMs: 14,
    details: 'Regla inviolable: CONSCORE AI no transfiere fondos de manera autónoma.',
  },
  {
    id: 'CHAOS-10',
    code: 'CH-INTEGRATION-RECOVERY',
    title: 'Recuperación de Red y Re-procesamiento desde Dead Letter Queue',
    failureInjected: 'Simulación de re-conexión de red tras 30 minutos de indisponibilidad.',
    expectedBehavior: 'Re-procesamiento selectivo (Re-drive) de elementos en DLQ con resolución 100% limpia.',
    observedResult: 'PASS',
    recoveryStrategy: 'PROGRESSIVE_RETRY',
    auditProof: 'HASH-CH10-9988-PASS: 100% elementos de DLQ re-procesados con éxito.',
    latencyMs: 95,
    details: 'La reconciliación restauró la sincronización total sin discrepancias contables.',
  },
];

// ============================================================================
// LIVE EVENT STREAM SAMPLE DATA
// ============================================================================

export const INITIAL_EVENT_STREAM: EnterpriseEvent[] = [
  {
    eventId: 'EVT-2026-9001',
    eventType: 'QUOTE_ACCEPTED',
    entityType: 'Quote',
    entityId: 'COT-2026-094',
    masterTransactionId: 'TRX-2026-9901',
    timestamp: '2026-08-27T09:20:00Z',
    userId: 'USR-VND-02',
    sourceModule: 'VENTAS',
    payload: { quoteId: 'COT-2026-094', customerId: 'CTE-001', customerName: 'Construcciones Delta S.A.', total: 450000 },
    severity: 'INFO',
    correlationId: 'CORR-9901',
    idempotencyKey: 'IDEMP-COT-094-ACCEPT',
    processed: true,
    processedAt: '2026-08-27T09:20:01Z',
    workflowExecutionId: 'EXEC-WF-001',
  },
  {
    eventId: 'EVT-2026-9002',
    eventType: 'ORDER_CREDIT_BLOCKED',
    entityType: 'Order',
    entityId: 'PED-2026-088',
    masterTransactionId: 'TRX-2026-9901',
    timestamp: '2026-08-27T09:20:02Z',
    userId: 'SYS-RULES-ENGINE',
    sourceModule: 'FINANZAS',
    payload: { orderId: 'PED-2026-088', orderTotal: 450000, creditLimit: 300000, availableCredit: 0 },
    severity: 'HIGH',
    correlationId: 'CORR-9901',
    idempotencyKey: 'IDEMP-PED-088-CR-BLK',
    processed: true,
    processedAt: '2026-08-27T09:20:03Z',
  },
  {
    eventId: 'EVT-2026-9003',
    eventType: 'STOCK_LOW',
    entityType: 'Product',
    entityId: 'PROD-RES-01',
    timestamp: '2026-08-27T07:45:00Z',
    userId: 'SYS-INVENTORY-MONITOR',
    sourceModule: 'INVENTARIOS',
    payload: { productId: 'PROD-RES-01', productName: 'Resina Epóxica Industrial', currentStock: 120, reorderPoint: 250 },
    severity: 'WARNING',
    correlationId: 'CORR-7782',
    idempotencyKey: 'IDEMP-STK-LOW-RES-01',
    processed: true,
    processedAt: '2026-08-27T07:45:01Z',
  },
  {
    eventId: 'EVT-2026-9004',
    eventType: 'THREE_WAY_MATCH_DISCREPANCY',
    entityType: 'AP_Bill',
    entityId: 'FAC-PROV-44120',
    masterTransactionId: 'TRX-2026-98102',
    timestamp: '2026-08-27T08:30:00Z',
    userId: 'SYS-3WAY-ENGINE',
    sourceModule: 'CXP',
    payload: { invoiceId: 'FAC-PROV-44120', invoiceQuantity: 500, receivedQuantity: 450, varianceQuantity: -50 },
    severity: 'HIGH',
    correlationId: 'CORR-8831',
    idempotencyKey: 'IDEMP-3WM-FAC-44120',
    processed: true,
    processedAt: '2026-08-27T08:30:02Z',
  },
];
