/**
 * @license
 * CONSCORE ERP IA - Initial Data for Customer Service, Warranties, Returns, Quality, CAPA, NPS & SLAs
 * FASE 11: Datos empresariales certificados para aislamiento térmico
 */

import {
  ServiceTicket,
  SLARule,
  SLAAlert,
  WarrantyCertificate,
  WarrantyClaim,
  CustomerReturn,
  QualityIncident,
  CAPAAction,
  CustomerSurvey,
} from '../types/customerServiceTypes';

export const INITIAL_SLA_RULES: SLARule[] = [
  {
    id: 'SLA-001',
    name: 'SLA Crítico / Tier A (VIP)',
    priority: 'CRITICA',
    customerTier: 'A',
    category: 'ALL',
    firstResponseMinutes: 15,
    resolutionHours: 4,
    warningThresholdPct: 75,
    escalationRole: 'GERENTE_VENTAS',
    isActive: true,
  },
  {
    id: 'SLA-002',
    name: 'SLA Alta Prioridad / Reclamos de Entrega',
    priority: 'ALTA',
    customerTier: 'ALL',
    category: 'ENTREGA',
    firstResponseMinutes: 30,
    resolutionHours: 8,
    warningThresholdPct: 75,
    escalationRole: 'LOGISTICA',
    isActive: true,
  },
  {
    id: 'SLA-003',
    name: 'SLA Calidad & Garantías',
    priority: 'ALTA',
    customerTier: 'ALL',
    category: 'GARANTIA',
    firstResponseMinutes: 60,
    resolutionHours: 24,
    warningThresholdPct: 75,
    escalationRole: 'CALIDAD',
    isActive: true,
  },
  {
    id: 'SLA-004',
    name: 'SLA Estándar Media',
    priority: 'MEDIA',
    customerTier: 'ALL',
    category: 'ALL',
    firstResponseMinutes: 120,
    resolutionHours: 48,
    warningThresholdPct: 75,
    escalationRole: 'SERVICIO_CLIENTE',
    isActive: true,
  },
  {
    id: 'SLA-005',
    name: 'SLA Consultas y General',
    priority: 'BAJA',
    customerTier: 'ALL',
    category: 'CONSULTA',
    firstResponseMinutes: 240,
    resolutionHours: 72,
    warningThresholdPct: 75,
    escalationRole: 'SERVICIO_CLIENTE',
    isActive: true,
  },
];

export const INITIAL_SERVICE_TICKETS: ServiceTicket[] = [
  {
    id: 'TCK-001',
    ticketNumber: 'TCK-2026-0001',
    customerId: 'CUST-001',
    customerName: 'Aislantes y Recubrimientos Industriales del Norte S.A. de C.V.',
    customerRfc: 'ARI880415NK2',
    customerTier: 'A',
    contactName: 'Ing. Roberto Garza Sada',
    contactPhone: '81-8345-9920',
    contactEmail: 'rgarza@aislantesnorte.com',
    salespersonId: 'USR-003',
    salespersonName: 'Lic. Fernando Morales',
    orderId: 'ORD-2026-0012',
    orderNumber: 'PED-2026-0012',
    invoiceFolio: 'FAC-2026-0089',
    productId: 'PROD-001',
    productCode: 'PRE-1080',
    productName: 'Preformado de Lana Mineral 2" x 1.5"',
    category: 'ENTREGA',
    subcategory: 'Retraso de Unidad en Patio de Obra',
    priority: 'ALTA',
    status: 'EN_PROCESO',
    title: 'Unidad de reparto demorada en planta Monterrey',
    description: 'El cliente reporta que la unidad con 120 tramos de PRE-1080 tenía ventana de descarga a las 09:00 hrs y a las 11:30 hrs aún no arriba a la nave 4.',
    department: 'Logística y Tráfico',
    assignedUserId: 'USR-007',
    assignedUserName: 'Ing. Rodrigo Mendoza (Logística)',
    createdAt: '2026-08-25T09:30:00Z',
    updatedAt: '2026-08-25T10:15:00Z',
    firstResponseAt: '2026-08-25T09:45:00Z',
    firstResponseDeadline: '2026-08-25T10:00:00Z',
    resolutionDeadline: '2026-08-25T17:30:00Z',
    firstResponseSlaMinutes: 30,
    resolutionSlaHours: 8,
    slaBreached: false,
    firstResponseBreached: false,
    resolutionBreached: false,
    comments: [
      {
        id: 'COM-001',
        userId: 'USR-007',
        userName: 'Ing. Rodrigo Mendoza',
        userRole: 'LOGISTICA',
        isInternal: false,
        content: 'Hablamos con el operador de la unidad C-03. Hubo bloqueo vial por obras en Libramiento Noreste. Ya se encuentra en caseta de acceso a la planta.',
        timestamp: '2026-08-25T10:15:00Z',
      },
    ],
    timeline: [
      {
        id: 'EVT-001',
        action: 'Ticket Creado',
        userId: 'USR-003',
        userName: 'Lic. Fernando Morales',
        timestamp: '2026-08-25T09:30:00Z',
        details: 'Reporte ingresado desde portal comercial.',
        newStatus: 'ABIERTO',
      },
      {
        id: 'EVT-002',
        action: 'Ticket Asignado',
        userId: 'USR-007',
        userName: 'Ing. Rodrigo Mendoza',
        timestamp: '2026-08-25T09:45:00Z',
        details: 'Asignado a Logística para rastreo GPS.',
        previousStatus: 'ABIERTO',
        newStatus: 'EN_PROCESO',
      },
    ],
    idempotencyKey: 'TCK_IDEM_20260825_001',
  },
  {
    id: 'TCK-002',
    ticketNumber: 'TCK-2026-0002',
    customerId: 'CUST-002',
    customerName: 'Termoacústicos y Montajes Industriales de México S.A.',
    customerRfc: 'TMI940620TL4',
    customerTier: 'A',
    contactName: 'Arq. Laura Esther Peña',
    contactPhone: '55-5678-1234',
    contactEmail: 'lpena@termoacusticos.mx',
    salespersonId: 'USR-004',
    salespersonName: 'Ing. Carlos Slim V.',
    orderId: 'ORD-2026-0015',
    orderNumber: 'PED-2026-0015',
    invoiceFolio: 'FAC-2026-0094',
    productId: 'PROD-004',
    productCode: 'AIS-FIBRA-50',
    productName: 'Colchoneta de Fibra de Vidrio 50mm con Foil de Aluminio',
    category: 'CALIDAD',
    subcategory: 'Desprendimiento superficial de foil',
    priority: 'CRITICA',
    status: 'ESPERA_INTERNA',
    title: 'Foil de aluminio con adhesión irregular en 15 rollos',
    description: 'En la inspección de recepción en obra Termoeléctrica Tula se detectó que el foil ASJ presenta desprendimiento en los extremos en 15 rollos del lote LOTE-2026-F08.',
    department: 'Aseguramiento de Calidad',
    assignedUserId: 'USR-002',
    assignedUserName: 'Lic. Claudia Mendoza',
    createdAt: '2026-08-24T14:00:00Z',
    updatedAt: '2026-08-25T08:30:00Z',
    firstResponseAt: '2026-08-24T14:12:00Z',
    firstResponseDeadline: '2026-08-24T14:15:00Z',
    resolutionDeadline: '2026-08-24T18:00:00Z',
    firstResponseSlaMinutes: 15,
    resolutionSlaHours: 4,
    slaBreached: true,
    firstResponseBreached: false,
    resolutionBreached: true,
    qualityIncidentId: 'NC-CAL-001',
    warrantyClaimId: 'REC-GAR-001',
    returnId: 'DEV-001',
    comments: [
      {
        id: 'COM-002',
        userId: 'USR-002',
        userName: 'Lic. Claudia Mendoza',
        userRole: 'ADMINISTRADOR',
        isInternal: true,
        content: 'Se abrió la No Conformidad NC-CAL-001 y se notificó al proveedor Owens Corning para dictamen técnico.',
        timestamp: '2026-08-24T15:20:00Z',
      },
    ],
    timeline: [
      {
        id: 'EVT-003',
        action: 'Ticket Creado',
        userId: 'USR-004',
        userName: 'Ing. Carlos Slim V.',
        timestamp: '2026-08-24T14:00:00Z',
        details: 'Reporte ingresado con fotos adjuntas.',
        newStatus: 'ABIERTO',
      },
      {
        id: 'EVT-004',
        action: 'Canalizado a Calidad',
        userId: 'USR-002',
        userName: 'Lic. Claudia Mendoza',
        timestamp: '2026-08-24T14:12:00Z',
        details: 'Enviado a laboratorio y solicitud de muestra.',
        previousStatus: 'ABIERTO',
        newStatus: 'ESPERA_INTERNA',
      },
    ],
    idempotencyKey: 'TCK_IDEM_20260824_002',
  },
  {
    id: 'TCK-003',
    ticketNumber: 'TCK-2026-0003',
    customerId: 'CUST-003',
    customerName: 'Constructora e Inmobiliaria Valle de México',
    customerRfc: 'CIV030911KP9',
    customerTier: 'B',
    contactName: 'Ing. Miguel Ángel Osorio',
    contactPhone: '55-4321-8765',
    contactEmail: 'mosorio@civm.mx',
    category: 'FACTURACION',
    subcategory: 'Corrección de Uso de CFDI',
    priority: 'MEDIA',
    status: 'RESUELTO',
    title: 'Cambio de uso de CFDI de G01 a G03 en factura FAC-0078',
    description: 'Solicitan refacturación o sustitución de CFDI con relación 04 por cambio contable en su departamento de compras.',
    department: 'Finanzas y Facturación',
    assignedUserId: 'USR-008',
    assignedUserName: 'C.P. Mariana Rivas (Finanzas)',
    createdAt: '2026-08-22T11:00:00Z',
    updatedAt: '2026-08-22T14:30:00Z',
    firstResponseAt: '2026-08-22T11:45:00Z',
    resolvedAt: '2026-08-22T14:30:00Z',
    closedAt: '2026-08-22T15:00:00Z',
    firstResponseDeadline: '2026-08-22T13:00:00Z',
    resolutionDeadline: '2026-08-24T11:00:00Z',
    firstResponseSlaMinutes: 120,
    resolutionSlaHours: 48,
    slaBreached: false,
    firstResponseBreached: false,
    resolutionBreached: false,
    resolutionSummary: 'Se canceló FAC-0078 ante SAT y se emitió FAC-0082 con relación tipo 04 y uso G03 Gastos en general.',
    customerRating: 5,
    customerSatisfactionNotes: 'Atención rápida y CFDI correcto timbrado el mismo día.',
    comments: [],
    timeline: [
      {
        id: 'EVT-005',
        action: 'Ticket Creado',
        userId: 'USR-008',
        userName: 'C.P. Mariana Rivas',
        timestamp: '2026-08-22T11:00:00Z',
        details: 'Ingresado por correo de cobranza.',
        newStatus: 'ABIERTO',
      },
      {
        id: 'EVT-006',
        action: 'Ticket Resuelto',
        userId: 'USR-008',
        userName: 'C.P. Mariana Rivas',
        timestamp: '2026-08-22T14:30:00Z',
        details: 'Factura timbrada y enviada XML/PDF al portal del cliente.',
        previousStatus: 'EN_PROCESO',
        newStatus: 'RESUELTO',
      },
    ],
    idempotencyKey: 'TCK_IDEM_20260822_003',
  },
  {
    id: 'TCK-004',
    ticketNumber: 'TCK-2026-0004',
    customerId: 'CUST-004',
    customerName: 'Climas y Refrigeración del Bajío S.A.',
    customerRfc: 'CRB110204AB1',
    customerTier: 'C',
    contactName: 'Ing. Esteban Duarte',
    contactPhone: '477-712-4455',
    contactEmail: 'eduarte@climasbajio.com',
    category: 'TECNICO',
    subcategory: 'Ficha técnica de conductividad térmica',
    priority: 'BAJA',
    status: 'RESUELTO',
    title: 'Solicitud de certificado de prueba ASTM C547 para Preformado',
    description: 'El supervisor de obra de CFE requiere memoria de cálculo y certificado de conductividad para PRE-1080.',
    department: 'Ingeniería y Soporte Técnico',
    assignedUserId: 'USR-002',
    assignedUserName: 'Lic. Claudia Mendoza',
    createdAt: '2026-08-20T16:00:00Z',
    updatedAt: '2026-08-21T09:00:00Z',
    firstResponseAt: '2026-08-21T08:30:00Z',
    resolvedAt: '2026-08-21T09:00:00Z',
    closedAt: '2026-08-21T09:00:00Z',
    firstResponseDeadline: '2026-08-21T10:00:00Z',
    resolutionDeadline: '2026-08-23T16:00:00Z',
    firstResponseSlaMinutes: 240,
    resolutionSlaHours: 72,
    slaBreached: false,
    firstResponseBreached: false,
    resolutionBreached: false,
    resolutionSummary: 'Se envió reporte de laboratorio oficial ASTM C547 con k=0.034 W/m·K a 24°C.',
    customerRating: 5,
    comments: [],
    timeline: [],
    idempotencyKey: 'TCK_IDEM_20260820_004',
  },
];

export const INITIAL_WARRANTIES: WarrantyCertificate[] = [
  {
    id: 'GAR-001',
    folio: 'GAR-2026-0082',
    customerId: 'CUST-001',
    customerName: 'Aislantes y Recubrimientos Industriales del Norte S.A. de C.V.',
    orderId: 'ORD-2026-0012',
    orderNumber: 'PED-2026-0012',
    invoiceFolio: 'FAC-2026-0089',
    productId: 'PROD-001',
    productCode: 'PRE-1080',
    productName: 'Preformado de Lana Mineral 2" x 1.5"',
    lotNumber: 'LOT-LM-2026-04',
    quantity: 120,
    unit: 'TRAMO',
    purchaseDate: '2026-07-15',
    deliveryDate: '2026-07-18',
    warrantyStart: '2026-07-18',
    warrantyEnd: '2028-07-18',
    warrantyMonths: 24,
    termsAndConditions: 'Garantía contra degradación de densidad, desintegración térmica hasta 650°C y deformación estructural bajo condiciones normales de instalación.',
    status: 'ACTIVA',
    claimsCount: 0,
  },
  {
    id: 'GAR-002',
    folio: 'GAR-2026-0091',
    customerId: 'CUST-002',
    customerName: 'Termoacústicos y Montajes Industriales de México S.A.',
    orderId: 'ORD-2026-0015',
    orderNumber: 'PED-2026-0015',
    invoiceFolio: 'FAC-2026-0094',
    productId: 'PROD-004',
    productCode: 'AIS-FIBRA-50',
    productName: 'Colchoneta de Fibra de Vidrio 50mm con Foil de Aluminio',
    lotNumber: 'LOTE-2026-F08',
    quantity: 80,
    unit: 'ROLLO',
    purchaseDate: '2026-08-10',
    deliveryDate: '2026-08-12',
    warrantyStart: '2026-08-12',
    warrantyEnd: '2027-08-12',
    warrantyMonths: 12,
    termsAndConditions: 'Garantía de barrera de vapor ASJ y resistencia a la tracción superficial según norma ASTM C1136.',
    status: 'RECLAMADA',
    claimsCount: 1,
  },
];

export const INITIAL_WARRANTY_CLAIMS: WarrantyClaim[] = [
  {
    id: 'REC-GAR-001',
    claimFolio: 'REC-GAR-2026-0012',
    warrantyId: 'GAR-002',
    warrantyFolio: 'GAR-2026-0091',
    ticketId: 'TCK-002',
    ticketNumber: 'TCK-2026-0002',
    customerId: 'CUST-002',
    customerName: 'Termoacústicos y Montajes Industriales de México S.A.',
    productId: 'PROD-004',
    productCode: 'AIS-FIBRA-50',
    productName: 'Colchoneta de Fibra de Vidrio 50mm con Foil de Aluminio',
    lotNumber: 'LOTE-2026-F08',
    quantityClaimed: 15,
    defectDescription: 'Desprendimiento del foil de aluminio por falta de curado de adhesivo en línea de producción.',
    installationEnvironment: 'Tuberías de vapor en nave industrial cerrada, 45°C ambiente.',
    evidencePhotos: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=300'],
    status: 'EN_REVISION',
    aiRecommendation: 'APPROVE',
    aiConfidencePct: 92,
    aiAnalysisNotes: 'Falla típica por polimerización deficiente en lote F08 reportado por Owens Corning. Cumple condiciones de garantía.',
    createdAt: '2026-08-24T14:30:00Z',
    updatedAt: '2026-08-25T08:30:00Z',
  },
];

export const INITIAL_CUSTOMER_RETURNS: CustomerReturn[] = [
  {
    id: 'DEV-001',
    returnFolio: 'DEV-2026-0045',
    ticketId: 'TCK-002',
    ticketNumber: 'TCK-2026-0002',
    customerId: 'CUST-002',
    customerName: 'Termoacústicos y Montajes Industriales de México S.A.',
    orderId: 'ORD-2026-0015',
    orderNumber: 'PED-2026-0015',
    invoiceFolio: 'FAC-2026-0094',
    reason: 'PRODUCTO_DEFECTUOSO',
    reasonNotes: 'Rollos con foil despegado pertenecientes al lote LOTE-2026-F08.',
    status: 'AUTORIZADA',
    items: [
      {
        id: 'DVI-001',
        productId: 'PROD-004',
        productCode: 'AIS-FIBRA-50',
        productName: 'Colchoneta de Fibra de Vidrio 50mm con Foil de Aluminio',
        lotNumber: 'LOTE-2026-F08',
        unit: 'ROLLO',
        quantityRequested: 15,
        quantityReceived: 0,
        quantityApproved: 15,
        quantityRejected: 0,
        unitCost: 420.00,
        unitPrice: 650.00,
        inspectionCondition: 'DEFECTO_REPARABLE',
        restockWarehouseId: 'WH-001',
        restockWarehouseName: 'Almacén Central Tlalnepantla',
        restockLocation: 'Nave 2 / Cuarentena Calidad',
        dispositionAction: 'DEVOLUCION_PROVEEDOR',
      },
    ],
    totalValue: 9750.00,
    pickupRequired: true,
    pickupAddress: 'Av. Industria Termoeléctrica #104, Tula, Hgo.',
    inspectionPassed: false,
    authorizedBy: 'USR-002',
    authorizedByName: 'Lic. Claudia Mendoza',
    authorizedAt: '2026-08-24T16:00:00Z',
    refundMethod: 'CAMBIO_FISICO',
    createdAt: '2026-08-24T15:00:00Z',
    updatedAt: '2026-08-24T16:00:00Z',
    idempotencyKey: 'DEV_IDEM_20260824_001',
  },
];

export const INITIAL_QUALITY_INCIDENTS: QualityIncident[] = [
  {
    id: 'NC-CAL-001',
    incidentFolio: 'NC-CAL-2026-0034',
    title: 'Adherencia deficiente de foil en colchoneta AIS-FIBRA-50 Lote F08',
    date: '2026-08-24',
    productId: 'PROD-004',
    productCode: 'AIS-FIBRA-50',
    productName: 'Colchoneta de Fibra de Vidrio 50mm con Foil de Aluminio',
    lotNumber: 'LOTE-2026-F08',
    supplierId: 'SUP-001',
    supplierName: 'Owens Corning México S. de R.L. de C.V.',
    warehouseId: 'WH-001',
    warehouseName: 'Almacén Central Tlalnepantla',
    customerId: 'CUST-002',
    customerName: 'Termoacústicos y Montajes Industriales de México S.A.',
    severity: 'MAYOR',
    category: 'DESPRENDIMIENTO_ALUMINIO',
    affectedQuantity: 15,
    unit: 'ROLLO',
    estimatedLoss: 6300.00,
    description: 'Al desenrollar la colchoneta en obra, el foil de aluminio reforzado con malla de fibra se separa de la base de fibra de vidrio.',
    rootCauseMethod: '5_WHYS',
    rootCauseAnalysis: '1. ¿Por qué se despega? El adhesivo Hot-Melt no tuvo curado adecuado. 2. ¿Por qué? Temperatura de boquillas aplicadoras a 130°C en vez de 165°C en la planta del proveedor. 3. ¿Por qué? Sensor termopar descalibrado durante el turno nocturno.',
    disposition: 'DEVOLUCION_PROVEEDOR',
    capaId: 'CAPA-001',
    capaFolio: 'CAPA-2026-0015',
    status: 'EN_CAPA',
    recordedBy: 'USR-002',
    recordedByName: 'Lic. Claudia Mendoza',
  },
  {
    id: 'NC-CAL-002',
    incidentFolio: 'NC-CAL-2026-0035',
    title: 'Tolerancia de diámetro interior fuera de norma en PRE-1080',
    date: '2026-08-15',
    productId: 'PROD-001',
    productCode: 'PRE-1080',
    productName: 'Preformado de Lana Mineral 2" x 1.5"',
    lotNumber: 'LOT-LM-2026-03',
    supplierId: 'SUP-002',
    supplierName: 'Saint-Gobain / Isover México',
    warehouseId: 'WH-001',
    warehouseName: 'Almacén Central Tlalnepantla',
    severity: 'MENOR',
    category: 'DIMENSIONES_FUERA_TOLERANCIA',
    affectedQuantity: 8,
    unit: 'TRAMO',
    estimatedLoss: 1480.00,
    description: 'Diámetro interior con ovalamiento superior a 3mm, dificultando el ensamble en tubería de 2 pulgadas.',
    rootCauseMethod: 'DIRECTA',
    rootCauseAnalysis: 'Apilamiento excesivo en rack durante almacenamiento transitorio en almacén proveedor.',
    disposition: 'SCRAP',
    status: 'CERRADA',
    recordedBy: 'USR-006',
    recordedByName: 'Jefe de Almacén',
    closedAt: '2026-08-18T10:00:00Z',
  },
];

export const INITIAL_CAPA_ACTIONS: CAPAAction[] = [
  {
    id: 'CAPA-001',
    capaFolio: 'CAPA-2026-0015',
    incidentId: 'NC-CAL-001',
    incidentFolio: 'NC-CAL-2026-0034',
    title: 'Calibración y verificación de temperatura en aplicación de foil ASJ',
    rootCauseIdentified: 'Termopar de aplicador Hot-Melt descalibrado en planta proveedor.',
    correctiveAction: 'Sustitución inmediata de los 15 rollos al cliente sin costo y cuarentena del lote restante.',
    preventiveAction: 'Auditoría en recepción: prueba destructiva de peel-strength (desprendimiento) a 1 rollo por tarima y solicitud de certificado de calibración mensual al proveedor.',
    ownerId: 'USR-002',
    ownerName: 'Lic. Claudia Mendoza',
    targetDate: '2026-09-15',
    implementationDate: '2026-08-25',
    status: 'EN_PROCESO',
    isOverdue: false,
    costEstimate: 2500.00,
    createdAt: '2026-08-24T17:00:00Z',
    updatedAt: '2026-08-25T09:00:00Z',
  },
];

export const INITIAL_CUSTOMER_SURVEYS: CustomerSurvey[] = [
  {
    id: 'SURV-001',
    surveyType: 'NPS',
    customerId: 'CUST-001',
    customerName: 'Aislantes y Recubrimientos Industriales del Norte S.A. de C.V.',
    orderId: 'ORD-2026-0010',
    orderNumber: 'PED-2026-0010',
    salespersonId: 'USR-003',
    salespersonName: 'Lic. Fernando Morales',
    score: 10,
    classification: 'PROMOTER',
    feedbackComments: 'Excelente calidad en lana mineral y cumplimiento en tiempos de entrega. Son nuestro proveedor de confianza.',
    primaryFactor: 'CALIDAD_PRODUCTO',
    followUpRequired: false,
    followUpCompleted: true,
    createdAt: '2026-08-15T12:00:00Z',
  },
  {
    id: 'SURV-002',
    surveyType: 'NPS',
    customerId: 'CUST-002',
    customerName: 'Termoacústicos y Montajes Industriales de México S.A.',
    orderId: 'ORD-2026-0015',
    orderNumber: 'PED-2026-0015',
    salespersonId: 'USR-004',
    salespersonName: 'Ing. Carlos Slim V.',
    score: 6,
    classification: 'DETRACTOR',
    feedbackComments: 'Tuvimos problema con el foil de la fibra de vidrio en la obra de Tula. La atención fue rápida pero el contratiempo nos afectó medio turno.',
    primaryFactor: 'CALIDAD_PRODUCTO',
    followUpRequired: true,
    followUpTicketId: 'TCK-002',
    followUpCompleted: false,
    createdAt: '2026-08-24T18:00:00Z',
  },
  {
    id: 'SURV-003',
    surveyType: 'NPS',
    customerId: 'CUST-003',
    customerName: 'Constructora e Inmobiliaria Valle de México',
    orderId: 'ORD-2026-0008',
    orderNumber: 'PED-2026-0008',
    salespersonId: 'USR-003',
    salespersonName: 'Lic. Fernando Morales',
    score: 9,
    classification: 'PROMOTER',
    feedbackComments: 'Buen servicio de facturación y asesoría técnica de primer nivel.',
    primaryFactor: 'ATENCION_ASESOR',
    followUpRequired: false,
    followUpCompleted: true,
    createdAt: '2026-08-18T10:30:00Z',
  },
  {
    id: 'SURV-004',
    surveyType: 'CSAT',
    customerId: 'CUST-004',
    customerName: 'Climas y Refrigeración del Bajío S.A.',
    orderId: 'ORD-2026-0005',
    score: 5,
    classification: 'SATISFIED',
    feedbackComments: 'La documentación técnica ASTM llegó súper rápido.',
    primaryFactor: 'ATENCION_ASESOR',
    followUpRequired: false,
    followUpCompleted: true,
    createdAt: '2026-08-21T11:00:00Z',
  },
];
