/**
 * @license
 * CONSCORE ERP IA - Governance, Risk, Compliance & Internal Control Initial Data
 * FASE 13 - Datos Iniciales Certificados para Gobierno Corporativo, SoD, ERM, Compliance y Documentos
 */

import {
  CorporatePolicy,
  CorporateCommittee,
  AuthorityLimitRule,
  ExecutiveApprovalRequest,
  SoDConflictRule,
  SoDViolationRisk,
  EnterpriseRisk,
  ComplianceObligation,
  CorrectiveActionPlan,
  CorporateDocument,
  EnterpriseAlert,
  AnomalyDetectionResult,
  GovernanceExecutiveAction,
  MasterAuditTraceTimeline,
} from '../types/governanceRiskComplianceTypes';

// ==========================================
// 1. POLÍTICAS CORPORATIVAS INICIALES
// ==========================================

export const INITIAL_CORPORATE_POLICIES: CorporatePolicy[] = [
  {
    id: 'POL-001',
    code: 'POL-GOV-001',
    name: 'Código de Ética, Conducta y Cero Tolerancia a la Corrupción',
    description: 'Lineamientos éticos obligatorios para todos los colaboradores, directores y proveedores de CONSCORE.',
    area: 'DIRECCION_GENERAL',
    version: '2.4',
    status: 'ACTIVE',
    effectiveDate: '2026-01-01',
    expirationDate: '2026-12-31',
    ownerId: 'USR-001',
    ownerName: 'Lic. Roberto Garza (Director General)',
    approverId: 'USR-001',
    approverName: 'Consejo de Administración',
    documentId: 'DOC-ETH-2026',
    auditId: 'AUD-POL-001',
    scope: 'Toda la organización y terceros vinculados.',
    keyControls: ['Firma anual de adhesión', 'Línea de denuncia anónima', 'Capacitación semestral'],
    reviewFrequencyDays: 365,
  },
  {
    id: 'POL-002',
    code: 'POL-FIN-002',
    name: 'Política de Crédito, Cobranza y Plazos de Pago a Clientes',
    description: 'Condiciones de otorgamiento de crédito comercial (30, 45, 60 días), límites de exposición y bloqueo automático por mora.',
    area: 'VENTAS_Y_CREDITO',
    version: '3.1',
    status: 'ACTIVE',
    effectiveDate: '2026-01-15',
    expirationDate: '2026-12-31',
    ownerId: 'USR-006',
    ownerName: 'Mtro. Fernando Morales (Gerente de Finanzas)',
    approverId: 'USR-001',
    approverName: 'Lic. Roberto Garza (Director General)',
    documentId: 'DOC-CRED-2026',
    auditId: 'AUD-POL-002',
    scope: 'Fuerza de ventas técnica, CXC y Dirección Comercial.',
    keyControls: ['Investigación en Buró de Crédito', 'Pagaré firmado', 'Validación estricta de DSO < 45 días'],
    reviewFrequencyDays: 180,
  },
  {
    id: 'POL-003',
    code: 'POL-COM-003',
    name: 'Política de Compras, Homologación de Proveedores y Órdenes de Compra',
    description: 'Protocolo de adquisición de aislamiento térmico mayorista (Owens Corning, Saint-Gobain, Rockwool, DOW) con matriz de firmas obligatoria.',
    area: 'COMPRAS_Y_ABASTECIMIENTO',
    version: '2.0',
    status: 'ACTIVE',
    effectiveDate: '2026-02-01',
    expirationDate: '2027-01-31',
    ownerId: 'USR-009',
    ownerName: 'Ing. Rodrigo Vega (Jefe de Compras)',
    approverId: 'USR-006',
    approverName: 'Mtro. Fernando Morales (Gerente de Finanzas)',
    documentId: 'DOC-PURCH-2026',
    auditId: 'AUD-POL-003',
    scope: 'Departamento de Compras, Almacén y Finanzas.',
    keyControls: ['Mínimo 3 cotizaciones > $100k', 'Contrato marco firmado', 'Evaluación OTIF trimestral'],
    reviewFrequencyDays: 365,
  },
  {
    id: 'POL-004',
    code: 'POL-ALM-004',
    name: 'Política de Custodia de Inventarios y Ajustes de Kardex',
    description: 'Procedimiento de conteos cíclicos, custodia de material térmico de alto volumen y control de mermas/ajustes de inventario.',
    area: 'ALMACEN_E_INVENTARIOS',
    version: '1.8',
    status: 'ACTIVE',
    effectiveDate: '2026-01-10',
    expirationDate: '2026-12-31',
    ownerId: 'USR-004',
    ownerName: 'Ing. Carlos Mendoza (Gerente de Almacén)',
    approverId: 'USR-006',
    approverName: 'Mtro. Fernando Morales (Gerente de Finanzas)',
    documentId: 'DOC-ALM-2026',
    auditId: 'AUD-POL-004',
    scope: 'Almacenes Naucalpan, Monterrey y Guadalajara.',
    keyControls: ['Conteo ciego mensual', 'Doble firma en ajustes > $5,000', 'Inspección de calidad al arribo'],
    reviewFrequencyDays: 180,
  },
  {
    id: 'POL-005',
    code: 'POL-SEC-005',
    name: 'Política de Ciberseguridad, Privacidad de Datos y Control de Accesos RBAC',
    description: 'Protección de datos fiscales sensibles (RFC, CURP, cuentas bancarias, salarios) y principio de menor privilegio.',
    area: 'TECNOLOGIA_Y_SEGURIDAD',
    version: '3.0',
    status: 'ACTIVE',
    effectiveDate: '2026-01-01',
    expirationDate: '2026-12-31',
    ownerId: 'USR-001',
    ownerName: 'Ing. Sistemas & Ciberseguridad',
    approverId: 'USR-001',
    approverName: 'Comité de Auditoría y Riesgos',
    documentId: 'DOC-SEC-2026',
    auditId: 'AUD-POL-005',
    scope: 'Todos los usuarios con acceso a CONSCORE ERP IA.',
    keyControls: ['Enmascaramiento de PII', 'Logs inmutables con Master Tx ID', 'Bloqueo de sesiones inactivas'],
    reviewFrequencyDays: 180,
  },
];

// ==========================================
// 2. COMITÉS CORPORATIVOS
// ==========================================

export const INITIAL_CORPORATE_COMMITTEES: CorporateCommittee[] = [
  {
    id: 'COM-01',
    code: 'COM-AUD-01',
    name: 'Comité de Auditoría, Control Interno y Riesgos',
    description: 'Supervisión transversal del cumplimiento normativo, evaluación de matriz de riesgos ERM y dictamen de auditoría interna.',
    frequency: 'MENSUAL',
    presidentName: 'Lic. Roberto Garza (Director General)',
    secretaryName: 'Mtro. Fernando Morales (Gerente de Finanzas)',
    members: [
      { userId: 'USR-001', userName: 'Lic. Roberto Garza', role: 'Presidente' },
      { userId: 'USR-006', userName: 'Mtro. Fernando Morales', role: 'Secretario' },
      { userId: 'USR-008', userName: 'Lic. Patricia Aguilar', role: 'Vocal de Talento' },
      { userId: 'USR-004', userName: 'Ing. Carlos Mendoza', role: 'Vocal de Operaciones' },
    ],
    lastSessionDate: '2026-08-15',
    nextSessionDate: '2026-09-15',
    agreements: [
      {
        id: 'AGR-01',
        agreementNumber: 'ACU-2026-08-01',
        description: 'Revisión exhaustiva de clientes con DSO > 60 días y bloqueo preventivo de pedidos.',
        responsibleId: 'USR-006',
        responsibleName: 'Mtro. Fernando Morales',
        targetDate: '2026-09-01',
        status: 'IN_PROGRESS',
      },
      {
        id: 'AGR-02',
        agreementNumber: 'ACU-2026-08-02',
        description: 'Implementación del protocolo SoD estricto para compras y transferencias.',
        responsibleId: 'USR-001',
        responsibleName: 'Ing. Auditoría de Sistemas',
        targetDate: '2026-08-30',
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 'COM-02',
    code: 'COM-CRED-02',
    name: 'Comité de Crédito, Precios y Licitaciones Industriales',
    description: 'Autorización de condiciones especiales, descuentos > 10% y líneas de crédito superiores a $500,000 MXN para megaproyectos.',
    frequency: 'QUINCENAL',
    presidentName: 'Lic. Roberto Garza (Director General)',
    secretaryName: 'Lic. Javier Duarte (Gerente de Ventas)',
    members: [
      { userId: 'USR-001', userName: 'Lic. Roberto Garza', role: 'Presidente' },
      { userId: 'USR-002', userName: 'Lic. Javier Duarte', role: 'Secretario' },
      { userId: 'USR-006', userName: 'Mtro. Fernando Morales', role: 'Vocal Financiero' },
    ],
    lastSessionDate: '2026-08-20',
    nextSessionDate: '2026-09-05',
    agreements: [
      {
        id: 'AGR-03',
        agreementNumber: 'ACU-CRED-01',
        description: 'Aprobación de línea de crédito ampliada a $1.2M MXN para Termoacústicos de Monterrey bajo garantía prendaria.',
        responsibleId: 'USR-006',
        responsibleName: 'Mtro. Fernando Morales',
        targetDate: '2026-08-25',
        status: 'COMPLETED',
      },
    ],
  },
];

// ==========================================
// 3. MATRIZ DE FACULTADES Y LÍMITES CONFIGURABLE
// ==========================================

export const INITIAL_AUTHORITY_LIMIT_RULES: AuthorityLimitRule[] = [
  // Ventas - Descuentos
  {
    id: 'RUL-DSCTO-01',
    code: 'AUTH-DSCTO-01',
    domain: 'VENTAS_DESCUENTOS',
    name: 'Descuento Estándar Vendedor',
    description: 'Descuentos comerciales hasta 5% autorizables por el ejecutivo técnico de ventas.',
    minThreshold: 0,
    maxThreshold: 5,
    metricUnit: 'PERCENTAGE',
    requiredRole: 'VENDEDOR',
    requiresTwoSignatures: false,
    allowSelfApproval: true,
    isActive: true,
  },
  {
    id: 'RUL-DSCTO-02',
    code: 'AUTH-DSCTO-02',
    domain: 'VENTAS_DESCUENTOS',
    name: 'Descuento Medio Gerencia Ventas',
    description: 'Descuentos entre 5.01% y 10% requieren autorización de la Gerencia de Ventas.',
    minThreshold: 5.01,
    maxThreshold: 10,
    metricUnit: 'PERCENTAGE',
    requiredRole: 'GERENTE_VENTAS',
    requiresTwoSignatures: false,
    allowSelfApproval: false,
    isActive: true,
  },
  {
    id: 'RUL-DSCTO-03',
    code: 'AUTH-DSCTO-03',
    domain: 'VENTAS_DESCUENTOS',
    name: 'Descuento Mayor Dirección General',
    description: 'Descuentos superiores al 10% requieren autorización explícita de Dirección General.',
    minThreshold: 10.01,
    maxThreshold: 100,
    metricUnit: 'PERCENTAGE',
    requiredRole: 'DIRECTOR',
    fallbackApproverRole: 'ADMINISTRADOR',
    requiresTwoSignatures: true,
    secondRequiredRole: 'FINANZAS',
    allowSelfApproval: false,
    isActive: true,
  },

  // Compras - Montos en MXN
  {
    id: 'RUL-COMP-01',
    code: 'AUTH-COMP-01',
    domain: 'COMPRAS_OC',
    name: 'Orden de Compra Operativa Menor',
    description: 'Compras hasta $50,000 MXN autorizadas por Jefe/Gerente de Compras.',
    minThreshold: 0,
    maxThreshold: 50000,
    metricUnit: 'MXN',
    requiredRole: 'COMPRAS',
    requiresTwoSignatures: false,
    allowSelfApproval: false,
    isActive: true,
  },
  {
    id: 'RUL-COMP-02',
    code: 'AUTH-COMP-02',
    domain: 'COMPRAS_OC',
    name: 'Orden de Compra Media Finanzas',
    description: 'Compras de $50,001 a $250,000 MXN requieren autorización de Gerencia de Finanzas.',
    minThreshold: 50001,
    maxThreshold: 250000,
    metricUnit: 'MXN',
    requiredRole: 'FINANZAS',
    requiresTwoSignatures: false,
    allowSelfApproval: false,
    isActive: true,
  },
  {
    id: 'RUL-COMP-03',
    code: 'AUTH-COMP-03',
    domain: 'COMPRAS_OC',
    name: 'Orden de Compra Mayor Dirección',
    description: 'Compras superiores a $250,000 MXN requieren autorización de Dirección General.',
    minThreshold: 250001,
    maxThreshold: 99999999,
    metricUnit: 'MXN',
    requiredRole: 'DIRECTOR',
    fallbackApproverRole: 'ADMINISTRADOR',
    requiresTwoSignatures: true,
    secondRequiredRole: 'FINANZAS',
    allowSelfApproval: false,
    isActive: true,
  },

  // Pagos Tesorería
  {
    id: 'RUL-PAG-01',
    code: 'AUTH-PAG-01',
    domain: 'PAGOS_TESORERIA',
    name: 'Pago Operativo Regular',
    description: 'Pagos calendarizados y programados en presupuesto autorizados por Finanzas.',
    minThreshold: 0,
    maxThreshold: 150000,
    metricUnit: 'MXN',
    requiredRole: 'FINANZAS',
    requiresTwoSignatures: false,
    allowSelfApproval: false,
    isActive: true,
  },
  {
    id: 'RUL-PAG-02',
    code: 'AUTH-PAG-02',
    domain: 'PAGOS_TESORERIA',
    name: 'Pago Extraordinario o Mayor',
    description: 'Pagos fuera de presupuesto o superiores a $150,000 MXN requieren Dirección General.',
    minThreshold: 150001,
    maxThreshold: 99999999,
    metricUnit: 'MXN',
    requiredRole: 'DIRECTOR',
    requiresTwoSignatures: true,
    secondRequiredRole: 'FINANZAS',
    allowSelfApproval: false,
    isActive: true,
  },

  // Ajustes de Inventario
  {
    id: 'RUL-INV-01',
    code: 'AUTH-INV-01',
    domain: 'AJUSTES_INVENTARIO',
    name: 'Ajuste Menor por Merma Operativa',
    description: 'Ajustes de inventario menores a $10,000 MXN autorizados por Gerente de Almacén.',
    minThreshold: 0,
    maxThreshold: 10000,
    metricUnit: 'MXN',
    requiredRole: 'ALMACEN',
    requiresTwoSignatures: false,
    allowSelfApproval: false,
    isActive: true,
  },
  {
    id: 'RUL-INV-02',
    code: 'AUTH-INV-02',
    domain: 'AJUSTES_INVENTARIO',
    name: 'Ajuste Mayor por Desviación de Inventario',
    description: 'Ajustes mayores a $10,000 MXN requieren autorización conjunta de Finanzas y Dirección.',
    minThreshold: 10001,
    maxThreshold: 99999999,
    metricUnit: 'MXN',
    requiredRole: 'FINANZAS',
    fallbackApproverRole: 'DIRECTOR',
    requiresTwoSignatures: true,
    secondRequiredRole: 'DIRECTOR',
    allowSelfApproval: false,
    isActive: true,
  },
];

// ==========================================
// 4. SOLICITUDES DE APROBACIÓN EJECUTIVA INICIALES
// ==========================================

export const INITIAL_APPROVAL_REQUESTS: ExecutiveApprovalRequest[] = [
  {
    approvalId: 'APR-2026-081',
    entityType: 'DESCUENTO_VENTA',
    entityId: 'COT-2026-094',
    folio: 'COT-094',
    requesterId: 'USR-003',
    requesterName: 'Ing. Alejandro Morales',
    requesterRole: 'VENDEDOR',
    requestedAmount: 12.5, // 12.5% de descuento
    currency: 'MXN',
    reason: 'Descuento especial por volumen para licitación termoacústica nave farmacéutica Toluca.',
    decision: 'PENDING',
    timestamp: '2026-08-27T08:30:00Z',
    ip: '192.168.1.104',
    auditId: 'AUD-APR-081',
    masterTransactionId: 'TX-2026-0827-001',
    riskEvaluationScore: 12,
    isSoDCompliant: true,
  },
  {
    approvalId: 'APR-2026-082',
    entityType: 'ORDEN_COMPRA',
    entityId: 'OC-2026-042',
    folio: 'OC-042',
    requesterId: 'USR-009',
    requesterName: 'Ing. Rodrigo Vega',
    requesterRole: 'COMPRAS',
    requestedAmount: 385000,
    currency: 'MXN',
    reason: 'Compra consolidada mensual de colchoneta de fibra de vidrio a Owens Corning con flete bonificado.',
    decision: 'APPROVED',
    approverId: 'USR-001',
    approverName: 'Lic. Roberto Garza',
    approverRole: 'DIRECTOR',
    decisionReason: 'Aprobado conforme a presupuesto operativo de compras y rotación proyectada.',
    timestamp: '2026-08-26T14:15:00Z',
    decisionTimestamp: '2026-08-26T16:00:00Z',
    ip: '192.168.1.101',
    auditId: 'AUD-APR-082',
    masterTransactionId: 'TX-2026-0826-004',
    riskEvaluationScore: 8,
    isSoDCompliant: true,
  },
  {
    approvalId: 'APR-2026-083',
    entityType: 'AJUSTE_INVENTARIO',
    entityId: 'AJU-2026-015',
    folio: 'AJU-015',
    requesterId: 'USR-004',
    requesterName: 'Ing. Carlos Mendoza',
    requesterRole: 'ALMACEN',
    requestedAmount: 18400,
    currency: 'MXN',
    reason: 'Ajuste de 12 rollos de aislamiento dañados por filtración pluvial en Almacén Monterrey.',
    decision: 'PENDING',
    timestamp: '2026-08-27T09:10:00Z',
    ip: '192.168.2.15',
    auditId: 'AUD-APR-083',
    riskEvaluationScore: 15,
    isSoDCompliant: true,
  },
];

// ==========================================
// 5. REGLAS DE SEGREGACIÓN DE FUNCIONES (SoD)
// ==========================================

export const INITIAL_SOD_CONFLICT_RULES: SoDConflictRule[] = [
  {
    id: 'SOD-01',
    code: 'SOD-001',
    name: 'Crear Proveedor vs Autorizar Proveedor',
    functionA: 'CREAR_PROVEEDOR',
    functionB: 'AUTORIZAR_PROVEEDOR',
    area: 'COMPRAS_Y_ABASTECIMIENTO',
    severity: 'CRITICAL',
    description: 'El usuario que da de alta los datos fiscales de un proveedor no puede aprobar su estatus para emitir pagos.',
    mitigatingControl: 'Revisión independiente por Compliance y Finanzas con constancia de situación fiscal.',
    enforceBlock: true,
    isActive: true,
  },
  {
    id: 'SOD-02',
    code: 'SOD-002',
    name: 'Crear Factura CXP vs Autorizar Pago',
    functionA: 'CREAR_FACTURA_CXP',
    functionB: 'AUTORIZAR_PAGO',
    area: 'FINANZAS_Y_TESORERIA',
    severity: 'CRITICAL',
    description: 'El usuario que registra una factura por pagar de proveedor no puede autorizar su dispersión bancaria.',
    mitigatingControl: 'Validación de 3 vías (OC vs Entrada de Almacén vs CFDI SAT).',
    enforceBlock: true,
    isActive: true,
  },
  {
    id: 'SOD-03',
    code: 'SOD-003',
    name: 'Crear Pago vs Dispersión / Transferencia Bancaria',
    functionA: 'CREAR_PAGO',
    functionB: 'EJECUTAR_TRANSFERENCIA',
    area: 'FINANZAS_Y_TESORERIA',
    severity: 'CRITICAL',
    description: 'La captura de la orden de pago y la liberación de fondos bancarios deben ser ejecutadas por personas distintas.',
    mitigatingControl: 'Token bancario dual y revisión de CLABE interbancaria autorizada.',
    enforceBlock: true,
    isActive: true,
  },
  {
    id: 'SOD-04',
    code: 'SOD-004',
    name: 'Crear Cotización con Descuento vs Autorizar Descuento',
    functionA: 'CREAR_DESCUENTO',
    functionB: 'AUTORIZAR_DESCUENTO',
    area: 'VENTAS_Y_CREDITO',
    severity: 'HIGH',
    description: 'El vendedor no puede auto-aprobar descuentos superiores al límite de su facultad.',
    mitigatingControl: 'Validación en motor de autorizaciones y firma de Gerencia / Dirección.',
    enforceBlock: true,
    isActive: true,
  },
  {
    id: 'SOD-05',
    code: 'SOD-005',
    name: 'Crear Ajuste de Kardex vs Aprobar Ajuste de Kardex',
    functionA: 'CREAR_AJUSTE_INVENTARIO',
    functionB: 'APROBAR_AJUSTE',
    area: 'ALMACEN_E_INVENTARIOS',
    severity: 'CRITICAL',
    description: 'El almacenista o supervisor que reporta la merma no puede aplicar el ajuste contable al Kardex.',
    mitigatingControl: 'Dictamen de inventario con evidencia fotográfica y aprobación de Finanzas.',
    enforceBlock: true,
    isActive: true,
  },
  {
    id: 'SOD-06',
    code: 'SOD-006',
    name: 'Calcular Nómina / Comisiones vs Autorizar Dispersión',
    functionA: 'CREAR_NOMINA',
    functionB: 'AUTORIZAR_NOMINA',
    area: 'RECURSOS_HUMANOS_Y_NOMINA',
    severity: 'CRITICAL',
    description: 'El analista de nómina no puede autorizar la póliza contable ni el layout bancario.',
    mitigatingControl: 'Revisión cruzada con contratos y aprobación de Dirección General.',
    enforceBlock: true,
    isActive: true,
  },
  {
    id: 'SOD-07',
    code: 'SOD-007',
    name: 'Crear Pedido vs Liberar Crédito Bloqueado',
    functionA: 'CREAR_PEDIDO',
    functionB: 'AUTORIZAR_EXCEPCION_CREDITO',
    area: 'VENTAS_Y_CREDITO',
    severity: 'HIGH',
    description: 'El equipo comercial no puede desbloquear clientes en mora para despachar mercancía.',
    mitigatingControl: 'Firma de Tesorería tras comprobar abono en cuenta bancaria.',
    enforceBlock: true,
    isActive: true,
  },
];

export const INITIAL_SOD_VIOLATIONS: SoDViolationRisk[] = [
  {
    id: 'SOD-VIO-01',
    ruleCode: 'SOD-001',
    ruleName: 'Crear Proveedor vs Autorizar Proveedor',
    userId: 'USR-009',
    userName: 'Ing. Rodrigo Vega (Compras)',
    attemptedAction: 'AUTORIZAR_PROVEEDOR',
    conflictingAction: 'CREAR_PROVEEDOR',
    entityType: 'PROVEEDOR',
    entityId: 'PRV-NEW-08',
    severity: 'CRITICAL',
    detectedAt: '2026-08-25T11:20:00Z',
    isBlocked: true,
    status: 'OPEN',
    auditId: 'AUD-SOD-001',
    mitigationNotes: 'Operación bloqueada por motor de control interno. Se turnó a Finanzas para validación.',
  },
];

// ==========================================
// 6. REGISTRO EMPRESARIAL DE RIESGOS (ERM)
// ==========================================

export const INITIAL_ENTERPRISE_RISKS: EnterpriseRisk[] = [
  {
    id: 'RSK-01',
    code: 'RSK-FIN-001',
    name: 'Concentración de Cartera y Cartera Vencida (DSO > 55 días)',
    description: 'Riesgo de falta de liquidez por morosidad en clientes industriales Tier 2 y contratistas generales.',
    area: 'FINANZAS_Y_TESORERIA',
    process: 'Cuentas por Cobrar y Tesorería',
    category: 'FINANCIAL',
    probability: 4,
    impact: 5,
    inherentRiskScore: 20,
    inherentRiskSeverity: 'CRITICAL',
    controls: ['Bloqueo automático de facturación por mora > 15 días', 'Póliza de seguro de crédito comercial', 'Comité de Crédito quincenal'],
    mitigation: 'Implementar cobranza preventiva escalonada y descuentos por pronto pago (2% 10 días).',
    residualProbability: 2,
    residualImpact: 3,
    residualRiskScore: 6,
    residualRiskSeverity: 'MEDIUM',
    ownerId: 'USR-006',
    ownerName: 'Mtro. Fernando Morales',
    dueDate: '2026-09-30',
    status: 'EN_MITIGACION',
    evidence: 'Reporte de Antigüedad de Saldos e Informe Semanal de Cobranza',
    auditId: 'AUD-RSK-001',
    estimatedFinancialExposureMXN: 1450000,
  },
  {
    id: 'RSK-02',
    code: 'RSK-INV-002',
    name: 'Quiebre de Stock en Aislamiento de Alta Rotación (Lana Mineral / XPS)',
    description: 'Retrasos en entregas de fabricantes principales que generen penalizaciones en obras industriales y pérdida de pedidos.',
    area: 'ALMACEN_E_INVENTARIOS',
    process: 'Planificación de Demanda y Reabastecimiento',
    category: 'INVENTORY',
    probability: 3,
    impact: 4,
    inherentRiskScore: 12,
    inherentRiskSeverity: 'HIGH',
    controls: ['Stock de seguridad dinámico de 21 días', 'Alertas tempranas de punto de reorden', 'Convenio de suministro preferente con Owens Corning'],
    mitigation: 'Monitoreo diario de inventario disponible y colocación de OCs con 30 días de anticipación.',
    residualProbability: 2,
    residualImpact: 2,
    residualRiskScore: 4,
    residualRiskSeverity: 'LOW',
    ownerId: 'USR-004',
    ownerName: 'Ing. Carlos Mendoza',
    dueDate: '2026-10-15',
    status: 'CONTROLADO',
    evidence: 'Bitácora de Reorden y Kardex Multialmacén',
    auditId: 'AUD-RSK-002',
    estimatedFinancialExposureMXN: 850000,
  },
  {
    id: 'RSK-03',
    code: 'RSK-LOG-003',
    name: 'Incidencias en Ruta y Daño de Material por Mala Estiba',
    description: 'Afectación física de rollos y preformados durante el transporte a obras industriales en el Valle de México y Bajío.',
    area: 'LOGISTICA_Y_DISTRIBUCION',
    process: 'Embarques y Distribución',
    category: 'LOGISTICS',
    probability: 3,
    impact: 3,
    inherentRiskScore: 9,
    inherentRiskSeverity: 'MEDIUM',
    controls: ['Checklist de salida vehicular obligatorio', 'Flejes y esquineros protectores', 'Evidencia fotográfica en entrega'],
    mitigation: 'Capacitación mensual a choferes y maniobristas en cubicaje de carga volumétrica.',
    residualProbability: 1,
    residualImpact: 2,
    residualRiskScore: 2,
    residualRiskSeverity: 'LOW',
    ownerId: 'USR-005',
    ownerName: 'Ing. Laura Valenzuela',
    dueDate: '2026-09-15',
    status: 'CONTROLADO',
    evidence: 'Checklist de Salida e Índices OTIF',
    auditId: 'AUD-RSK-003',
    estimatedFinancialExposureMXN: 220000,
  },
  {
    id: 'RSK-04',
    code: 'RSK-CMP-004',
    name: 'Discrepancias SAT en CFDI 4.0 con Complemento Carta Porte 3.1',
    description: 'Multas o retención de unidades por errores en folios fiscales o claves de producto en traslados federales.',
    area: 'COMPLIANCE_Y_LEGAL',
    process: 'Facturación y Cumplimiento Fiscal',
    category: 'COMPLIANCE',
    probability: 2,
    impact: 4,
    inherentRiskScore: 8,
    inherentRiskSeverity: 'MEDIUM',
    controls: ['Validación estricta de timbrado previo a salida de ruta', 'Actualización continua de catálogos SAT'],
    mitigation: 'Auditoría mensual de CFDIs emitidos vs constancias de choferes.',
    residualProbability: 1,
    residualImpact: 2,
    residualRiskScore: 2,
    residualRiskSeverity: 'LOW',
    ownerId: 'USR-006',
    ownerName: 'Mtro. Fernando Morales',
    dueDate: '2026-09-30',
    status: 'CONTROLADO',
    evidence: 'Auditoría SAT de Timbrado CFDI 4.0',
    auditId: 'AUD-RSK-004',
    estimatedFinancialExposureMXN: 350000,
  },
  {
    id: 'RSK-05',
    code: 'RSK-CYB-005',
    name: 'Fuga de Información Confidencial de Márgenes y Precios',
    description: 'Extracción de listas de precios y costos directos por personal no autorizado o accesos compartidos.',
    area: 'TECNOLOGIA_Y_SEGURIDAD',
    process: 'Seguridad de la Información',
    category: 'CYBERSECURITY',
    probability: 3,
    impact: 4,
    inherentRiskScore: 12,
    inherentRiskSeverity: 'HIGH',
    controls: ['RBAC con principio de menor privilegio', 'Registro inmutable de accesos en AuditLog', 'Enmascaramiento de datos'],
    mitigation: 'Revisión periódica de permisos de usuarios y revocación inmediata en bajas laborales.',
    residualProbability: 1,
    residualImpact: 3,
    residualRiskScore: 3,
    residualRiskSeverity: 'LOW',
    ownerId: 'USR-001',
    ownerName: 'Ing. Sistemas & Seguridad',
    dueDate: '2026-10-30',
    status: 'EN_MITIGACION',
    evidence: 'Matriz de Accesos RBAC y Logs de Auditoría',
    auditId: 'AUD-RSK-005',
    estimatedFinancialExposureMXN: 1200000,
  },
];

// ==========================================
// 7. OBLIGACIONES DE COMPLIANCE
// ==========================================

export const INITIAL_COMPLIANCE_OBLIGATIONS: ComplianceObligation[] = [
  {
    id: 'CMP-01',
    code: 'CMP-SAT-001',
    regulationSource: 'SAT - Código Fiscal de la Federación',
    name: 'Timbrado CFDI 4.0 con Carta Porte y Cancelación Justificada',
    description: 'Emisión oportuna de facturación electrónica con claves de producto SAT 30141500 (Aislamiento) y complementos de pago.',
    area: 'FINANZAS_Y_TESORERIA',
    frequency: 'PERMANENTE',
    mandatoryControls: ['Validación de RFC receptor', 'Catálogo de régimen fiscal actualizado', 'Timbrado < 24 hrs'],
    evidences: [
      {
        id: 'EVI-SAT-01',
        documentName: 'Reporte Mensual de Timbrado PAC y SAT Julio 2026',
        documentType: 'PDF_CERTIFICADO',
        date: '2026-08-05',
        responsibleName: 'Mtro. Fernando Morales',
        version: '1.0',
        evidenceUrlOrHash: 'sha256:4a8b9f1e2c3d5e6f7a8b9c0d1e2f3a4b',
        reviewerName: 'Lic. Roberto Garza',
        reviewDate: '2026-08-07',
        reviewResult: 'APROBADA',
        observations: 'Cumplimiento 100% en los 452 comprobantes del mes.',
        auditId: 'AUD-CMP-001',
      },
    ],
    status: 'COMPLIANT',
    dueDate: '2026-09-05',
    lastReviewDate: '2026-08-07',
    ownerName: 'Mtro. Fernando Morales',
    auditId: 'AUD-OBL-001',
  },
  {
    id: 'CMP-02',
    code: 'CMP-STPS-002',
    regulationSource: 'STPS - NOM-018-STPS-2015',
    name: 'Hojas de Datos de Seguridad (HDS) y Rotulación de Fibras Aislantes',
    description: 'Disponibilidad inmediata de fichas técnicas y HDS de lana mineral y fibra de vidrio para choferes y personal de almacén.',
    area: 'ALMACEN_E_INVENTARIOS',
    frequency: 'SEMESTRAL',
    mandatoryControls: ['Carpetas de HDS en vehículos y racks', 'Equipo de Protección Personal obligatorio', 'Capacitación anual'],
    evidences: [
      {
        id: 'EVI-STPS-01',
        documentName: 'Compendio de HDS Fabricantes 2026 (Owens Corning / Rockwool)',
        documentType: 'EXPEDIENTE_TECNICO',
        date: '2026-06-15',
        responsibleName: 'Ing. Carlos Mendoza',
        version: '2.1',
        evidenceUrlOrHash: 'sha256:7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e',
        reviewerName: 'Ing. Laura Valenzuela',
        reviewDate: '2026-06-20',
        reviewResult: 'APROBADA',
        observations: 'Expediente completo y accesible en los 3 almacenes.',
        auditId: 'AUD-CMP-002',
      },
    ],
    status: 'COMPLIANT',
    dueDate: '2026-12-15',
    lastReviewDate: '2026-06-20',
    ownerName: 'Ing. Carlos Mendoza',
    auditId: 'AUD-OBL-002',
  },
  {
    id: 'CMP-03',
    code: 'CMP-ISO-003',
    regulationSource: 'ISO 9001:2015 - Gestión de Calidad',
    name: 'Auditoría Interna Anual y Control de No Conformidades / Garantías',
    description: 'Evaluación de procesos de atención a clientes, garantías técnicas de aislamiento y control de devoluciones.',
    area: 'CALIDAD_Y_SERVICIO',
    frequency: 'ANUAL',
    mandatoryControls: ['Registro de tickets de garantía < 24h', 'Análisis causa raíz en quejas', 'Revisión por la Dirección'],
    evidences: [], // Sin evidencia actual -> Regla estricta: PENDING_REVIEW / NO ASUMIR
    status: 'PENDING_REVIEW',
    dueDate: '2026-10-30',
    ownerName: 'Lic. Claudia Serrano (Servicio al Cliente)',
    correctivePlan: 'Completar la recopilación de minutas de auditoría de calidad antes del 15 de Octubre.',
    auditId: 'AUD-OBL-003',
  },
  {
    id: 'CMP-04',
    code: 'CMP-LFPDP-004',
    name: 'Aviso de Privacidad y Cumplimiento LFPDPPP',
    regulationSource: 'INAI - Ley Federal de Protección de Datos Personales',
    description: 'Salvaguarda de información personal de clientes, empleados y proveedores con consentimiento expreso.',
    area: 'TECNOLOGIA_Y_SEGURIDAD',
    frequency: 'ANUAL',
    mandatoryControls: ['Aviso de privacidad integral en cotizaciones y contratos', 'Derechos ARCO habilitados'],
    evidences: [
      {
        id: 'EVI-INAI-01',
        documentName: 'Aviso de Privacidad Vigente 2026 y Bitácora de Consentimientos',
        documentType: 'DOCUMENTO_LEGAL',
        date: '2026-01-20',
        responsibleName: 'Lic. Roberto Garza',
        version: '3.0',
        evidenceUrlOrHash: 'sha256:1f2e3d4c5b6a7f8e9d0c1b2a3f4e5d6c',
        reviewerName: 'Mtro. Fernando Morales',
        reviewDate: '2026-01-25',
        reviewResult: 'APROBADA',
        observations: 'Publicado en portal y anexado a propuestas comerciales.',
        auditId: 'AUD-CMP-004',
      },
    ],
    status: 'COMPLIANT',
    dueDate: '2027-01-20',
    lastReviewDate: '2026-01-25',
    ownerName: 'Lic. Roberto Garza',
    auditId: 'AUD-OBL-004',
  },
];

export const INITIAL_ACTION_PLANS: CorrectiveActionPlan[] = [
  {
    id: 'CAPA-2026-001',
    obligationId: 'CMP-03',
    title: 'Auditoría Interna de Calidad ISO 9001:2015',
    description: 'Recopilar y validar minutas de auditoría interna de calidad y control de garantías técnicas para certificar cumplimiento anual.',
    responsible: 'Lic. Claudia Serrano (Servicio al Cliente)',
    targetDate: '2026-10-15',
    status: 'IN_PROGRESS',
    progressPct: 65,
  },
  {
    id: 'CAPA-2026-002',
    obligationId: 'CMP-01',
    title: 'Actualización Claves SAT Complemento Carta Porte 3.1',
    description: 'Capacitación al equipo de logística y facturación en validación de claves de transporte para unidades pesadas.',
    responsible: 'Mtro. Fernando Morales (Finanzas)',
    targetDate: '2026-09-20',
    status: 'COMPLETED',
    progressPct: 100,
  },
];

// ==========================================
// 8. CONTROL DOCUMENTAL CORPORATIVO
// ==========================================

export const INITIAL_CORPORATE_DOCUMENTS: CorporateDocument[] = [
  {
    id: 'DOC-001',
    code: 'DOC-CONT-2026-01',
    title: 'Contrato Marco de Distribución Exclusiva Owens Corning México',
    category: 'CONTRATOS_COMERCIALES',
    entityType: 'SUPPLIER',
    entityId: 'PRV-001',
    entityLabel: 'Owens Corning México S. de R.L. de C.V.',
    version: '4.0',
    status: 'VALID',
    validFrom: '2026-01-01',
    validTo: '2027-12-31',
    uploadedBy: 'USR-009',
    uploadedByName: 'Lic. Claudia Serrano (Compras)',
    approvedBy: 'USR-001',
    sha256Hash: '9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d',
    fileSizeKb: 2450,
    fileExtension: 'PDF',
    mimeType: 'application/pdf',
    auditId: 'AUD-DOC-001',
    storagePath: '/vault/contracts/owens_corning_2026.pdf',
    isConfidential: true,
    tags: ['distribucion', 'owens-corning', 'contrato-marco', 'proveedor'],
    notes: 'Incluye descuentos preferenciales por volumen > 50 toneladas mensuales.',
    contentPreview: 'CONTRATO DE DISTRIBUCIÓN MERCANTIL celebrado entre Owens Corning México y Consorcio Core S.A. de C.V. Clausulado general, cuotas mínimas y vigencia 2026-2027.',
  },
  {
    id: 'DOC-002',
    code: 'DOC-POL-2026-02',
    title: 'Póliza de Seguro de Transporte de Carga y Daño a Terceros (Qualitas)',
    category: 'POLIZAS_SEGUROS',
    entityType: 'VEHICLE',
    entityId: 'VEH-001',
    entityLabel: 'Camión Kenworth T370 2024 (Placas 45-AF-8K)',
    version: '2.0',
    status: 'VALID',
    validFrom: '2026-03-01',
    validTo: '2027-03-01',
    uploadedBy: 'USR-005',
    uploadedByName: 'Ing. Fernando Garza (Logística)',
    approvedBy: 'USR-006',
    sha256Hash: '8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e',
    fileSizeKb: 1120,
    fileExtension: 'PDF',
    mimeType: 'application/pdf',
    auditId: 'AUD-DOC-002',
    storagePath: '/vault/fleet/insurance_kenworth_2026.pdf',
    isConfidential: false,
    tags: ['seguro', 'transporte', 'poliza', 'qualitas', 'flotilla'],
    contentPreview: 'PÓLIZA DE SEGURO AUTOMOTRIZ DE TRANSPORTE PESADO No. POL-QU-99281. Cobertura amplia, carga frágil termoacústica y asistencia en carretera.',
  },
  {
    id: 'DOC-003',
    code: 'DOC-CRED-2026-03',
    title: 'Pagaré y Carta de Crédito Aislantes Industriales del Norte S.A.',
    category: 'EXPEDIENTES_CREDITO',
    entityType: 'CLIENT',
    entityId: 'CLI-001',
    entityLabel: 'Aislantes Industriales del Norte S.A. de C.V.',
    version: '1.0',
    status: 'VALID',
    validFrom: '2026-02-10',
    validTo: '2027-02-10',
    uploadedBy: 'USR-006',
    uploadedByName: 'Mtro. Fernando Morales (Finanzas)',
    approvedBy: 'USR-001',
    sha256Hash: '7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b',
    fileSizeKb: 890,
    fileExtension: 'PDF',
    mimeType: 'application/pdf',
    auditId: 'AUD-DOC-003',
    storagePath: '/vault/credits/pagare_aislantes_norte.pdf',
    isConfidential: true,
    tags: ['credito', 'pagare', 'cartera', 'financiero'],
    contentPreview: 'PAGARÉ MERCANTIL INCONDICIONAL por valor de $500,000 MXN en garantía de línea de crédito comercial a 30 días, suscrito por representante legal apoderado.',
  },
  {
    id: 'DOC-004',
    code: 'DOC-SAT-2026-04',
    title: 'Opinión de Cumplimiento de Obligaciones Fiscales SAT (Art. 32-D)',
    category: 'OPINIONES_SAT',
    entityType: 'COMPLIANCE',
    entityId: 'CMP-SAT-001',
    entityLabel: 'Consorcio Core S.A. de C.V. (RFC: CCO210415AA1)',
    version: '1.0',
    status: 'VALID',
    validFrom: '2026-08-01',
    validTo: '2026-09-30',
    uploadedBy: 'USR-001',
    uploadedByName: 'Administrador del Sistema',
    approvedBy: 'USR-001',
    sha256Hash: '4a8b9f1e2c3d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f',
    fileSizeKb: 450,
    fileExtension: 'PDF',
    mimeType: 'application/pdf',
    auditId: 'AUD-DOC-004',
    storagePath: '/vault/tax/opinion_sat_32d_agosto2026.pdf',
    isConfidential: false,
    tags: ['sat', '32-d', 'fiscal', 'cumplimiento', 'positiva'],
    notes: 'Opinión positiva generada desde portal SAT para licitaciones y operaciones con proveedores clave.',
    contentPreview: 'SERVICIO DE ADMINISTRACIÓN TRIBUTARIA - OPINIÓN DEL CUMPLIMIENTO DE OBLIGACIONES FISCALES. En los controles electrónicos institucionales del SAT, se observa que al momento de la emisión el contribuyente se encuentra al corriente.',
  },
];

// ==========================================
// 9. ALERTAS EMPRESARIALES INICIALES
// ==========================================

export const INITIAL_ENTERPRISE_ALERTS: EnterpriseAlert[] = [
  {
    alertId: 'ALT-2026-001',
    type: 'CXC_VENCIDA_CRITICA',
    severity: 'HIGH',
    module: 'FINANZAS',
    domain: 'FINANZAS',
    entityId: 'CLI-003',
    entityName: 'Climas y Ductos de Occidente S.A.',
    description: 'Factura F-2026-088 por $284,500 MXN con 38 días de mora. Límite de tolerancia excedido.',
    detectedAt: '2026-08-27T07:45:00Z',
    ownerId: 'USR-006',
    ownerName: 'Mtro. Fernando Morales',
    status: 'OPEN',
    recommendedAction: 'Aplicar bloqueo automático de nuevos pedidos y enviar requerimiento de pago por Dirección.',
    auditId: 'AUD-ALT-001',
    masterTransactionId: 'TX-2026-0715-002',
    financialImpactEstimatedMXN: 284500,
  },
  {
    alertId: 'ALT-2026-002',
    type: 'STOCK_CRITICO_AISLANTE',
    severity: 'MEDIUM',
    module: 'INVENTARIO',
    domain: 'INVENTARIO',
    entityId: 'PROD-002',
    entityName: 'Placa Poliestireno Extruido XPS Foamular 2"',
    description: 'Inventario disponible en Almacén Naucalpan (45 pzas) por debajo del punto de reorden (100 pzas).',
    detectedAt: '2026-08-27T08:00:00Z',
    ownerId: 'USR-004',
    ownerName: 'Ing. Carlos Mendoza',
    status: 'IN_PROGRESS',
    recommendedAction: 'Generar orden de reabastecimiento prioritaria a fabricante por 200 piezas.',
    auditId: 'AUD-ALT-002',
    financialImpactEstimatedMXN: 142000,
  },
  {
    alertId: 'ALT-2026-003',
    type: 'DESCUENTO_FUERA_DE_PATRON',
    severity: 'HIGH',
    module: 'COTIZACIONES',
    domain: 'VENTAS',
    entityId: 'COT-2026-094',
    entityName: 'Cotización Termoacústica Toluca',
    description: 'Descuento solicitado del 12.5% supera el límite de facultad del vendedor (5%) y gerencia (10%).',
    detectedAt: '2026-08-27T08:30:00Z',
    ownerId: 'USR-002',
    ownerName: 'Lic. Javier Duarte',
    status: 'OPEN',
    recommendedAction: 'Revisión por Dirección General antes de emisión formal.',
    auditId: 'AUD-ALT-003',
    masterTransactionId: 'TX-2026-0827-001',
    financialImpactEstimatedMXN: 68000,
  },
];

// ==========================================
// 10. ANOMALÍAS DETECTADAS INICIALES
// ==========================================

export const INITIAL_ANOMALIES_DETECTED: AnomalyDetectionResult[] = [
  {
    anomalyId: 'ANOM-2026-01',
    domain: 'VENTAS',
    metricName: 'Margen Bruto de Operación',
    historicalBaseline: 'Margen habitual promedio: 24.5% – 28.0%',
    currentObservedValue: 'Margen actual observado: 11.2%',
    deviationPercentage: -57.1,
    severity: 'HIGH',
    detectedAt: '2026-08-27T08:45:00Z',
    entityId: 'COT-2026-094',
    entityName: 'Propuesta Aislamiento Industrial Toluca',
    diagnosticNote: 'Comportamiento atípico detectado en estructura de costos y precios. Requiere revisión humana.',
    recommendedAction: 'Verificar si el flete o costo de materia prima está subvaluado antes de autorizar.',
    status: 'ACTIVO',
    auditId: 'AUD-ANOM-001',
    masterTransactionId: 'TX-2026-0827-001',
  },
  {
    anomalyId: 'ANOM-2026-02',
    domain: 'FINANZAS',
    metricName: 'Plazo de Pago de Cliente (DSO Individual)',
    historicalBaseline: 'Histórico habitual de pago del cliente: 22 a 28 días',
    currentObservedValue: 'Plazo actual observado: 68 días',
    deviationPercentage: +172.0,
    severity: 'HIGH',
    detectedAt: '2026-08-26T17:00:00Z',
    entityId: 'CLI-003',
    entityName: 'Climas y Ductos de Occidente S.A.',
    diagnosticNote: 'Comportamiento atípico detectado en ciclo de cobranza del cliente. Requiere revisión humana.',
    recommendedAction: 'Contactar a Dirección de Compras del cliente para acordar calendario de liquidación.',
    status: 'EN_REVISION',
    auditId: 'AUD-ANOM-002',
    masterTransactionId: 'TX-2026-0715-002',
  },
  {
    anomalyId: 'ANOM-2026-03',
    domain: 'INVENTARIO',
    metricName: 'Volumen de Entrada Inesperada en Kardex',
    historicalBaseline: 'Entrada mensual habitual: 1,500 – 2,200 rollos',
    currentObservedValue: 'Entrada reportada en un solo evento: 8,000 rollos',
    deviationPercentage: +300.0,
    severity: 'MEDIUM',
    detectedAt: '2026-08-25T14:30:00Z',
    entityId: 'ALM-001',
    entityName: 'Almacén Central Naucalpan',
    diagnosticNote: 'Comportamiento atípico detectado en recepción de mercancía mayor a la capacidad estimada. Requiere revisión humana.',
    recommendedAction: 'Verificar si se trata de un lote de consolidación nacional con destino a sucursales.',
    status: 'JUSTIFICADO',
    auditId: 'AUD-ANOM-003',
  },
];

// ==========================================
// 11. ACCIONES EJECUTIVAS DE GOBIERNO
// ==========================================

export const INITIAL_GOVERNANCE_ACTIONS: GovernanceExecutiveAction[] = [
  {
    actionId: 'ACT-GOV-001',
    horizon: 'HOY',
    title: 'Dictamen de Descuento 12.5% en Cotización COT-094',
    description: 'Evaluar margen de contribución de la propuesta para licitación Toluca y autorizar o ajustar a 8.5%.',
    priority: 'CRITICAL',
    ownerId: 'USR-001',
    ownerName: 'Lic. Roberto Garza (Director General)',
    dueDate: '2026-08-27',
    financialImpactMXN: 68000,
    riskImpact: 'Evita erosión de margen operativo en pedido de $1.2M MXN.',
    source: 'AI_ADVISOR',
    status: 'OPEN',
    requiresHumanValidation: true,
    masterTransactionId: 'TX-2026-0827-001',
    auditId: 'AUD-ACT-001',
  },
  {
    actionId: 'ACT-GOV-002',
    horizon: 'HOY',
    title: 'Resolución de Bloqueo SoD en Alta de Proveedor PRV-NEW-08',
    description: 'Turnar expediente fiscal a Finanzas para separación de funciones e investigación de compliance.',
    priority: 'HIGH',
    ownerId: 'USR-006',
    ownerName: 'Mtro. Fernando Morales (Finanzas)',
    dueDate: '2026-08-27',
    financialImpactMXN: 0,
    riskImpact: 'Garantiza estricta segregación de funciones (SoD) en compras.',
    source: 'SoD',
    status: 'OPEN',
    requiresHumanValidation: true,
    auditId: 'AUD-ACT-002',
  },
  {
    actionId: 'ACT-GOV-003',
    horizon: 'ESTA_SEMANA',
    title: 'Cobranza Ejecutiva y Bloqueo Preventivo Climas y Ductos',
    description: 'Formalizar convenio de pago para saldo vencido de $284,500 MXN o ejecutar pagaré mercantil.',
    priority: 'HIGH',
    ownerId: 'USR-006',
    ownerName: 'Mtro. Fernando Morales (Finanzas)',
    dueDate: '2026-08-29',
    financialImpactMXN: 284500,
    riskImpact: 'Mitigación directa del riesgo financiero crítico RSK-FIN-001.',
    source: 'RIESGO_ERM',
    status: 'IN_PROGRESS',
    requiresHumanValidation: true,
    masterTransactionId: 'TX-2026-0715-002',
    auditId: 'AUD-ACT-003',
  },
  {
    actionId: 'ACT-GOV-004',
    horizon: 'ESTE_MES',
    title: 'Auditoría Anual ISO 9001 y Recopilación de Evidencias de Calidad',
    description: 'Cargar evidencias de auditoría interna en el módulo de Compliance para certificar obligación CMP-ISO-003.',
    priority: 'MEDIUM',
    ownerId: 'USR-008',
    ownerName: 'Lic. Claudia Serrano (Servicio y Calidad)',
    dueDate: '2026-09-15',
    financialImpactMXN: 150000,
    riskImpact: 'Asegura retención de certificación y homologación en clientes corporativos.',
    source: 'COMPLIANCE',
    status: 'OPEN',
    requiresHumanValidation: true,
    auditId: 'AUD-ACT-004',
  },
];

// ==========================================
// 12. LÍNEA TEMPORAL MAESTRA TRANSVERSAL (E2E)
// ==========================================

export const INITIAL_MASTER_AUDIT_TIMELINES: MasterAuditTraceTimeline[] = [
  {
    masterTransactionId: 'TX-2026-0827-001',
    clientName: 'Termoacústicos y Montajes Industriales del Bajío S.A.',
    rfc: 'TMI180422K98',
    totalAmount: 1245000,
    status: 'IN_PROGRESS',
    lifecycleSteps: [
      { stepCode: 'LEAD', stepLabel: 'Lead Captado', module: 'MARKETING', isCompleted: true, timestamp: '2026-08-10T10:00:00Z', user: 'Campañas Digitales Google Ads', amount: 0, folio: 'LEAD-2026-114' },
      { stepCode: 'OPPORTUNITY', stepLabel: 'Oportunidad Calificada', module: 'VENTAS', isCompleted: true, timestamp: '2026-08-12T11:30:00Z', user: 'Ing. Alejandro Morales', amount: 1245000, folio: 'OPP-2026-088' },
      { stepCode: 'QUOTATION', stepLabel: 'Cotización Comercial', module: 'COTIZACIONES', isCompleted: true, timestamp: '2026-08-15T15:00:00Z', user: 'Ing. Alejandro Morales', amount: 1245000, folio: 'COT-2026-094' },
      { stepCode: 'ORDER', stepLabel: 'Pedido Confirmado', module: 'PEDIDOS', isCompleted: true, timestamp: '2026-08-20T09:00:00Z', user: 'Ing. Alejandro Morales', amount: 1245000, folio: 'PED-2026-076' },
      { stepCode: 'RESERVATION', stepLabel: 'Reserva de Inventario', module: 'INVENTARIO', isCompleted: true, timestamp: '2026-08-20T09:05:00Z', user: 'Sistema Automático Kardex', amount: 820000, folio: 'RES-076' },
      { stepCode: 'PICKING', stepLabel: 'Surtido y Embalaje', module: 'ALMACENES', isCompleted: true, timestamp: '2026-08-22T14:00:00Z', user: 'Ing. Carlos Mendoza', amount: 820000, folio: 'SUR-076' },
      { stepCode: 'DELIVERY', stepLabel: 'Embarque y Entrega en Obra', module: 'LOGISTICA', isCompleted: true, timestamp: '2026-08-24T16:30:00Z', user: 'Ing. Laura Valenzuela', amount: 1245000, folio: 'RUT-042' },
      { stepCode: 'INVOICE', stepLabel: 'Timbrado CFDI 4.0', module: 'FINANZAS', isCompleted: true, timestamp: '2026-08-25T10:00:00Z', user: 'Mtro. Fernando Morales', amount: 1245000, folio: 'FAC-2026-192' },
      { stepCode: 'CXC', stepLabel: 'Registro en Cartera CXC', module: 'FINANZAS', isCompleted: true, timestamp: '2026-08-25T10:05:00Z', user: 'Sistema Finanzas', amount: 1245000, folio: 'CXC-192' },
      { stepCode: 'PAYMENT', stepLabel: 'Cobro / Complemento de Pago', module: 'FINANZAS', isCompleted: false, details: 'Pendiente de cobro (Crédito a 30 días, vence 2026-09-24)' },
      { stepCode: 'COMMISSION', stepLabel: 'Cálculo de Comisión', module: 'RH', isCompleted: true, timestamp: '2026-08-25T10:10:00Z', user: 'Motor Nómina', amount: 31125, folio: 'COM-2026-094' },
      { stepCode: 'PAYROLL', stepLabel: 'Dispersión de Comisión', module: 'RH', isCompleted: false, details: 'Programada en nómina quincenal próxima' },
      { stepCode: 'PROFITABILITY', stepLabel: 'Análisis de Rentabilidad', module: 'REPORTES', isCompleted: true, timestamp: '2026-08-25T11:00:00Z', user: 'BI Motor', amount: 393875, details: 'Margen Bruto 31.6%' },
      { stepCode: 'EBITDA', stepLabel: 'Contribución a EBITDA', module: 'REPORTES', isCompleted: true, timestamp: '2026-08-25T11:00:00Z', user: 'BI Motor', amount: 362750 },
      { stepCode: 'RISK', stepLabel: 'Monitoreo de Riesgo ERM', module: 'AUDITORIA', isCompleted: true, timestamp: '2026-08-27T08:00:00Z', user: 'Risk Engine', details: 'Riesgo residual: LOW' },
      { stepCode: 'COMPLIANCE', stepLabel: 'Validación CFDI Carta Porte', module: 'AUDITORIA', isCompleted: true, timestamp: '2026-08-25T10:00:00Z', user: 'Compliance Manager', details: 'SAT 4.0 Validado' },
      { stepCode: 'AUDIT', stepLabel: 'AuditLog & Trazabilidad Inmutable', module: 'AUDITORIA', isCompleted: true, timestamp: '2026-08-27T08:30:00Z', user: 'Executive Audit Core', details: '17 Eventos Enlazados' },
    ],
    events: [
      {
        eventId: 'EVT-001',
        timestamp: '2026-08-10T10:00:00Z',
        userId: 'SYS-MKT',
        userName: 'Motor de Marketing Digital',
        userRole: 'MARKETING',
        module: 'MARKETING',
        entityType: 'LEAD',
        entityId: 'LEAD-114',
        folio: 'LEAD-114',
        action: 'CREAR_LEAD',
        masterTransactionId: 'TX-2026-0827-001',
        ip: '10.0.0.12',
        amount: 0,
      },
      {
        eventId: 'EVT-002',
        timestamp: '2026-08-15T15:00:00Z',
        userId: 'USR-003',
        userName: 'Ing. Alejandro Morales',
        userRole: 'VENDEDOR',
        module: 'COTIZACIONES',
        entityType: 'COTIZACION',
        entityId: 'COT-094',
        folio: 'COT-094',
        action: 'CREAR_COTIZACION',
        masterTransactionId: 'TX-2026-0827-001',
        ip: '192.168.1.104',
        amount: 1245000,
      },
      {
        eventId: 'EVT-003',
        timestamp: '2026-08-20T09:00:00Z',
        userId: 'USR-003',
        userName: 'Ing. Alejandro Morales',
        userRole: 'VENDEDOR',
        module: 'PEDIDOS',
        entityType: 'PEDIDO',
        entityId: 'PED-076',
        folio: 'PED-076',
        action: 'CONVERTIR_A_PEDIDO',
        masterTransactionId: 'TX-2026-0827-001',
        ip: '192.168.1.104',
        amount: 1245000,
      },
      {
        eventId: 'EVT-004',
        timestamp: '2026-08-25T10:00:00Z',
        userId: 'USR-006',
        userName: 'Mtro. Fernando Morales',
        userRole: 'FINANZAS',
        module: 'FINANZAS',
        entityType: 'FACTURA',
        entityId: 'FAC-192',
        folio: 'FAC-192',
        action: 'TIMBRAR_CFDI_4.0',
        masterTransactionId: 'TX-2026-0827-001',
        ip: '192.168.1.106',
        amount: 1245000,
      },
    ],
  },
];

export const initialGovernanceData = {
  policies: INITIAL_CORPORATE_POLICIES,
  committees: INITIAL_CORPORATE_COMMITTEES,
  authorityRules: INITIAL_AUTHORITY_LIMIT_RULES,
  approvalRequests: INITIAL_APPROVAL_REQUESTS,
  sodRules: INITIAL_SOD_CONFLICT_RULES,
  sodViolations: INITIAL_SOD_VIOLATIONS,
  risks: INITIAL_ENTERPRISE_RISKS,
  obligations: INITIAL_COMPLIANCE_OBLIGATIONS,
  evidenceList: INITIAL_COMPLIANCE_OBLIGATIONS.flatMap((o) => o.evidences || []),
  actionPlans: INITIAL_ACTION_PLANS,
  documents: INITIAL_CORPORATE_DOCUMENTS,
  alerts: INITIAL_ENTERPRISE_ALERTS,
  anomalies: INITIAL_ANOMALIES_DETECTED,
  executiveActions: INITIAL_GOVERNANCE_ACTIONS,
  sampleTraces: INITIAL_MASTER_AUDIT_TIMELINES.map((t) => ({
    masterTransactionId: t.masterTransactionId,
    leadId: 'LEAD-2026-089',
    quoteId: 'COT-094',
    orderId: 'PED-076',
    wmsDispatchId: 'DESP-044',
    invoiceId: 'FAC-192',
    arPaymentId: 'PAG-081',
    treasuryDepositId: 'DEP-055',
    commissionId: 'COM-038',
    totalAmount: 1245000,
    ebitdaContribution: 298800,
    status: 'COMPLETE' as const,
    integrityHash: 'a7b9c1d3e5f889201a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f',
    tracePoints: t.events,
  })),
};
