/**
 * @license
 * CONSCORE ERP IA - Phase 16 Initial Data
 * Predictive Operations, Business Continuity & AI Forecasting
 */

import {
  SalesForecastPeriod,
  InventoryForecastItem,
  CollectionForecastItem,
  CashFlowPeriod,
  EarlyWarningAlert,
  BusinessContinuityComponent,
  DisasterRecoveryScenario,
  MasterTransactionRecoveryChain,
  OperationsBottleneck,
  BusinessHealthScoreBreakdown,
  CooAdvisorAdvice,
  PredictionRecord,
} from '../types/predictiveOperationsTypes';

export const INITIAL_SALES_FORECASTS: SalesForecastPeriod[] = [
  {
    period: '7D',
    periodLabel: 'Próximos 7 Días',
    meta: 420000,
    real: 395000,
    forecast: 432000,
    variacion: 12000,
    cumplimientoProyectado: 102.8,
    nivelConfianza: 94.5,
    dataClassification: 'PROJECTED',
    factors: [
      { name: 'Cotizaciones en Cierre Caliente', weight: 40, impact: 'POSITIVE', description: '5 cotizaciones con decisión final esperada esta semana.' },
      { name: 'Histórico de Estacionalidad Semanal', weight: 25, impact: 'POSITIVE', description: 'Patrón de compra recurrente de jueves a sábado.' },
      { name: 'Disponibilidad de Stock en WMS', weight: 20, impact: 'POSITIVE', description: '100% de SKUs requeridos disponibles en Almacén Central.' },
      { name: 'Riesgo de Aprobación Crediticia', weight: 15, impact: 'NEUTRAL', description: '1 cliente clave al 88% de su límite de crédito asignado.' },
    ],
    historicalTrend: [
      { label: 'Día 1', real: 58000, projected: 55000 },
      { label: 'Día 2', real: 62000, projected: 60000 },
      { label: 'Día 3', real: 71000, projected: 68000 },
      { label: 'Día 4', real: 54000, projected: 58000 },
      { label: 'Día 5', real: 85000, projected: 82000 },
      { label: 'Día 6', real: 65000, projected: 62000 },
      { label: 'Día 7', real: 0, projected: 47000 },
    ],
  },
  {
    period: '30D',
    periodLabel: 'Próximos 30 Días (Mensual)',
    meta: 1850000,
    real: 1420000,
    forecast: 1910000,
    variacion: 60000,
    cumplimientoProyectado: 103.2,
    nivelConfianza: 89.2,
    dataClassification: 'PROJECTED',
    factors: [
      { name: 'Pipeline Comercial Ponderado', weight: 35, impact: 'POSITIVE', description: 'Pipeline activo de $3.4M MXN con probabilidad ajustada de 56%.' },
      { name: 'Velocidad de Conversión CRM', weight: 25, impact: 'POSITIVE', description: 'Ciclo promedio de venta reducido de 18 a 14 días.' },
      { name: 'Riesgo de Abastecimiento Crítico', weight: 20, impact: 'NEGATIVE', description: 'Posible retraso en 2 órdenes de importación de transformadores.' },
      { name: 'Retención de Clientes Top 20', weight: 20, impact: 'POSITIVE', description: 'Tasa de recompra de clientes clave en 92%.' },
    ],
    historicalTrend: [
      { label: 'Sem 1', real: 410000, projected: 400000 },
      { label: 'Sem 2', real: 460000, projected: 450000 },
      { label: 'Sem 3', real: 550000, projected: 520000 },
      { label: 'Sem 4', real: 0, projected: 540000 },
    ],
  },
  {
    period: '60D',
    periodLabel: 'Horizonte 60 Días',
    meta: 3700000,
    real: 1420000,
    forecast: 3820000,
    variacion: 120000,
    cumplimientoProyectado: 103.2,
    nivelConfianza: 83.7,
    dataClassification: 'PROJECTED',
    factors: [
      { name: 'Licitaciones Públicas en Evaluación', weight: 30, impact: 'POSITIVE', description: '2 proyectos de infraestructura con dictamen técnico favorable.' },
      { name: 'Tendencia Macroeconómica Sector Construcción', weight: 25, impact: 'NEUTRAL', description: 'Crecimiento estimado del 3.2% en demanda industrial regional.' },
      { name: 'Capacidad Logística de Distribución', weight: 25, impact: 'POSITIVE', description: 'Flota operativa al 82% con margen para incremento de volumen.' },
      { name: 'Variación de Precios de Cobre/Aluminio', weight: 20, impact: 'NEGATIVE', description: 'Volatilidad en commodities con impacto potencial en márgenes.' },
    ],
    historicalTrend: [
      { label: 'Mes 1', real: 1850000, projected: 1910000 },
      { label: 'Mes 2', real: 0, projected: 1910000 },
    ],
  },
  {
    period: '90D',
    periodLabel: 'Horizonte 90 Días (Trimestral)',
    meta: 5550000,
    real: 1420000,
    forecast: 5680000,
    variacion: 130000,
    cumplimientoProyectado: 102.3,
    nivelConfianza: 78.4,
    dataClassification: 'PROJECTED',
    factors: [
      { name: 'Expansión de Cartera Zona Bajío', weight: 30, impact: 'POSITIVE', description: '14 prospectos corporativos calificados en etapa de propuesta.' },
      { name: 'Acuerdos Marco con Proveedores Tier 1', weight: 25, impact: 'POSITIVE', description: 'Condiciones de precio y entrega garantizadas para el trimestre.' },
      { name: 'Índice de Incertidumbre de Tasas de Interés', weight: 25, impact: 'NEGATIVE', description: 'Clientes cautelosos en comprometer proyectos de largo plazo.' },
      { name: 'Efectividad de Campañas de Marketing Digital', weight: 20, impact: 'POSITIVE', description: 'Costo de adquisición de lead (CAC) disminuyó 14%.' },
    ],
    historicalTrend: [
      { label: 'Mes 1', real: 1850000, projected: 1910000 },
      { label: 'Mes 2', real: 0, projected: 1910000 },
      { label: 'Mes 3', real: 0, projected: 1860000 },
    ],
  },
  {
    period: 'MONTH_END',
    periodLabel: 'Proyección Cierre Mensual',
    meta: 1850000,
    real: 1420000,
    forecast: 1895000,
    variacion: 45000,
    cumplimientoProyectado: 102.4,
    nivelConfianza: 91.8,
    dataClassification: 'PROJECTED',
    factors: [
      { name: 'Backlog de Pedidos por Facturar', weight: 50, impact: 'POSITIVE', description: '$310k MXN en pedidos confirmados listos para embarque.' },
      { name: 'Cotizaciones en Negociación Final', weight: 30, impact: 'POSITIVE', description: '$260k MXN con alta probabilidad de cierre antes del día 30.' },
      { name: 'Riesgo de Cancelaciones / Devoluciones', weight: 20, impact: 'NEUTRAL', description: 'Tasa histórica de cancelación menor al 1.2%.' },
    ],
    historicalTrend: [
      { label: 'Día 1-10', real: 540000, projected: 520000 },
      { label: 'Día 11-20', real: 560000, projected: 550000 },
      { label: 'Día 21-30', real: 320000, projected: 825000 },
    ],
  },
  {
    period: 'QUARTER_END',
    periodLabel: 'Proyección Cierre Trimestral',
    meta: 5550000,
    real: 1420000,
    forecast: 5720000,
    variacion: 170000,
    cumplimientoProyectado: 103.1,
    nivelConfianza: 81.5,
    dataClassification: 'PROJECTED',
    factors: [
      { name: 'Presupuestos Asignados de Clientes Industriales', weight: 40, impact: 'POSITIVE', description: 'Cierre de año fiscal de clientes corporativos acelera compras.' },
      { name: 'Cumplimiento de Metas por Equipo Comercial', weight: 35, impact: 'POSITIVE', description: '7 de 9 ejecutivos de venta proyectados por arriba del 100% de cuota.' },
      { name: 'Riesgo de Tiempos de Entrega Proveedor', weight: 25, impact: 'NEGATIVE', description: 'Lead time en componentes importados se extendió 6 días hábiles.' },
    ],
    historicalTrend: [
      { label: 'Mes 1 (Real)', real: 1850000, projected: 1850000 },
      { label: 'Mes 2 (Estimado)', real: 0, projected: 1910000 },
      { label: 'Mes 3 (Estimado)', real: 0, projected: 1960000 },
    ],
  },
];

export const INITIAL_INVENTORY_FORECASTS: InventoryForecastItem[] = [
  {
    productId: 'PRD-001',
    productName: 'Cable de Cobre THW-LS Calibre 10 AWG (Rollo 100m)',
    sku: 'CAB-THW-10-100M',
    category: 'Conductores Eléctricos',
    stockActual: 18,
    stockComprometido: 14,
    stockDisponible: 4,
    demandaProyectada30D: 45,
    diasEstimadosCobertura: 3.5,
    probabilidadRuptura: 92.4,
    impactoEconomico: 86400,
    recomendacion: 'Generar Orden de Compra urgente por 50 rollos al proveedor principal CONDUMEX.',
    stockSeguridad: 15,
    puntoReorden: 25,
    tendencia: 'CRECIENTE',
    status: 'RUPTURA_CRITICA',
    dataClassification: 'PROJECTED',
  },
  {
    productId: 'PRD-002',
    productName: 'Transformador Trifásico Tipo Poste 75 kVA 13.2kV / 220-127V',
    sku: 'TRA-TRI-75KVA-STD',
    category: 'Transformadores & Subestaciones',
    stockActual: 3,
    stockComprometido: 2,
    stockDisponible: 1,
    demandaProyectada30D: 4,
    diasEstimadosCobertura: 7.2,
    probabilidadRuptura: 78.6,
    impactoEconomico: 145000,
    recomendacion: 'Emitir requisición preventiva de 3 unidades. Tiempo de entrega del fabricante: 14 días.',
    stockSeguridad: 2,
    puntoReorden: 4,
    tendencia: 'CRECIENTE',
    status: 'REORDEN_INMEDIATO',
    dataClassification: 'PROJECTED',
  },
  {
    productId: 'PRD-003',
    productName: 'Interruptor Termomagnético Industrial 3x100A 240V',
    sku: 'INT-TER-3X100A',
    category: 'Protección & Control',
    stockActual: 84,
    stockComprometido: 6,
    stockDisponible: 78,
    demandaProyectada30D: 12,
    diasEstimadosCobertura: 195.0,
    probabilidadRuptura: 1.2,
    impactoEconomico: 62400,
    recomendacion: 'Sobreinventario detectado. Frenar compras adicionales y paquetizar con transformadores en ofertas comerciales.',
    stockSeguridad: 10,
    puntoReorden: 20,
    tendencia: 'DECRECIENTE',
    status: 'SOBREINVENTARIO',
    dataClassification: 'PROJECTED',
  },
  {
    productId: 'PRD-004',
    productName: 'Tubería Conduit Metálica Pared Gruesa 1 pulgada (Tramo 3m)',
    sku: 'TUB-CON-PG-1IN',
    category: 'Canalización & Tubería',
    stockActual: 140,
    stockComprometido: 25,
    stockDisponible: 115,
    demandaProyectada30D: 110,
    diasEstimadosCobertura: 31.3,
    probabilidadRuptura: 18.5,
    impactoEconomico: 22000,
    recomendacion: 'Nivel óptimo de cobertura para el mes en curso. Monitorear pedidos de obra la próxima semana.',
    stockSeguridad: 40,
    puntoReorden: 80,
    tendencia: 'ESTABLE',
    status: 'OPTIMO',
    dataClassification: 'PROJECTED',
  },
  {
    productId: 'PRD-005',
    productName: 'Luminaria LED Industrial High Bay 150W 5000K IP65',
    sku: 'LUM-LED-HB-150W',
    category: 'Iluminación Industrial',
    stockActual: 56,
    stockComprometido: 2,
    stockDisponible: 54,
    demandaProyectada30D: 5,
    diasEstimadosCobertura: 324.0,
    probabilidadRuptura: 0.8,
    impactoEconomico: 89600,
    recomendacion: 'Baja rotación acumulada en 90 días. Se recomienda transferir 30 unidades a sucursal Monterrey.',
    stockSeguridad: 8,
    puntoReorden: 15,
    tendencia: 'DECRECIENTE',
    status: 'BAJA_ROTACION',
    dataClassification: 'PROJECTED',
  },
  {
    productId: 'PRD-006',
    productName: 'Preformado de Remate Distribución 3/8" Acero Galvanizado',
    sku: 'PRE-REM-DIST-38',
    category: 'Herrajes & Línea Aérea',
    stockActual: 320,
    stockComprometido: 180,
    stockDisponible: 140,
    demandaProyectada30D: 250,
    diasEstimadosCobertura: 16.8,
    probabilidadRuptura: 44.2,
    impactoEconomico: 38500,
    recomendacion: 'Programar reorden regular de 200 piezas para la semana 3 del mes.',
    stockSeguridad: 100,
    puntoReorden: 220,
    tendencia: 'CRECIENTE',
    status: 'OPTIMO',
    dataClassification: 'PROJECTED',
  },
  {
    productId: 'PRD-007',
    productName: 'Gabinete NEMA 4X Acero Inoxidable 600x400x250mm',
    sku: 'GAB-NEMA-4X-SS',
    category: 'Enclosures & Tableros',
    stockActual: 12,
    stockComprometido: 0,
    stockDisponible: 12,
    demandaProyectada30D: 0.5,
    diasEstimadosCobertura: 720.0,
    probabilidadRuptura: 0.0,
    impactoEconomico: 114000,
    recomendacion: 'Inventario inmovilizado por 180+ días. Proponer a clientes de industria química con descuento del 12%.',
    stockSeguridad: 2,
    puntoReorden: 4,
    tendencia: 'DECRECIENTE',
    status: 'INMOVILIZADO',
    dataClassification: 'PROJECTED',
  },
];

export const INITIAL_COLLECTION_FORECASTS: CollectionForecastItem[] = [
  {
    customerId: 'CUST-001',
    customerName: 'Constructora e Inmobiliaria del Norte S.A. de C.V.',
    taxId: 'CIN880412KJ1',
    saldoPendiente: 284500,
    dso: 48,
    antiguedadPromedioDias: 42,
    limiteCredito: 350000,
    creditoUtilizadoPct: 81.3,
    probabilidadAtraso: 74.2,
    exposicionFinanciera: 284500,
    nivelRiesgo: 'HIGH',
    incumplimientosHistoricos: 3,
    comportamientoScore: 62,
    promesasPago: [
      { id: 'PROM-001', fechaPromesa: '2026-08-30', monto: 120000, cumplida: false },
      { id: 'PROM-002', fechaPromesa: '2026-09-15', monto: 164500, cumplida: false },
    ],
    recomendacion: 'Contactar a tesorería de cliente para ratificar SPEI del día 30. No autorizar nuevos pedidos a crédito mayores a $20k hasta abonar.',
    responsable: 'Lic. Mariana Garza',
    responsibleRole: 'FINANZAS',
    requiresHumanValidation: true,
    dataClassification: 'PROJECTED',
  },
  {
    customerId: 'CUST-002',
    customerName: 'Desarrollos Industriales del Bajío S.A.P.I.',
    taxId: 'DIB150920TR9',
    saldoPendiente: 412000,
    dso: 65,
    antiguedadPromedioDias: 58,
    limiteCredito: 400000,
    creditoUtilizadoPct: 103.0,
    probabilidadAtraso: 89.5,
    exposicionFinanciera: 412000,
    nivelRiesgo: 'CRITICAL',
    incumplimientosHistoricos: 5,
    comportamientoScore: 41,
    promesasPago: [
      { id: 'PROM-003', fechaPromesa: '2026-08-25', monto: 200000, cumplida: false },
    ],
    recomendacion: 'CRÍTICO: Exceso de límite de crédito y promesa vencida hace 2 días. Escalar a Gerencia de Finanzas para plan de pagos formal.',
    responsable: 'C.P. Roberto Silva',
    responsibleRole: 'FINANZAS',
    requiresHumanValidation: true,
    dataClassification: 'PROJECTED',
  },
  {
    customerId: 'CUST-003',
    customerName: 'Instalaciones Electromecánicas Peninsulares',
    taxId: 'IEP110304LM8',
    saldoPendiente: 95000,
    dso: 22,
    antiguedadPromedioDias: 18,
    limiteCredito: 250000,
    creditoUtilizadoPct: 38.0,
    probabilidadAtraso: 12.0,
    exposicionFinanciera: 95000,
    nivelRiesgo: 'LOW',
    incumplimientosHistoricos: 0,
    comportamientoScore: 95,
    promesasPago: [
      { id: 'PROM-004', fechaPromesa: '2026-09-05', monto: 95000, cumplida: false },
    ],
    recomendacion: 'Cliente con excelente historial de pago. Proponer incremento de línea de crédito a $350k para capturar nuevo proyecto de hotel.',
    responsable: 'Lic. Mariana Garza',
    responsibleRole: 'FINANZAS',
    requiresHumanValidation: true,
    dataClassification: 'PROJECTED',
  },
  {
    customerId: 'CUST-004',
    customerName: 'Grupo Minero y Metalúrgico San Cristóbal',
    taxId: 'GMM040819PL5',
    saldoPendiente: 188000,
    dso: 38,
    antiguedadPromedioDias: 31,
    limiteCredito: 300000,
    creditoUtilizadoPct: 62.7,
    probabilidadAtraso: 35.8,
    exposicionFinanciera: 188000,
    nivelRiesgo: 'MEDIUM',
    incumplimientosHistoricos: 1,
    comportamientoScore: 78,
    promesasPago: [
      { id: 'PROM-005', fechaPromesa: '2026-09-10', monto: 188000, cumplida: false },
    ],
    recomendacion: 'Seguimiento preventivo a contrarecibo en portal de proveedores el 5 de septiembre.',
    responsable: 'Lic. Mariana Garza',
    responsibleRole: 'FINANZAS',
    requiresHumanValidation: false,
    dataClassification: 'PROJECTED',
  },
];

export const INITIAL_CASH_FLOW_PERIODS: CashFlowPeriod[] = [
  {
    horizon: '7D',
    horizonLabel: '7 Días (Semanal)',
    saldoInicial: 840000,
    ingresosProyectados: {
      cobranzaCxc: 320000,
      ventasContado: 110000,
      otrosIngresos: 15000,
      totalIngresos: 445000,
    },
    egresosProyectados: {
      cxpProveedores: 280000,
      nomina: 95000,
      impuestosSat: 0,
      comprasDirectas: 45000,
      gastosOperativos: 32000,
      totalEgresos: 452000,
    },
    flujoNeto: -7000,
    saldoFinalProyectado: 833000,
    capitalTrabajo: 620000,
    nivelLiquidez: 'ROBUST',
    dataClassification: 'PROJECTED',
  },
  {
    horizon: '30D',
    horizonLabel: '30 Días (Mensual)',
    saldoInicial: 840000,
    ingresosProyectados: {
      cobranzaCxc: 1450000,
      ventasContado: 380000,
      otrosIngresos: 45000,
      totalIngresos: 1875000,
    },
    egresosProyectados: {
      cxpProveedores: 980000,
      nomina: 380000,
      impuestosSat: 185000,
      comprasDirectas: 120000,
      gastosOperativos: 95000,
      totalEgresos: 1760000,
    },
    flujoNeto: 115000,
    saldoFinalProyectado: 955000,
    capitalTrabajo: 710000,
    nivelLiquidez: 'ROBUST',
    dataClassification: 'PROJECTED',
  },
  {
    horizon: '60D',
    horizonLabel: '60 Días (Bimestral)',
    saldoInicial: 840000,
    ingresosProyectados: {
      cobranzaCxc: 2980000,
      ventasContado: 740000,
      otrosIngresos: 80000,
      totalIngresos: 3800000,
    },
    egresosProyectados: {
      cxpProveedores: 1950000,
      nomina: 760000,
      impuestosSat: 370000,
      comprasDirectas: 240000,
      gastosOperativos: 190000,
      totalEgresos: 3510000,
    },
    flujoNeto: 290000,
    saldoFinalProyectado: 1130000,
    capitalTrabajo: 840000,
    nivelLiquidez: 'ROBUST',
    dataClassification: 'PROJECTED',
  },
  {
    horizon: '90D',
    horizonLabel: '90 Días (Trimestral)',
    saldoInicial: 840000,
    ingresosProyectados: {
      cobranzaCxc: 4420000,
      ventasContado: 1120000,
      otrosIngresos: 120000,
      totalIngresos: 5660000,
    },
    egresosProyectados: {
      cxpProveedores: 2920000,
      nomina: 1140000,
      impuestosSat: 550000,
      comprasDirectas: 360000,
      gastosOperativos: 285000,
      totalEgresos: 5255000,
    },
    flujoNeto: 405000,
    saldoFinalProyectado: 1245000,
    capitalTrabajo: 920000,
    nivelLiquidez: 'ROBUST',
    dataClassification: 'PROJECTED',
  },
  {
    horizon: '180D',
    horizonLabel: '180 Días (Semestral)',
    saldoInicial: 840000,
    ingresosProyectados: {
      cobranzaCxc: 9100000,
      ventasContado: 2300000,
      otrosIngresos: 240000,
      totalIngresos: 11640000,
    },
    egresosProyectados: {
      cxpProveedores: 6100000,
      nomina: 2280000,
      impuestosSat: 1120000,
      comprasDirectas: 750000,
      gastosOperativos: 580000,
      totalEgresos: 10830000,
    },
    flujoNeto: 810000,
    saldoFinalProyectado: 1650000,
    capitalTrabajo: 1150000,
    nivelLiquidez: 'ROBUST',
    dataClassification: 'PROJECTED',
  },
  {
    horizon: '365D',
    horizonLabel: '365 Días (Anual)',
    saldoInicial: 840000,
    ingresosProyectados: {
      cobranzaCxc: 18900000,
      ventasContado: 4800000,
      otrosIngresos: 500000,
      totalIngresos: 24200000,
    },
    egresosProyectados: {
      cxpProveedores: 12800000,
      nomina: 4560000,
      impuestosSat: 2350000,
      comprasDirectas: 1550000,
      gastosOperativos: 1200000,
      totalEgresos: 22460000,
    },
    flujoNeto: 1740000,
    saldoFinalProyectado: 2580000,
    capitalTrabajo: 1780000,
    nivelLiquidez: 'ROBUST',
    dataClassification: 'PROJECTED',
  },
];

export const INITIAL_EARLY_WARNINGS: EarlyWarningAlert[] = [
  {
    ALERT_ID: 'WARN-VTA-001',
    SEVERITY: 'HIGH',
    MODULE: 'VENTAS',
    ENTITY: 'Concentración de Cartera en Cliente Top 1',
    CAUSE: 'El 34% de la facturación proyectada del mes depende de un solo cliente (Desarrollos Industriales del Bajío).',
    IMPACT: 'Vulnerabilidad ante cualquier retraso de pago o cancelación de licitación.',
    FINANCIAL_IMPACT: 620000,
    RECOMMENDATION: 'Diversificar pipeline activando prospección B2B en sectores agroindustrial y hospitalario.',
    OWNER: 'Lic. Fernando Morales (Gerente de Ventas)',
    TARGET_DATE: '2026-09-05',
    STATUS: 'OPEN',
    DATA_CLASSIFICATION: 'PROJECTED',
    CONFIDENCE: 91,
    masterTransactionId: 'MTX-2026-08819',
  },
  {
    ALERT_ID: 'WARN-FIN-002',
    SEVERITY: 'CRITICAL',
    MODULE: 'FINANZAS',
    ENTITY: 'Incremento de CXC Vencida +45 Días',
    CAUSE: '3 clientes con saldos vencidos acumulan $412k MXN sin abono en los últimos 30 días.',
    IMPACT: 'Deterioro del ratio de rotación de cartera y aumento en necesidad de apalancamiento de corto plazo.',
    FINANCIAL_IMPACT: 412000,
    RECOMMENDATION: 'Iniciar cobranza extrajudicial formal con envío de estados de cuenta certificados y llamada ejecutiva.',
    OWNER: 'C.P. Roberto Silva (Director de Finanzas)',
    TARGET_DATE: '2026-08-30',
    STATUS: 'OPEN',
    DATA_CLASSIFICATION: 'REAL',
    CONFIDENCE: 98,
    masterTransactionId: 'MTX-2026-08820',
  },
  {
    ALERT_ID: 'WARN-INV-003',
    SEVERITY: 'HIGH',
    MODULE: 'INVENTARIO',
    ENTITY: 'Ruptura Inminente de Cable THW Calibre 10',
    CAUSE: 'Solo quedan 4 rollos disponibles y existen pedidos confirmados por surtir esta semana.',
    IMPACT: 'Detención de 3 órdenes de trabajo y penalización contractual por entrega tardía.',
    FINANCIAL_IMPACT: 86400,
    RECOMMENDATION: 'Autorizar compra directa local de 15 rollos de emergencia mientras arriba la orden maestra.',
    OWNER: 'Ing. Carlos Mendoza (Jefe de Almacén)',
    TARGET_DATE: '2026-08-28',
    STATUS: 'OPEN',
    DATA_CLASSIFICATION: 'PROJECTED',
    CONFIDENCE: 95,
  },
  {
    ALERT_ID: 'WARN-OPS-004',
    SEVERITY: 'MEDIUM',
    MODULE: 'OPERACION',
    ENTITY: 'Cuello de Botella en Andén de Despacho 2',
    CAUSE: 'Acumulación de 14 pedidos listos para carga simultánea entre 16:00 y 18:00 hrs.',
    IMPACT: 'Retraso de salida de rutas metropolitanas y tiempos muertos en choferes.',
    FINANCIAL_IMPACT: 24500,
    RECOMMENDATION: 'Escalonar ventanas de carga asignando 4 pedidos al Andén 1 a partir de las 14:30 hrs.',
    OWNER: 'Ing. Rodrigo Paz (Coord. Logística)',
    TARGET_DATE: '2026-08-28',
    STATUS: 'OPEN',
    DATA_CLASSIFICATION: 'REAL',
    CONFIDENCE: 88,
  },
  {
    ALERT_ID: 'WARN-CLI-005',
    SEVERITY: 'MEDIUM',
    MODULE: 'CLIENTES',
    ENTITY: 'Deterioro en Customer Health Score - Constructora del Norte',
    CAUSE: 'Incremento de 2 tickets de reclamación por retraso en entrega de certificados de calidad en últimos 15 días.',
    IMPACT: 'Riesgo de churn comercial y reducción en asignación de proyectos futuros.',
    FINANCIAL_IMPACT: 180000,
    RECOMMENDATION: 'Agendar visita de postventa con entrega física de certificados y bonificación del 2% en flete.',
    OWNER: 'Lic. Laura Benítez (Servicio al Cliente)',
    TARGET_DATE: '2026-09-02',
    STATUS: 'OPEN',
    DATA_CLASSIFICATION: 'PROJECTED',
    CONFIDENCE: 84,
  },
  {
    ALERT_ID: 'WARN-FIN-006',
    SEVERITY: 'LOW',
    MODULE: 'FINANZAS',
    ENTITY: 'Desviación Presupuestal en Combustible de Flota',
    CAUSE: 'Gasto de diésel 8.4% superior a la partida presupuestada debido a desvíos por obras viales.',
    IMPACT: 'Sobrecosto mensual de $12,800 MXN en logística.',
    FINANCIAL_IMPACT: 12800,
    RECOMMENDATION: 'Actualizar rutas en módulo de logística con optimización de tráfico en tiempo real.',
    OWNER: 'Ing. Rodrigo Paz (Coord. Logística)',
    TARGET_DATE: '2026-09-04',
    STATUS: 'MITIGATED',
    DATA_CLASSIFICATION: 'CALCULATED',
    CONFIDENCE: 92,
  },
];

export const INITIAL_BUSINESS_CONTINUITY_COMPONENTS: BusinessContinuityComponent[] = [
  {
    componentId: 'BC-01',
    name: 'Database',
    status: 'HEALTHY',
    rpo: '0 seg (Sync)',
    rto: '< 5 seg',
    lastBackupTimestamp: '2026-08-27T15:00:00Z',
    sha256Integrity: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 99.99,
  },
  {
    componentId: 'BC-02',
    name: 'API',
    status: 'HEALTHY',
    rpo: '0 seg',
    rto: '< 3 seg',
    lastBackupTimestamp: '2026-08-27T14:45:00Z',
    sha256Integrity: '4a6f23b89012a9efd01934bc8921afde3910cbe44120349efda8921045bc901a',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 99.98,
  },
  {
    componentId: 'BC-03',
    name: 'Authentication',
    status: 'HEALTHY',
    rpo: '0 seg',
    rto: '< 2 seg',
    lastBackupTimestamp: '2026-08-27T15:00:00Z',
    sha256Integrity: '8f912bc09124adfe901248bc90124aef8912401bcda9012389410cbefda90123',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 100.0,
  },
  {
    componentId: 'BC-04',
    name: 'Authorization',
    status: 'HEALTHY',
    rpo: '0 seg',
    rto: '< 2 seg',
    lastBackupTimestamp: '2026-08-27T15:00:00Z',
    sha256Integrity: '12948bcda09124ef891023bc490129aefda901248bc901234891023cbefda901',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 100.0,
  },
  {
    componentId: 'BC-05',
    name: 'Realtime',
    status: 'HEALTHY',
    rpo: '< 1 seg',
    rto: '< 4 seg',
    lastBackupTimestamp: '2026-08-27T14:30:00Z',
    sha256Integrity: '78bc90124afde9012348bc9012348aefda9012348bc90123489012348bc90123',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 99.95,
  },
  {
    componentId: 'BC-06',
    name: 'Storage',
    status: 'HEALTHY',
    rpo: '0 seg',
    rto: '< 5 seg',
    lastBackupTimestamp: '2026-08-27T15:00:00Z',
    sha256Integrity: '901248bcda09124ef89012348bc90124aefda9012348bc90123489012348bc90',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 99.99,
  },
  {
    componentId: 'BC-07',
    name: 'Audit',
    status: 'HEALTHY',
    rpo: '0 seg (Append-Only)',
    rto: '< 2 seg',
    lastBackupTimestamp: '2026-08-27T15:10:00Z',
    sha256Integrity: 'bc90124aefda9012348bc90123489012348bc9012348aefda9012348bc901234',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 100.0,
  },
  {
    componentId: 'BC-08',
    name: 'Integrations',
    status: 'HEALTHY',
    rpo: '< 2 seg',
    rto: '< 8 seg',
    lastBackupTimestamp: '2026-08-27T14:00:00Z',
    sha256Integrity: '348bc90123489012348bc9012348aefda9012348bc9012348bc90124aefda901',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 99.92,
  },
  {
    componentId: 'BC-09',
    name: 'AI',
    status: 'HEALTHY',
    rpo: 'N/A (Stateless)',
    rto: '< 3 seg',
    lastBackupTimestamp: '2026-08-27T15:00:00Z',
    sha256Integrity: 'efda9012348bc9012348bc90124aefda9012348bc9012348bc90124aefda9012',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 99.96,
  },
  {
    componentId: 'BC-10',
    name: 'Backups',
    status: 'HEALTHY',
    rpo: '60 min',
    rto: '< 10 seg',
    lastBackupTimestamp: '2026-08-27T15:00:00Z',
    sha256Integrity: '9012348bc9012348bc90124aefda9012348bc9012348bc90124aefda9012348b',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 100.0,
  },
  {
    componentId: 'BC-11',
    name: 'Banking',
    status: 'HEALTHY',
    rpo: '0 seg (Idempotent)',
    rto: '< 12 seg',
    lastBackupTimestamp: '2026-08-27T14:30:00Z',
    sha256Integrity: 'bc9012348bc90124aefda9012348bc9012348bc90124aefda9012348bc901234',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 99.88,
  },
  {
    componentId: 'BC-12',
    name: 'SAT/PAC',
    status: 'HEALTHY',
    rpo: '0 seg (CFDI Sync)',
    rto: '< 10 seg',
    lastBackupTimestamp: '2026-08-27T14:45:00Z',
    sha256Integrity: 'aefda9012348bc9012348bc90124aefda9012348bc9012348bc90124aefda901',
    replicationStatus: 'SYNCED',
    affectedServices: [],
    lastIncidentTimestamp: null,
    recoveryTimeActual: '0s',
    uptimePct: 99.91,
  },
];

export const INITIAL_DISASTER_RECOVERY_SCENARIOS: DisasterRecoveryScenario[] = [
  {
    scenarioId: 'DR-SCEN-01',
    name: 'Escenario 1: Database Down',
    description: 'Simulación de indisponibilidad del cluster primario de base de datos con conmutación por error (Failover) a réplica caliente.',
    targetComponent: 'Database',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-001',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Detección de timeout > 1200ms en heartbeat de conexión PostgreSQL.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Aislamiento de nodo primario y enrutamiento a modo Read-Only temporal.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Activación de búfer de transacciones en memoria RAM con respaldo local cifrado.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Promoción automática de réplica secundaria a Primario en < 3.2 segundos.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Conciliación de 14 transacciones pendientes mediante Idempotency Keys.' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Generación de reporte forense con sellado criptográfico SHA-256.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-02',
    name: 'Escenario 2: API Down',
    description: 'Caída del API Gateway con rebalanceo de tráfico a nodos satélite y degradación elegante de servicios no críticos.',
    targetComponent: 'API',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-002',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Detección de error HTTP 502 Bad Gateway en ingress reverse proxy.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Drenado de conexiones huérfanas y contención de peticiones en cola.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Protección de estado de sesión con token refresh sin deslogueo de usuarios.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Auto-scaling y reinicio de pods API en tiempo récord de 1.8 segundos.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Reintento ordenado de 28 requests concurrentes con jitter exponencial.' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Registro de telemetría y latencias percentiles en bitácora inmutable.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-03',
    name: 'Escenario 3: Authentication Down',
    description: 'Falla en proveedor de autenticación con activación de tokens de contingencia offline y validación biométrica/PIN de seguridad.',
    targetComponent: 'Authentication',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-003',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Falla de handshake OAuth con servidor central de credenciales.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Bloqueo de intentos anómalos de login y cuarentena de sesiones sospechosas.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Preservación de sesiones locales activas verificadas previamente.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Conmutación a proveedor federado secundario en 2.1 segundos.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Revalidación de firmas JWT contra clave pública de respaldo.' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Traza completa de accesos validados durante el periodo de contingencia.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-04',
    name: 'Escenario 4: Banking Connector Down',
    description: 'Desconexión del conector SPEI/Bancario durante dispersión o conciliación, activando cola segura de pagos sin duplicados.',
    targetComponent: 'Banking',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-004',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Timeout de API bancaria STP/BBVA en consulta de saldo y emisión SPEI.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Pausa preventiva del motor de dispersión automática para evitar reintentos duplicados.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Marcado de transacciones en estado WAITING_BANK_CONFIRMATION con bloqueo.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Restablecimiento de webhook y canal secundario bancario.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Conciliación 100% precisa contra extracto CEP del Banco de México ($0.00 diferencia).' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Firma de auditoría contable con autorización humana obligatoria.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-05',
    name: 'Escenario 5: SAT / PAC Down',
    description: 'Interrupción del servicio de timbrado fiscal CFDI del PAC, encolando comprobantes con sello digital previo para timbrado diferido.',
    targetComponent: 'SAT/PAC',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-005',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Respuesta HTTP 503 o timeout > 4000ms en endpoint del PAC autorizado.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Aislamiento de la cola de facturación para no bloquear el despacho físico en WMS.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Generación de pre-factura interna con Folio de Control y UUID temporal reservado.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Conmutación a PAC de respaldo secundario (Finkok / Edicom).' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Timbrado de 8 CFDIs encolados y actualización de sellos digitales SAT.' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Validación de 0 duplicados fiscales y notificación por correo a clientes.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-06',
    name: 'Escenario 6: Realtime Disconnect',
    description: 'Pérdida de conectividad WebSocket con resincronización reactiva del estado del almacén y tablero Kanban.',
    targetComponent: 'Realtime',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-006',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Pérdida de paquetes WebSocket y desconexión de socket de eventos.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Cambio transparente a modo polling HTTP de baja frecuencia.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Mantenimiento del estado optimista en cliente sin parpadeo de interfaz.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Reconexión WebSocket con handshake asegurado en 1.1 segundos.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Descarga del delta de eventos desde el último sequenceId confirmado.' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Verificación de consistencia de datos en memoria vs. almacenamiento persistente.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-07',
    name: 'Escenario 7: Storage Failure',
    description: 'Falla en repositorio de expedientes y comprobantes XML/PDF, con recuperación desde bóveda secundaria replicada.',
    targetComponent: 'Storage',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-007',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Error de I/O en lectura de bucket primario de almacenamiento de archivos.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Redirección de descargas de documentos a CDN de caché perimetral.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Verificación de suma de verificación SHA-256 de todos los documentos en caché.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Activación de réplica geográfica en nube multirregión en 2.4 segundos.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Validación de 100% de archivos íntegros sin pérdida de bytes.' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Certificación de integridad documental en bitácora de cumplimiento.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-08',
    name: 'Escenario 8: Network Partition / Latency Spike',
    description: 'Pérdida temporal de paquetes de red entre zonas de disponibilidad, aplicando aislamiento de partición y resolución de quórum.',
    targetComponent: 'Integrations',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-008',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Latencia inter-servicio > 800ms y pérdida de paquetes > 15%.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Activación de Circuit Breaker para evitar cascada de fallos en llamadas remotas.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Respuestas de contingencia cacheadas para consultas de catálogo y precios.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Rerouting por enlace troncal alternativo con latencia normalizada a 18ms.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Vaciado ordenado de colas de mensajes pendientes por orden cronológico.' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Registro de métricas de red y confirmación de consistencia fuerte.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-09',
    name: 'Escenario 9: Timeout 5000ms en Microservicio Crítico',
    description: 'Simulación de latencia extrema en cálculo de rutas logísticas con timeout forzado y fallback heurístico determinista.',
    targetComponent: 'API',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-009',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Ejecución de cálculo excede umbral SLA de 5000ms.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Interrupción limpia de hilo de ejecución (AbortController) sin fuga de memoria.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Activación de algoritmo heurístico de contingencia pre-computado.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Entrega de ruta optimizada con 97% de eficiencia al operador logístico.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Asignación confirmada en base de datos sin bloquear al usuario.' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Marcado de predicción como HEURISTIC_FALLBACK en la traza de auditoría.' },
    ],
  },
  {
    scenarioId: 'DR-SCEN-10',
    name: 'Escenario 10: Duplicate Event Burst (Tormenta de Eventos)',
    description: 'Inyección de 100 eventos concurrentes con la misma Idempotency Key para validar protección absoluta contra doble cobro o doble surtido.',
    targetComponent: 'Audit',
    isNonDestructiveSandbox: true,
    auditTrailId: 'AUD-DR-010',
    status: 'IDLE',
    durationMs: 0,
    steps: [
      { phase: 'DETECT', status: 'PENDING', details: 'Ingreso simultáneo de 100 peticiones POST con la misma clave de idempotencia.' },
      { phase: 'ISOLATE', status: 'PENDING', details: 'Adquisición de Lock distribuido por el primer hilo en 1.2 milisegundos.' },
      { phase: 'PROTECT', status: 'PENDING', details: 'Descarte inmediato de las 99 peticiones restantes con respuesta 200 idempotente.' },
      { phase: 'RECOVER', status: 'PENDING', details: 'Procesamiento único del pedido original sin duplicar inventario ni cargo contable.' },
      { phase: 'RECONCILE', status: 'PENDING', details: 'Verificación de saldo de inventario: exactamente 1 unidad descontada (0 duplicados).' },
      { phase: 'AUDIT', status: 'PENDING', details: 'Emisión de reporte de protección antifraude con 100% de efectividad.' },
    ],
  },
];

export const INITIAL_MASTER_TRANSACTIONS: MasterTransactionRecoveryChain[] = [
  {
    masterTransactionId: 'MTX-2026-08819',
    customerName: 'Constructora e Inmobiliaria del Norte S.A. de C.V.',
    LAST_CONFIRMED_STATE: 'PAYMENT_RECEIVED',
    PENDING_EVENTS: 0,
    FAILED_EVENTS: 0,
    ROLLED_BACK_EVENTS: 0,
    COMPENSATING_EVENTS: 0,
    AUDIT_EVENTS: 17,
    isComplete: true,
    healthStatus: 'INTACT',
    stages: [
      { stepNumber: 1, stageName: 'Lead', status: 'CONFIRMED', entityId: 'LEAD-1049', amount: 0, timestamp: '2026-08-20T09:15:00Z', sha256Hash: 'a1b2c3d4...', details: 'Captura de lead calificado vía portal web.' },
      { stepNumber: 2, stageName: 'Opportunity', status: 'CONFIRMED', entityId: 'OPP-892', amount: 284500, timestamp: '2026-08-20T11:30:00Z', sha256Hash: 'b2c3d4e5...', details: 'Oportunidad de suministro de cable y transformadores.' },
      { stepNumber: 3, stageName: 'Quote', status: 'CONFIRMED', entityId: 'COT-2026-0412', amount: 284500, timestamp: '2026-08-21T10:00:00Z', sha256Hash: 'c3d4e5f6...', details: 'Cotización con lista de precios industrial y descuento del 5%.' },
      { stepNumber: 4, stageName: 'Approval', status: 'CONFIRMED', entityId: 'APR-9912', amount: 284500, timestamp: '2026-08-21T14:20:00Z', sha256Hash: 'd4e5f6a1...', details: 'Aprobación comercial y de crédito por Gerencia de Ventas.' },
      { stepNumber: 5, stageName: 'Order', status: 'CONFIRMED', entityId: 'PED-2026-0889', amount: 284500, timestamp: '2026-08-22T08:45:00Z', sha256Hash: 'e5f6a1b2...', details: 'Pedido en firme generado con Orden de Compra de cliente.' },
      { stepNumber: 6, stageName: 'Inventory Reservation', status: 'CONFIRMED', entityId: 'RES-0889-1', amount: 284500, timestamp: '2026-08-22T08:46:00Z', sha256Hash: 'f6a1b2c3...', details: 'Reserva atómica de stock en Almacén Central sin colisiones.' },
      { stepNumber: 7, stageName: 'WMS', status: 'CONFIRMED', entityId: 'WMS-ORD-4412', amount: 0, timestamp: '2026-08-22T10:15:00Z', sha256Hash: '1a2b3c4d...', details: 'Generación de orden de trabajo en WMS con ruta de recolección.' },
      { stepNumber: 8, stageName: 'Picking', status: 'CONFIRMED', entityId: 'PICK-9012', amount: 0, timestamp: '2026-08-22T11:40:00Z', sha256Hash: '2b3c4d5e...', details: 'Surtido verificado por código de barras 2D por operador de almacén.' },
      { stepNumber: 9, stageName: 'Shipment', status: 'CONFIRMED', entityId: 'EMB-3310', amount: 0, timestamp: '2026-08-22T15:00:00Z', sha256Hash: '3c4d5e6f...', details: 'Embarque en camión de ruta #4 con hoja de despacho firmada.' },
      { stepNumber: 10, stageName: 'Invoice', status: 'CONFIRMED', entityId: 'FACT-2026-1190', amount: 284500, timestamp: '2026-08-22T16:15:00Z', sha256Hash: '4d5e6f1a...', details: 'CFDI 4.0 timbrado exitosamente con SAT UUID 88AB-9921-CDEF.' },
      { stepNumber: 11, stageName: 'CXC', status: 'CONFIRMED', entityId: 'CXC-4019', amount: 284500, timestamp: '2026-08-22T16:20:00Z', sha256Hash: '5e6f1a2b...', details: 'Registro contable en cuentas por cobrar a 30 días.' },
      { stepNumber: 12, stageName: 'Payment', status: 'CONFIRMED', entityId: 'PAG-8812', amount: 284500, timestamp: '2026-08-26T11:30:00Z', sha256Hash: '6f1a2b3c...', details: 'Cobranza recibida vía transferencia electrónica SPEI.' },
      { stepNumber: 13, stageName: 'Bank', status: 'CONFIRMED', entityId: 'BNK-TX-9902', amount: 284500, timestamp: '2026-08-26T11:35:00Z', sha256Hash: '1f2a3b4c...', details: 'Conciliación bancaria automática con extracto STP ($0.00 dif).' },
      { stepNumber: 14, stageName: 'Commission', status: 'CONFIRMED', entityId: 'COM-08819', amount: 8535, timestamp: '2026-08-26T14:00:00Z', sha256Hash: '2a3b4c5d...', details: 'Cálculo de comisión al 3% para el ejecutivo de ventas asignado.' },
      { stepNumber: 15, stageName: 'Payroll', status: 'CONFIRMED', entityId: 'NOM-INC-441', amount: 8535, timestamp: '2026-08-26T14:05:00Z', sha256Hash: '3b4c5d6e...', details: 'Integración automática a la prenómina quincenal de RH.' },
      { stepNumber: 16, stageName: 'Profitability', status: 'CONFIRMED', entityId: 'PRF-08819', amount: 76815, timestamp: '2026-08-26T16:00:00Z', sha256Hash: '4c5d6e7f...', details: 'Margen de utilidad bruta real consolidado en 27.0%.' },
      { stepNumber: 17, stageName: 'EBITDA', status: 'CONFIRMED', entityId: 'EBT-08819', amount: 54055, timestamp: '2026-08-26T16:05:00Z', sha256Hash: '5d6e7f8a...', details: 'Contribución neta al EBITDA de la unidad de negocio.' },
    ],
  },
  {
    masterTransactionId: 'MTX-2026-08820',
    customerName: 'Desarrollos Industriales del Bajío S.A.P.I.',
    LAST_CONFIRMED_STATE: 'INVOICE_GENERATED',
    PENDING_EVENTS: 6,
    FAILED_EVENTS: 0,
    ROLLED_BACK_EVENTS: 0,
    COMPENSATING_EVENTS: 0,
    AUDIT_EVENTS: 11,
    isComplete: false,
    healthStatus: 'RECOVERABLE',
    stages: [
      { stepNumber: 1, stageName: 'Lead', status: 'CONFIRMED', entityId: 'LEAD-1055', amount: 0, timestamp: '2026-08-22T10:00:00Z', sha256Hash: 'ab12cd34...', details: 'Lead recurrente de cuenta corporativa.' },
      { stepNumber: 2, stageName: 'Opportunity', status: 'CONFIRMED', entityId: 'OPP-899', amount: 412000, timestamp: '2026-08-22T11:00:00Z', sha256Hash: 'bc23de45...', details: 'Requerimiento de conductores y tubería conduit.' },
      { stepNumber: 3, stageName: 'Quote', status: 'CONFIRMED', entityId: 'COT-2026-0420', amount: 412000, timestamp: '2026-08-23T09:30:00Z', sha256Hash: 'cd34ef56...', details: 'Cotización con condiciones de pago a 30 días.' },
      { stepNumber: 4, stageName: 'Approval', status: 'CONFIRMED', entityId: 'APR-9925', amount: 412000, timestamp: '2026-08-23T11:15:00Z', sha256Hash: 'de45fa67...', details: 'Autorización ejecutiva con excepción temporal de crédito.' },
      { stepNumber: 5, stageName: 'Order', status: 'CONFIRMED', entityId: 'PED-2026-0895', amount: 412000, timestamp: '2026-08-23T14:00:00Z', sha256Hash: 'ef56ab78...', details: 'Pedido confirmado y bloqueado para surtido inmediato.' },
      { stepNumber: 6, stageName: 'Inventory Reservation', status: 'CONFIRMED', entityId: 'RES-0895-1', amount: 412000, timestamp: '2026-08-23T14:02:00Z', sha256Hash: 'fa67bc89...', details: 'Reserva exitosa en WMS.' },
      { stepNumber: 7, stageName: 'WMS', status: 'CONFIRMED', entityId: 'WMS-ORD-4420', amount: 0, timestamp: '2026-08-24T08:30:00Z', sha256Hash: '1b2c3d4e...', details: 'Orden de recolección en Almacén Norte.' },
      { stepNumber: 8, stageName: 'Picking', status: 'CONFIRMED', entityId: 'PICK-9022', amount: 0, timestamp: '2026-08-24T10:00:00Z', sha256Hash: '2c3d4e5f...', details: 'Surtido completo sin faltantes.' },
      { stepNumber: 9, stageName: 'Shipment', status: 'CONFIRMED', entityId: 'EMB-3318', amount: 0, timestamp: '2026-08-24T14:30:00Z', sha256Hash: '3d4e5f6a...', details: 'Despacho entregado con firma de recibo de obra.' },
      { stepNumber: 10, stageName: 'Invoice', status: 'CONFIRMED', entityId: 'FACT-2026-1205', amount: 412000, timestamp: '2026-08-24T16:00:00Z', sha256Hash: '4e5f6a1b...', details: 'CFDI 4.0 timbrado con SAT UUID 99CD-1123-EFAB.' },
      { stepNumber: 11, stageName: 'CXC', status: 'CONFIRMED', entityId: 'CXC-4025', amount: 412000, timestamp: '2026-08-24T16:05:00Z', sha256Hash: '5f6a1b2c...', details: 'Saldo pendiente por cobrar registrado en cartera.' },
      { stepNumber: 12, stageName: 'Payment', status: 'PENDING', entityId: 'PENDING', amount: 412000, timestamp: '', sha256Hash: '', details: 'Esperando depósito SPEI de cliente (promesa en seguimiento).' },
      { stepNumber: 13, stageName: 'Bank', status: 'PENDING', entityId: 'PENDING', amount: 0, timestamp: '', sha256Hash: '', details: 'Pendiente de conciliar en extracto bancario.' },
      { stepNumber: 14, stageName: 'Commission', status: 'PENDING', entityId: 'PENDING', amount: 12360, timestamp: '', sha256Hash: '', details: 'Comisión en reserva sujeta al cobro efectivo.' },
      { stepNumber: 15, stageName: 'Payroll', status: 'PENDING', entityId: 'PENDING', amount: 12360, timestamp: '', sha256Hash: '', details: 'Pendiente de dispersar en nómina.' },
      { stepNumber: 16, stageName: 'Profitability', status: 'PENDING', entityId: 'PENDING', amount: 111240, timestamp: '', sha256Hash: '', details: 'Rentabilidad devengada no cobrada.' },
      { stepNumber: 17, stageName: 'EBITDA', status: 'PENDING', entityId: 'PENDING', amount: 78280, timestamp: '', sha256Hash: '', details: 'Impacto en EBITDA pendiente de realización.' },
    ],
  },
  {
    masterTransactionId: 'MTX-2026-08821',
    customerName: 'Instalaciones Electromecánicas Peninsulares',
    LAST_CONFIRMED_STATE: 'CREDIT_LIMIT_EXCEEDED_ROLLED_BACK',
    PENDING_EVENTS: 0,
    FAILED_EVENTS: 1,
    ROLLED_BACK_EVENTS: 2,
    COMPENSATING_EVENTS: 2,
    AUDIT_EVENTS: 8,
    isComplete: false,
    healthStatus: 'DEGRADED',
    stages: [
      { stepNumber: 1, stageName: 'Lead', status: 'CONFIRMED', entityId: 'LEAD-1060', amount: 0, timestamp: '2026-08-25T09:00:00Z', sha256Hash: '99aa88bb...', details: 'Lead comercial.' },
      { stepNumber: 2, stageName: 'Opportunity', status: 'CONFIRMED', entityId: 'OPP-905', amount: 320000, timestamp: '2026-08-25T09:30:00Z', sha256Hash: '88bb77cc...', details: 'Oportunidad de alta tensión.' },
      { stepNumber: 3, stageName: 'Quote', status: 'CONFIRMED', entityId: 'COT-2026-0428', amount: 320000, timestamp: '2026-08-25T11:00:00Z', sha256Hash: '77cc66dd...', details: 'Cotización con precios regulares.' },
      { stepNumber: 4, stageName: 'Approval', status: 'FAILED', entityId: 'APR-9930', amount: 320000, timestamp: '2026-08-25T12:15:00Z', sha256Hash: '66dd55ee...', details: 'Rechazo automático por regla R03: Excede límite de crédito disponible ($95k saldo + $320k pedido > $250k límite).' },
      { stepNumber: 5, stageName: 'Order', status: 'ROLLED_BACK', entityId: 'PED-2026-0899', amount: 0, timestamp: '2026-08-25T12:16:00Z', sha256Hash: '55ee44ff...', details: 'Transacción cancelada limpiamente en base de datos.' },
      { stepNumber: 6, stageName: 'Inventory Reservation', status: 'COMPENSATED', entityId: 'RES-COMP-0899', amount: 0, timestamp: '2026-08-25T12:16:00Z', sha256Hash: '44ff33aa...', details: 'Compensación reversa de stock: inventario liberado a disponible (0 saldo huérfano).' },
      { stepNumber: 7, stageName: 'WMS', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No se generó orden de surtido.' },
      { stepNumber: 8, stageName: 'Picking', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 9, stageName: 'Shipment', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 10, stageName: 'Invoice', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 11, stageName: 'CXC', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 12, stageName: 'Payment', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 13, stageName: 'Bank', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 14, stageName: 'Commission', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 15, stageName: 'Payroll', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 16, stageName: 'Profitability', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
      { stepNumber: 17, stageName: 'EBITDA', status: 'INSUFFICIENT_DATA', entityId: 'N/A', amount: 0, timestamp: '', sha256Hash: '', details: 'No aplica.' },
    ],
  },
];

export const INITIAL_BOTTLENECKS: OperationsBottleneck[] = [
  {
    id: 'BOT-01',
    problema: 'Acumulación de Pedidos en Espera de Autorización de Crédito',
    causaProbable: 'Falta de revisión oportuna de excepciones de cartera durante las mañanas.',
    volumenAfectado: '6 pedidos comerciales',
    tiempoAfectado: 'Promedio de 4.8 horas de espera',
    impactoFinanciero: 540000,
    prioridad: 'HIGH',
    recomendacion: 'Establecer ventana fija de revisión a las 09:00 y 14:00 hrs para Gerencia de Finanzas con notificaciones push prioritarias.',
    modulo: 'AUTORIZACIONES',
    responsable: 'C.P. Roberto Silva',
    responsibleRole: 'FINANZAS',
    dataClassification: 'REAL',
  },
  {
    id: 'BOT-02',
    problema: 'Picking Atrasado en Línea de Cables y Conductores',
    causaProbable: 'Reubicación de carretes pesados en pasillo 4 sin equipo montacargas dedicado.',
    volumenAfectado: '18 líneas de surtido',
    tiempoAfectado: '2.5 horas de demora operativa',
    impactoFinanciero: 120000,
    prioridad: 'HIGH',
    recomendacion: 'Asignar montacargas #2 de forma exclusiva para zona de carretes durante turno matutino.',
    modulo: 'WMS',
    responsable: 'Ing. Carlos Mendoza',
    responsibleRole: 'ALMACEN',
    dataClassification: 'REAL',
  },
  {
    id: 'BOT-03',
    problema: 'Despacho Insuficiente en Andén de Carga Metropolitana',
    causaProbable: 'Coincidencia de horarios de arribo de transportistas externos con camiones propios.',
    volumenAfectado: '4 rutas locales',
    tiempoAfectado: '1.2 horas de retraso por viaje',
    impactoFinanciero: 35000,
    prioridad: 'MEDIUM',
    recomendacion: 'Asignar andén #1 exclusivamente a paqueterías externas y andén #2 a flota propia.',
    modulo: 'DESPACHO',
    responsable: 'Ing. Rodrigo Paz',
    responsibleRole: 'LOGISTICA',
    dataClassification: 'REAL',
  },
  {
    id: 'BOT-04',
    problema: 'Compras Atrasadas en Herrajes Especiales',
    causaProbable: 'Tiempo de respuesta de cotización de proveedores supera los 3 días hábiles.',
    volumenAfectado: '8 requisiciones de compra',
    tiempoAfectado: '72 horas de espera',
    impactoFinanciero: 88000,
    prioridad: 'MEDIUM',
    recomendacion: 'Dar de alta 2 proveedores alternativos con catálogo de precios pre-pactados en el sistema ERP.',
    modulo: 'COMPRAS',
    responsable: 'Lic. Andrés Valdés',
    responsibleRole: 'COMPRAS',
    dataClassification: 'CALCULATED',
  },
  {
    id: 'BOT-05',
    problema: 'Cobranza Atrasada en Clientes de Obra Pública',
    causaProbable: 'Proceso manual de validación de estimaciones y firmas de supervisores de obra.',
    volumenAfectado: '$680k MXN en cartera',
    tiempoAfectado: 'DSO extendido a 55 días',
    impactoFinanciero: 680000,
    prioridad: 'CRITICAL',
    recomendacion: 'Implementar entrega anticipada de expedientes digitales con acuse electrónico SHA-256 5 días antes de la fecha de corte.',
    modulo: 'COBRANZA',
    responsable: 'Lic. Mariana Garza',
    responsibleRole: 'FINANZAS',
    dataClassification: 'REAL',
  },
  {
    id: 'BOT-06',
    problema: 'Tickets Acumulados de Garantías y Certificados Técnicos',
    causaProbable: 'Descarga manual de certificados desde portales individuales de fabricantes.',
    volumenAfectado: '12 tickets abiertos',
    tiempoAfectado: 'Tiempo promedio de resolución: 36 horas',
    impactoFinanciero: 45000,
    prioridad: 'LOW',
    recomendacion: 'Automatizar indexación de certificados técnicos en la Bóveda Digital en el momento de la recepción física en almacén.',
    modulo: 'SOPORTE',
    responsable: 'Lic. Laura Benítez',
    responsibleRole: 'SERVICIO_CLIENTE',
    dataClassification: 'CALCULATED',
  },
];

export const INITIAL_HEALTH_SCORE: BusinessHealthScoreBreakdown = {
  overallScore: 84.6,
  rating: 'HEALTHY',
  lastUpdated: new Date().toISOString(),
  dimensions: {
    ventas: {
      name: 'Ventas Comerciales',
      weight: 0.15,
      score: 88.0,
      contribution: 13.2,
      status: 'HEALTHY',
      kpi: 'Cumplimiento de Cuota Mensual: 102.4%',
      trend: 'UP',
    },
    rentabilidad: {
      name: 'Rentabilidad & Márgenes',
      weight: 0.15,
      score: 86.5,
      contribution: 13.0,
      status: 'HEALTHY',
      kpi: 'Margen Bruto Promedio: 26.8% (Meta: 25%)',
      trend: 'UP',
    },
    liquidez: {
      name: 'Liquidez & Tesorería',
      weight: 0.15,
      score: 91.0,
      contribution: 13.65,
      status: 'EXCELLENT',
      kpi: 'Razón Ácida: 1.84x · Cobertura Egresos: 48 días',
      trend: 'STABLE',
    },
    cxc: {
      name: 'Cobranza & Cartera CXC',
      weight: 0.10,
      score: 72.0,
      contribution: 7.2,
      status: 'RISK',
      kpi: 'DSO: 42 días · 14.8% Cartera > 45 días',
      trend: 'DOWN',
    },
    inventarios: {
      name: 'Inventarios & WMS',
      weight: 0.10,
      score: 82.0,
      contribution: 8.2,
      status: 'HEALTHY',
      kpi: 'Exactitud de Registro (IRA): 99.4% · Rotación: 6.2x',
      trend: 'UP',
    },
    operaciones: {
      name: 'Operaciones & Logística',
      weight: 0.10,
      score: 85.0,
      contribution: 8.5,
      status: 'HEALTHY',
      kpi: 'Entregas a Tiempo (OTIF): 94.2%',
      trend: 'STABLE',
    },
    clientes: {
      name: 'Clientes & Satisfacción',
      weight: 0.08,
      score: 89.0,
      contribution: 7.12,
      status: 'HEALTHY',
      kpi: 'NPS: +68 · Retención Clientes Clave: 92%',
      trend: 'UP',
    },
    rh: {
      name: 'Recursos Humanos',
      weight: 0.05,
      score: 88.0,
      contribution: 4.4,
      status: 'HEALTHY',
      kpi: 'Rotación Voluntaria: 2.1% · Clima: 86%',
      trend: 'STABLE',
    },
    marketing: {
      name: 'Marketing & Adquisición',
      weight: 0.05,
      score: 84.0,
      contribution: 4.2,
      status: 'HEALTHY',
      kpi: 'CAC: $4,200 MXN · Conversión MQL a SQL: 34%',
      trend: 'UP',
    },
    riesgos: {
      name: 'Gestión de Riesgos (ERM)',
      weight: 0.04,
      score: 78.0,
      contribution: 3.12,
      status: 'RISK',
      kpi: '3 Riesgos Altos Monitoreados en Bóveda',
      trend: 'STABLE',
    },
    compliance: {
      name: 'Compliance & Normatividad',
      weight: 0.03,
      score: 96.0,
      contribution: 2.88,
      status: 'EXCELLENT',
      kpi: '100% CFDIs Válidos SAT · 0 Violaciones SoD',
      trend: 'UP',
    },
  },
};

export const INITIAL_COO_ADVISOR_ADVICES: CooAdvisorAdvice[] = [
  {
    id: 'COO-ADV-001',
    situacionActual: 'La empresa mantiene un ritmo de facturación saludable con $1.42M MXN colocados en el mes y proyección de cierre en $1.91M MXN (+3.2% vs. meta). Sin embargo, se detecta una fricción operativa en la cobranza de clientes corporativos (DSO en 42 días) y un riesgo de ruptura inminente en conductores eléctricos.',
    datosUtilizados: [
      'Facturación histórica de los últimos 6 meses',
      'Cartera de cuentas por cobrar CXC desglosada por antigüedad',
      'Kardex de existencias de Almacén Central y órdenes de compra en tránsito',
      'Bitácora de tiempos de surtido y despacho en WMS',
    ],
    datosFaltantes: [
      'Confirmación formal de pago de contrarecibo de Grupo Minero San Cristóbal',
      'Fecha estimada de liberación aduanal de transformadores de importación',
    ],
    problemaDetectado: 'Desalineación entre la velocidad de ventas y la recuperación de flujo en dos cuentas clave, combinada con bajo stock de seguridad en el SKU de mayor rotación (Cable THW Calibre 10).',
    causaProbable: 'Crecimiento de volumen sin ajuste dinámico de puntos de reorden en WMS y permisividad en los días de crédito otorgados a constructoras en etapa de cierre de obra.',
    impactoOperativo: 'Riesgo de paro en 3 cuadrillas de instalación por desabasto de cable y retraso en surtido de pedidos de fin de mes.',
    impactoFinanciero: 498400,
    riesgo: 'Pérdida de margen por compra de emergencia local y aumento del costo financiero del capital de trabajo.',
    prioridad: 'HIGH',
    oportunidad: 'Capturar $180k MXN adicionales en ventas canalizando stock hacia clientes de pago inmediato de contado.',
    alternativas: [
      'Alternativa A: Pausar temporalmente crédito a Desarrollos del Bajío y exigir liquidación del 50% antes de nuevo embarque.',
      'Alternativa B: Negociar factoraje financiero con tasa preferencial del 1.2% mensual para anticipar cobranza de obra pública.',
      'Alternativa C: Emitir orden de compra abierta con entrega semanal escalonada al fabricante Condumex.',
    ],
    recomendacion: 'Ejecutar de inmediato la compra de 50 rollos de cable THW Calibre 10 y convocar reunión ejecutiva con el director de compras de Desarrollos Industriales del Bajío para formalizar convenio de abonos semanales.',
    nextBestAction: 'Autorizar Requisición de Compra REQ-2026-0412 en el módulo de Compras y enviar estado de cuenta con certificación digital al cliente.',
    responsable: 'Ing. Carlos Mendoza (Jefe de Almacén) / C.P. Roberto Silva (Finanzas)',
    responsibleRole: 'FINANZAS',
    fechaObjetivo: '2026-08-30',
    kpiAfectado: 'DSO (días de cartera) y Nivel de Servicio OTIF en Almacén',
    impactoEsperado: 'Reducción de DSO de 42 a 34 días y garantía de 0 rupturas de stock en el mes.',
    nivelConfianza: 94,
    clasificacionDatos: 'PROJECTED',
    directivaHitl: 'REQUIERE VALIDACIÓN HUMANA: Toda modificación de condiciones comerciales o dispersión de compras mayores a $50k MXN debe ser firmada por el Director de Área.',
    auditHash: '8f912bc09124adfe901248bc90124aef8912401bcda9012389410cbefda90123',
  },
];

export const INITIAL_PREDICTION_RECORDS: PredictionRecord[] = [
  {
    predictionId: 'PRED-2026-001',
    masterTransactionId: 'MTX-2026-08819',
    entityType: 'SALES_FORECAST',
    entityId: 'FC-SALES-30D',
    predictionType: 'SALES_FORECAST',
    dataClassification: 'PROJECTED',
    prediction: 'Facturación proyectada de $1,910,000 MXN para el cierre mensual con 103.2% de cumplimiento de meta.',
    probability: 89.2,
    financialImpact: 1910000,
    timeHorizon: '30D',
    riskLevel: 'LOW',
    recommendedAction: 'Mantener seguimiento en pipeline activo y priorizar cierre de 5 cotizaciones calientes.',
    responsibleRole: 'GERENTE_VENTAS',
    targetDate: '2026-08-31',
    humanValidationRequired: false,
    createdAt: new Date().toISOString(),
    modelVersion: 'CONSCORE-PREDICT-v2.4',
    correlationId: 'CORR-PRED-001',
    dataSources: ['CRM_PIPELINE', 'SALES_HISTORY_6M', 'WMS_STOCK_LEVELS'],
    calculationMethod: 'ARIMA + Regresión Bayesiana Ponderada por Velocidad de Oportunidades',
    auditHash: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
    user: 'CONSCORE_AI_SYSTEM',
  },
  {
    predictionId: 'PRED-2026-002',
    masterTransactionId: 'MTX-2026-08819',
    entityType: 'INVENTORY_ITEM',
    entityId: 'PRD-001',
    predictionType: 'INVENTORY_RUNOUT',
    dataClassification: 'PROJECTED',
    prediction: 'Ruptura inminente de stock en Cable THW Calibre 10 en 3.5 días hábiles.',
    probability: 92.4,
    financialImpact: 86400,
    timeHorizon: '7D',
    riskLevel: 'CRITICAL',
    recommendedAction: 'Emitir orden de compra urgente por 50 rollos.',
    responsibleRole: 'COMPRAS',
    targetDate: '2026-08-28',
    humanValidationRequired: true,
    createdAt: new Date().toISOString(),
    modelVersion: 'CONSCORE-PREDICT-v2.4',
    correlationId: 'CORR-PRED-002',
    dataSources: ['WMS_KARDEX', 'CONFIRMED_ORDERS_QUEUE', 'SUPPLIER_LEAD_TIMES'],
    calculationMethod: 'Modelado de Runout Estocástico basado en Órdenes Comprometidas',
    auditHash: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
    user: 'CONSCORE_AI_SYSTEM',
  },
  {
    predictionId: 'PRED-2026-003',
    masterTransactionId: 'MTX-2026-08820',
    entityType: 'CUSTOMER_CREDIT',
    entityId: 'CUST-002',
    predictionType: 'CXC_COLLECTION',
    dataClassification: 'PROJECTED',
    prediction: 'Probabilidad del 89.5% de atraso mayor a 30 días en saldo vencido de $412,000 MXN.',
    probability: 89.5,
    financialImpact: 412000,
    timeHorizon: '30D',
    riskLevel: 'CRITICAL',
    recommendedAction: 'Pausar nuevos créditos y formalizar reestructuración de pagos.',
    responsibleRole: 'FINANZAS',
    targetDate: '2026-08-30',
    humanValidationRequired: true,
    createdAt: new Date().toISOString(),
    modelVersion: 'CONSCORE-PREDICT-v2.4',
    correlationId: 'CORR-PRED-003',
    dataSources: ['CXC_AGING_TABLE', 'PAYMENT_HISTORY_12M', 'CREDIT_BUREAU_LOGS'],
    calculationMethod: 'Scoring de Crédito Predictivo + Análisis de Frecuencia de Promesas Incumplidas',
    auditHash: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
    user: 'CONSCORE_AI_SYSTEM',
  },
  {
    predictionId: 'PRED-2026-004',
    masterTransactionId: 'MTX-2026-08819',
    entityType: 'CASH_FLOW',
    entityId: 'CF-FORECAST-30D',
    predictionType: 'CASH_FLOW',
    dataClassification: 'PROJECTED',
    prediction: 'Superávit neto de flujo de efectivo estimado en +$115,000 MXN con saldo final proyectado de $955,000 MXN.',
    probability: 88.0,
    financialImpact: 115000,
    timeHorizon: '30D',
    riskLevel: 'LOW',
    recommendedAction: 'Mantener calendario de pagos a proveedores y reinvertir excedente en compras anticipadas de alta rotación.',
    responsibleRole: 'FINANZAS',
    targetDate: '2026-08-31',
    humanValidationRequired: false,
    createdAt: new Date().toISOString(),
    modelVersion: 'CONSCORE-PREDICT-v2.4',
    correlationId: 'CORR-PRED-004',
    dataSources: ['TREASURY_BALANCES', 'PROJECTED_CXC', 'COMMITTED_CXP', 'PAYROLL_BUDGET'],
    calculationMethod: 'Modelo Determinista de Flujo de Caja Integrado Directo',
    auditHash: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
    user: 'CONSCORE_AI_SYSTEM',
  },
];
