/**
 * @license
 * CONSCORE ERP IA - Planeación Estratégica, OKR & BSC
 * FASE 12 - Datos Iniciales Certificados
 */

import {
  StrategicObjective,
  BSCIndicator,
  OKRKeyResult,
  StrategicInitiative,
  StrategicVarianceItem,
  StrategicAlert,
  ExecutiveActionItem,
  MultiMetricStrategicForecast,
  PriorityMatrixItem,
  SensitivityVariableEffect,
} from '../types/strategicPlanningTypes';

export const INITIAL_STRATEGIC_OBJECTIVES: StrategicObjective[] = [
  {
    objectiveId: 'OBJ-2026-001',
    code: 'FIN-01',
    name: 'Maximizar Rentabilidad y Expansión del Margen EBITDA',
    description: 'Elevar el margen EBITDA al 24.5% mediante optimización de la mezcla de productos de alta densidad térmica y reducción de mermas.',
    perspective: 'FINANCIERA',
    ownerId: 'USR-001',
    ownerName: 'Lic. Fernando Garza (Director General)',
    departmentId: 'DEP-FIN',
    departmentName: 'Dirección General & Finanzas',
    startDate: '2026-01-01',
    targetDate: '2026-12-31',
    baseline: 19.2,
    target: 24.5,
    currentValue: 22.8,
    unit: '%',
    progress: 72,
    status: 'ON_TRACK',
    priority: 'CRITICAL',
    semaphore: 'GREEN',
    keyResultIds: ['KR-001', 'KR-002', 'KR-003'],
    initiativeIds: ['INIT-001', 'INIT-002'],
    updatedAt: '2026-08-27T08:30:00Z',
  },
  {
    objectiveId: 'OBJ-2026-002',
    code: 'FIN-02',
    name: 'Optimizar Flujo de Caja y Reducción del Ciclo Financiero (DSO)',
    description: 'Acelerar la cobranza corporativa para disminuir el DSO de 52 a 38 días sin deteriorar la relación con cuentas clave.',
    perspective: 'FINANCIERA',
    ownerId: 'USR-005',
    ownerName: 'C.P. Mariana Rivas (Gerente de Finanzas)',
    departmentId: 'DEP-FIN',
    departmentName: 'Finanzas & Tesorería',
    startDate: '2026-01-01',
    targetDate: '2026-12-31',
    baseline: 52.0,
    target: 38.0,
    currentValue: 42.5,
    unit: 'Días',
    progress: 68,
    status: 'ON_TRACK',
    priority: 'HIGH',
    semaphore: 'YELLOW',
    keyResultIds: ['KR-004', 'KR-005'],
    initiativeIds: ['INIT-003'],
    updatedAt: '2026-08-27T08:30:00Z',
  },
  {
    objectiveId: 'OBJ-2026-003',
    code: 'CLI-01',
    name: 'Consolidar Liderazgo y Retención de Cuentas Industriales Tier A',
    description: 'Alcanzar un NPS ≥ +65 y tasa de retención del 96% en plantas petroquímicas, termoeléctricas y siderúrgicas.',
    perspective: 'CLIENTES',
    ownerId: 'USR-002',
    ownerName: 'Ing. Carlos Mendoza (Gerente Comercial)',
    departmentId: 'DEP-VTAS',
    departmentName: 'Ventas & Postventa',
    startDate: '2026-01-01',
    targetDate: '2026-12-31',
    baseline: 48.0,
    target: 65.0,
    currentValue: 62.0,
    unit: 'Puntos NPS',
    progress: 82,
    status: 'ON_TRACK',
    priority: 'CRITICAL',
    semaphore: 'GREEN',
    keyResultIds: ['KR-006', 'KR-007'],
    initiativeIds: ['INIT-004', 'INIT-005'],
    updatedAt: '2026-08-27T08:30:00Z',
  },
  {
    objectiveId: 'OBJ-2026-004',
    code: 'PROC-01',
    name: 'Excelencia Operativa Logística & Cumplimiento OTIF ≥ 98%',
    description: 'Reducir tiempos de entrega y eliminar incidencias de picking en naves de almacenamiento y transporte dedicado.',
    perspective: 'PROCESOS_INTERNOS',
    ownerId: 'USR-003',
    ownerName: 'Ing. Roberto Hernández (Gerente de Operaciones)',
    departmentId: 'DEP-LOG',
    departmentName: 'Logística & Almacenes',
    startDate: '2026-01-01',
    targetDate: '2026-12-31',
    baseline: 91.5,
    target: 98.0,
    currentValue: 95.8,
    unit: '% OTIF',
    progress: 66,
    status: 'AT_RISK',
    priority: 'HIGH',
    semaphore: 'YELLOW',
    keyResultIds: ['KR-008', 'KR-009'],
    initiativeIds: ['INIT-006'],
    updatedAt: '2026-08-27T08:30:00Z',
  },
  {
    objectiveId: 'OBJ-2026-005',
    code: 'APR-01',
    name: 'Transformación del Talento, Certificación Técnica & Productividad',
    description: 'Certificar al 100% de la fuerza técnica y comercial en normas ASTM C547 / C592 y elevar el revenue por colaborador a $1.8M MXN.',
    perspective: 'APRENDIZAJE_CRECIMIENTO',
    ownerId: 'USR-006',
    ownerName: 'Lic. Lorena Castillo (Gerente de RH)',
    departmentId: 'DEP-RH',
    departmentName: 'Recursos Humanos',
    startDate: '2026-01-01',
    targetDate: '2026-12-31',
    baseline: 65.0,
    target: 100.0,
    currentValue: 88.0,
    unit: '% Certificados',
    progress: 65,
    status: 'ON_TRACK',
    priority: 'MEDIUM',
    semaphore: 'GREEN',
    keyResultIds: ['KR-010', 'KR-011'],
    initiativeIds: ['INIT-007'],
    updatedAt: '2026-08-27T08:30:00Z',
  },
];

export const INITIAL_BSC_INDICATORS: BSCIndicator[] = [
  // 1. FINANCIERA
  {
    indicatorId: 'BSC-FIN-01',
    perspective: 'FINANCIERA',
    name: 'Margen EBITDA Global',
    description: 'Utilidad operativa antes de intereses, impuestos, depreciación y amortización sobre ventas netas.',
    code: 'EBITDA_%',
    unit: '%',
    baseline: 19.2,
    target: 24.5,
    currentValue: 22.8,
    historicalPrevious: 21.4,
    yoyChangePct: +3.6,
    momChangePct: +0.7,
    semaphore: 'GREEN',
    dataHonesty: 'CALCULATED',
    formulaDescription: '(EBITDA / Ventas Netas Totales) * 100',
    owner: 'C.P. Mariana Rivas',
    targetToleranceRange: { greenMin: 22.0, yellowMin: 19.5, orangeMin: 17.0 },
  },
  {
    indicatorId: 'BSC-FIN-02',
    perspective: 'FINANCIERA',
    name: 'Margen de Contribución Industrial',
    description: 'Margen remanente tras deducir costo Kardex, comisiones, fletes y garantías.',
    code: 'MARGEN_CONTRIB_%',
    unit: '%',
    baseline: 34.0,
    target: 40.0,
    currentValue: 38.4,
    historicalPrevious: 36.8,
    yoyChangePct: +4.4,
    momChangePct: +0.5,
    semaphore: 'GREEN',
    dataHonesty: 'CALCULATED',
    formulaDescription: '((Ventas - COGS - Fletes - Comisiones) / Ventas) * 100',
    owner: 'Lic. Fernando Garza',
    targetToleranceRange: { greenMin: 37.0, yellowMin: 34.0, orangeMin: 30.0 },
  },
  {
    indicatorId: 'BSC-FIN-03',
    perspective: 'FINANCIERA',
    name: 'Flujo Operativo de Caja (Free Cash Flow)',
    description: 'Generación neta de efectivo operativo mensual en cuenta fiscal.',
    code: 'FLUJO_CAJA_MXN',
    unit: 'MXN',
    baseline: 850000,
    target: 1500000,
    currentValue: 1380000,
    historicalPrevious: 1150000,
    yoyChangePct: +20.0,
    momChangePct: +3.5,
    semaphore: 'GREEN',
    dataHonesty: 'REAL',
    formulaDescription: 'Cobranza Efectiva - Pagos Proveedores - Nómina - Gastos Op',
    owner: 'C.P. Mariana Rivas',
    targetToleranceRange: { greenMin: 1200000, yellowMin: 900000, orangeMin: 600000 },
  },
  {
    indicatorId: 'BSC-FIN-04',
    perspective: 'FINANCIERA',
    name: 'Días de Cartera (DSO - Days Sales Outstanding)',
    description: 'Promedio de días que tarda la empresa en cobrar sus facturas emitidas.',
    code: 'DSO_DIAS',
    unit: 'Días',
    baseline: 52.0,
    target: 38.0,
    currentValue: 42.5,
    historicalPrevious: 45.0,
    yoyChangePct: -18.2,
    momChangePct: -2.1,
    semaphore: 'YELLOW',
    dataHonesty: 'CALCULATED',
    formulaDescription: '(Cuentas por Cobrar Totales / Ventas Totales del Periodo) * Días',
    owner: 'Lic. Andrea Lozano (CXC)',
    targetToleranceRange: { greenMin: 38.0, yellowMin: 45.0, orangeMin: 55.0 },
  },

  // 2. CLIENTES
  {
    indicatorId: 'BSC-CLI-01',
    perspective: 'CLIENTES',
    name: 'Net Promoter Score (NPS Global)',
    description: 'Índice de lealtad y recomendación de clientes industriales.',
    code: 'NPS_SCORE',
    unit: 'Pts',
    baseline: 48,
    target: 65,
    currentValue: 62,
    historicalPrevious: 58,
    yoyChangePct: +29.1,
    momChangePct: +4.0,
    semaphore: 'GREEN',
    dataHonesty: 'CALCULATED',
    formulaDescription: '% Promotores (Score 9-10) - % Detractores (Score 0-6)',
    owner: 'Lic. Sofía Morales',
    targetToleranceRange: { greenMin: 60, yellowMin: 50, orangeMin: 35 },
  },
  {
    indicatorId: 'BSC-CLI-02',
    perspective: 'CLIENTES',
    name: 'Tasa de Retención de Clientes Tier A',
    description: 'Porcentaje de clientes corporativos que repiten compras en el ejercicio.',
    code: 'RETENCION_TIER_A_%',
    unit: '%',
    baseline: 89.0,
    target: 96.0,
    currentValue: 94.2,
    historicalPrevious: 92.0,
    yoyChangePct: +5.8,
    momChangePct: +0.4,
    semaphore: 'GREEN',
    dataHonesty: 'REAL',
    formulaDescription: '(Clientes Activos Fin - Clientes Nuevos) / Clientes Inicio * 100',
    owner: 'Ing. Carlos Mendoza',
    targetToleranceRange: { greenMin: 93.0, yellowMin: 88.0, orangeMin: 80.0 },
  },
  {
    indicatorId: 'BSC-CLI-03',
    perspective: 'CLIENTES',
    name: 'Ticket Promedio por Pedido Industrial',
    description: 'Importe promedio facturado por orden de compra surtida.',
    code: 'TICKET_PROMEDIO_MXN',
    unit: 'MXN',
    baseline: 68000,
    target: 95000,
    currentValue: 88450,
    historicalPrevious: 82000,
    yoyChangePct: +30.0,
    momChangePct: +2.2,
    semaphore: 'GREEN',
    dataHonesty: 'REAL',
    formulaDescription: 'Ventas Totales Facturadas / Número Total de Pedidos',
    owner: 'Ing. Carlos Mendoza',
    targetToleranceRange: { greenMin: 85000, yellowMin: 75000, orangeMin: 60000 },
  },
  {
    indicatorId: 'BSC-CLI-04',
    perspective: 'CLIENTES',
    name: 'Tasa de Reclamos & Incidencias Postventa',
    description: 'Porcentaje de pedidos con reportes técnicos o reclamos de calidad.',
    code: 'TASA_RECLAMOS_%',
    unit: '%',
    baseline: 4.8,
    target: 1.5,
    currentValue: 2.2,
    historicalPrevious: 2.9,
    yoyChangePct: -54.1,
    momChangePct: -0.3,
    semaphore: 'YELLOW',
    dataHonesty: 'REAL',
    formulaDescription: '(Pedidos con Reclamo / Pedidos Totales Entregados) * 100',
    owner: 'Lic. Sofía Morales',
    targetToleranceRange: { greenMin: 1.8, yellowMin: 3.0, orangeMin: 4.5 },
  },

  // 3. PROCESOS INTERNOS
  {
    indicatorId: 'BSC-PROC-01',
    perspective: 'PROCESOS_INTERNOS',
    name: 'Cumplimiento de Entrega OTIF (On-Time In-Full)',
    description: 'Órdenes entregadas en la fecha acordada y con el 100% del material.',
    code: 'OTIF_%',
    unit: '%',
    baseline: 91.5,
    target: 98.0,
    currentValue: 95.8,
    historicalPrevious: 94.0,
    yoyChangePct: +4.7,
    momChangePct: +0.6,
    semaphore: 'YELLOW',
    dataHonesty: 'CALCULATED',
    formulaDescription: '(Entregas a Tiempo y Completas / Entregas Totales) * 100',
    owner: 'Ing. Roberto Hernández',
    targetToleranceRange: { greenMin: 97.0, yellowMin: 94.0, orangeMin: 90.0 },
  },
  {
    indicatorId: 'BSC-PROC-02',
    perspective: 'PROCESOS_INTERNOS',
    name: 'Rotación de Inventario Anualizada',
    description: 'Número de veces que el inventario de almacén se vende y reemplaza en el año.',
    code: 'ROTACION_INVENTARIO',
    unit: 'Veces/Año',
    baseline: 5.2,
    target: 8.5,
    currentValue: 7.4,
    historicalPrevious: 6.8,
    yoyChangePct: +42.3,
    momChangePct: +0.2,
    semaphore: 'GREEN',
    dataHonesty: 'CALCULATED',
    formulaDescription: 'Costo de Ventas Anual (COGS) / Inventario Promedio Valuado',
    owner: 'C.P. Mario Alatorre',
    targetToleranceRange: { greenMin: 7.2, yellowMin: 6.0, orangeMin: 4.5 },
  },
  {
    indicatorId: 'BSC-PROC-03',
    perspective: 'PROCESOS_INTERNOS',
    name: 'Exactitud de Registro de Almacén (IRA)',
    description: 'Concordancia física vs sistema en conteos cíclicos de estantería.',
    code: 'IRA_EXACTITUD_%',
    unit: '%',
    baseline: 96.0,
    target: 99.8,
    currentValue: 99.2,
    historicalPrevious: 98.5,
    yoyChangePct: +3.3,
    momChangePct: +0.1,
    semaphore: 'GREEN',
    dataHonesty: 'REAL',
    formulaDescription: '(Ubicaciones con Stock 100% Exacto / Ubicaciones Auditadas) * 100',
    owner: 'Ing. Roberto Hernández',
    targetToleranceRange: { greenMin: 99.0, yellowMin: 97.5, orangeMin: 95.0 },
  },

  // 4. APRENDIZAJE Y CRECIMIENTO
  {
    indicatorId: 'BSC-APR-01',
    perspective: 'APRENDIZAJE_CRECIMIENTO',
    name: 'Cumplimiento Plan de Capacitación Técnica',
    description: 'Horas y certificaciones acreditadas en normativas térmicas y seguridad.',
    code: 'CAPACITACION_%',
    unit: '%',
    baseline: 65.0,
    target: 100.0,
    currentValue: 88.0,
    historicalPrevious: 82.0,
    yoyChangePct: +35.3,
    momChangePct: +2.0,
    semaphore: 'GREEN',
    dataHonesty: 'REAL',
    formulaDescription: '(Horas Capacitación Ejecutadas / Horas Programadas) * 100',
    owner: 'Lic. Lorena Castillo',
    targetToleranceRange: { greenMin: 90.0, yellowMin: 80.0, orangeMin: 70.0 },
  },
  {
    indicatorId: 'BSC-APR-02',
    perspective: 'APRENDIZAJE_CRECIMIENTO',
    name: 'Productividad / Facturación por Empleado',
    description: 'Ingreso promedio generado por cada integrante del headcount activo.',
    code: 'REVENUE_PER_EMP_MXN',
    unit: 'MXN/Colab',
    baseline: 1250000,
    target: 1800000,
    currentValue: 1680000,
    historicalPrevious: 1520000,
    yoyChangePct: +34.4,
    momChangePct: +1.8,
    semaphore: 'GREEN',
    dataHonesty: 'CALCULATED',
    formulaDescription: 'Ventas Totales Facturadas / Headcount Promedio',
    owner: 'Lic. Fernando Garza',
    targetToleranceRange: { greenMin: 1600000, yellowMin: 1400000, orangeMin: 1200000 },
  },
  {
    indicatorId: 'BSC-APR-03',
    perspective: 'APRENDIZAJE_CRECIMIENTO',
    name: 'Rotación No Deseada de Personal',
    description: 'Porcentaje de renuncias en puestos clave operativos y comerciales.',
    code: 'ROTACION_RH_%',
    unit: '%',
    baseline: 14.2,
    target: 5.0,
    currentValue: 6.8,
    historicalPrevious: 7.5,
    yoyChangePct: -52.1,
    momChangePct: -0.2,
    semaphore: 'YELLOW',
    dataHonesty: 'REAL',
    formulaDescription: '(Bajas Voluntarias / Headcount Promedio) * 100',
    owner: 'Lic. Lorena Castillo',
    targetToleranceRange: { greenMin: 5.5, yellowMin: 8.0, orangeMin: 12.0 },
  },
];

export const INITIAL_OKR_KEY_RESULTS: OKRKeyResult[] = [
  {
    krId: 'KR-001',
    objectiveId: 'OBJ-2026-001',
    code: 'KR1.1',
    title: 'Elevar margen de contribución industrial del 34% al 40%',
    metricName: 'Margen de Contribución',
    baseline: 34.0,
    target: 40.0,
    currentValue: 38.4,
    unit: '%',
    progressPct: 73,
    confidenceScore: 0.88,
    ownerId: 'USR-001',
    ownerName: 'Lic. Fernando Garza',
    deadline: '2026-12-31',
    status: 'ON_TRACK',
    initiativesCount: 2,
  },
  {
    krId: 'KR-002',
    objectiveId: 'OBJ-2026-001',
    code: 'KR1.2',
    title: 'Reducir el costo logístico de reparto por tonelada en 8.5%',
    metricName: 'Costo Logístico / Ton',
    baseline: 2450,
    target: 2240,
    currentValue: 2290,
    unit: 'MXN/Ton',
    progressPct: 76,
    confidenceScore: 0.85,
    ownerId: 'USR-003',
    ownerName: 'Ing. Roberto Hernández',
    deadline: '2026-09-30',
    status: 'ON_TRACK',
    initiativesCount: 1,
  },
  {
    krId: 'KR-003',
    objectiveId: 'OBJ-2026-001',
    code: 'KR1.3',
    title: 'Eliminar en un 70% los descuentos fuera de política comercial',
    metricName: 'Descuentos No Autorizados',
    baseline: 320000,
    target: 96000,
    currentValue: 142000,
    unit: 'MXN/Mes',
    progressPct: 79,
    confidenceScore: 0.90,
    ownerId: 'USR-002',
    ownerName: 'Ing. Carlos Mendoza',
    deadline: '2026-11-30',
    status: 'ON_TRACK',
    initiativesCount: 1,
  },
  {
    krId: 'KR-004',
    objectiveId: 'OBJ-2026-002',
    code: 'KR2.1',
    title: 'Cobrar el 95% de facturas vencidas a más de 45 días',
    metricName: 'Recuperación Cartera Vencida',
    baseline: 68.0,
    target: 95.0,
    currentValue: 84.0,
    unit: '%',
    progressPct: 59,
    confidenceScore: 0.75,
    ownerId: 'USR-005',
    ownerName: 'C.P. Mariana Rivas',
    deadline: '2026-10-31',
    status: 'AT_RISK',
    initiativesCount: 1,
  },
  {
    krId: 'KR-006',
    objectiveId: 'OBJ-2026-003',
    code: 'KR3.1',
    title: 'Asegurar 100% de entregas con certificado de calidad y trazabilidad',
    metricName: 'Entregas con Certificado',
    baseline: 82.0,
    target: 100.0,
    currentValue: 98.5,
    unit: '%',
    progressPct: 91,
    confidenceScore: 0.95,
    ownerId: 'USR-004',
    ownerName: 'Lic. Sofía Morales',
    deadline: '2026-12-31',
    status: 'ON_TRACK',
    initiativesCount: 2,
  },
];

export const INITIAL_STRATEGIC_INITIATIVES: StrategicInitiative[] = [
  {
    initiativeId: 'INIT-001',
    objectiveId: 'OBJ-2026-001',
    objectiveName: 'Maximizar Rentabilidad y Expansión del Margen EBITDA',
    krId: 'KR-001',
    name: 'Plan de Reconfiguración de Precios en Líneas de Alta Densidad (PRE-1080 / PRE-1090)',
    description: 'Ajustar precios de lista en un +3.8% selectivo en materiales aislantes donde CONSCORE tiene cuota de mercado >45% sin riesgo de sustitución.',
    ownerId: 'USR-002',
    ownerName: 'Ing. Carlos Mendoza',
    department: 'Comercial',
    budget: 45000,
    spentBudget: 12000,
    expectedFinancialImpact: 580000,
    actualFinancialImpact: 410000,
    expectedImpactSummary: '+ $580,000 MXN adicionales de margen bruto directo en el segundo semestre.',
    impactScore: 9,
    effortScore: 3,
    matrixClassification: 'QUICK_WINS',
    startDate: '2026-02-01',
    targetDate: '2026-06-30',
    status: 'COMPLETED',
    priority: 'CRITICAL',
    notes: 'Implementado con éxito. Ningún cliente canceló contratos marco.',
  },
  {
    initiativeId: 'INIT-002',
    objectiveId: 'OBJ-2026-001',
    objectiveName: 'Maximizar Rentabilidad y Expansión del Margen EBITDA',
    krId: 'KR-002',
    name: 'Ruteo Dinámico & Consolidación de Carga por Zona Industrial (Fase 10 Logística)',
    description: 'Agrupar pedidos foráneos (Monterrey - Saltillo - Ramos Arizpe) en camiones de 3.5 y 10 toneladas para maximizar ocupación cúbica.',
    ownerId: 'USR-003',
    ownerName: 'Ing. Roberto Hernández',
    department: 'Logística',
    budget: 80000,
    spentBudget: 65000,
    expectedFinancialImpact: 340000,
    actualFinancialImpact: 295000,
    expectedImpactSummary: 'Ahorro logístico de $340,000 MXN anualizados en combustible y fletes tercerizados.',
    impactScore: 8,
    effortScore: 4,
    matrixClassification: 'QUICK_WINS',
    startDate: '2026-03-01',
    targetDate: '2026-09-30',
    status: 'ACTIVE',
    priority: 'HIGH',
  },
  {
    initiativeId: 'INIT-003',
    objectiveId: 'OBJ-2026-002',
    objectiveName: 'Optimizar Flujo de Caja y Reducción del Ciclo Financiero (DSO)',
    krId: 'KR-004',
    name: 'Automatización de Portal B2B de Cobranza & Facturación Electrónica Inmediata',
    description: 'Envío automático de complementos de pago y estado de cuenta semanal a cuentas clave por WhatsApp y correo certificado.',
    ownerId: 'USR-005',
    ownerName: 'C.P. Mariana Rivas',
    department: 'Finanzas',
    budget: 120000,
    spentBudget: 95000,
    expectedFinancialImpact: 850000,
    actualFinancialImpact: 520000,
    expectedImpactSummary: 'Aceleración de liquidez en $850,000 MXN y recorte de 8 días de cartera.',
    impactScore: 9,
    effortScore: 5,
    matrixClassification: 'STRATEGIC',
    startDate: '2026-01-15',
    targetDate: '2026-08-31',
    status: 'ACTIVE',
    priority: 'CRITICAL',
  },
  {
    initiativeId: 'INIT-004',
    objectiveId: 'OBJ-2026-003',
    objectiveName: 'Consolidar Liderazgo y Retención de Cuentas Industriales Tier A',
    krId: 'KR-006',
    name: 'Programa de Auditorías Térmicas en Planta Gratuitas para Clientes Estratégicos',
    description: 'Visitas técnicas con cámara termográfica Fluke para cuantificar ahorro energético en tuberías y ductos de clientes Tier A.',
    ownerId: 'USR-004',
    ownerName: 'Lic. Sofía Morales',
    department: 'Servicio & Calidad',
    budget: 150000,
    spentBudget: 110000,
    expectedFinancialImpact: 1400000,
    actualFinancialImpact: 980000,
    expectedImpactSummary: 'Generación de $1.4M MXN en pipeline de renovación de aislamiento térmico.',
    impactScore: 10,
    effortScore: 6,
    matrixClassification: 'STRATEGIC',
    startDate: '2026-02-15',
    targetDate: '2026-11-30',
    status: 'ACTIVE',
    priority: 'HIGH',
  },
  {
    initiativeId: 'INIT-005',
    objectiveId: 'OBJ-2026-004',
    objectiveName: 'Excelencia Operativa Logística & Cumplimiento OTIF ≥ 98%',
    krId: 'KR-002',
    name: 'Ampliación de Almacén Secundario en Zona Bajío (Querétaro)',
    description: 'Estudio de factibilidad para hub logístico en Bajío.',
    ownerId: 'USR-003',
    ownerName: 'Ing. Roberto Hernández',
    department: 'Operaciones',
    budget: 450000,
    spentBudget: 40000,
    expectedFinancialImpact: 600000,
    actualFinancialImpact: 0,
    expectedImpactSummary: 'Reducción de tiempos de entrega en Bajío de 48h a 12h.',
    impactScore: 6,
    effortScore: 9,
    matrixClassification: 'LOW_PRIORITY',
    startDate: '2026-06-01',
    targetDate: '2026-12-31',
    status: 'PLANNED',
    priority: 'LOW',
  },
];

export const INITIAL_STRATEGIC_VARIANCES: StrategicVarianceItem[] = [
  {
    varianceId: 'VAR-001',
    metricCode: 'VENTAS_YTD',
    metricName: 'Ventas Totales Netas YTD',
    category: 'VENTAS',
    unit: 'MXN',
    targetValue: 18500000,
    realValue: 19845200,
    forecastValue: 20100000,
    varianceVsTarget: +1345200,
    varianceVsTargetPct: +7.27,
    varianceVsForecast: -254800,
    isNegativeDeviation: false,
    financialImpactMXN: +1345200,
    severity: 'INFORMATIVA',
    responsibleOwner: 'Ing. Carlos Mendoza (Gerente Comercial)',
    suggestedCorrectionAction: 'Mantener ritmo de colocación de tubos preformados y colchonetas.',
    detectedAt: '2026-08-27T08:00:00Z',
  },
  {
    varianceId: 'VAR-002',
    metricCode: 'DSO_DIAS',
    metricName: 'Días de Cartera (DSO)',
    category: 'LIQUIDEZ',
    unit: 'Días',
    targetValue: 38.0,
    realValue: 42.5,
    forecastValue: 40.0,
    varianceVsTarget: +4.5,
    varianceVsTargetPct: +11.84,
    varianceVsForecast: +2.5,
    isNegativeDeviation: true,
    financialImpactMXN: -380000,
    severity: 'ALTA',
    responsibleOwner: 'C.P. Mariana Rivas (Gerente de Finanzas)',
    suggestedCorrectionAction: 'Activar llamadas de seguimiento con CFE y Ternium para conciliar facturas pendientes.',
    detectedAt: '2026-08-27T08:00:00Z',
  },
  {
    varianceId: 'VAR-003',
    metricCode: 'OTIF_LOGISTICA',
    metricName: 'Nivel de Servicio OTIF',
    category: 'OPERACION',
    unit: '%',
    targetValue: 98.0,
    realValue: 95.8,
    forecastValue: 96.5,
    varianceVsTarget: -2.2,
    varianceVsTargetPct: -2.24,
    varianceVsForecast: -0.7,
    isNegativeDeviation: true,
    financialImpactMXN: -85000,
    severity: 'MEDIA',
    responsibleOwner: 'Ing. Roberto Hernández (Operaciones)',
    suggestedCorrectionAction: 'Reasignar 2 unidades dedicadas para pedidos urgentes en turno vespertino.',
    detectedAt: '2026-08-27T08:00:00Z',
  },
  {
    varianceId: 'VAR-004',
    metricCode: 'CAC_MARKETING',
    metricName: 'Costo de Adquisición de Clientes (CAC)',
    category: 'MARKETING',
    unit: 'MXN/Cliente',
    targetValue: 4500,
    realValue: 5150,
    forecastValue: 4800,
    varianceVsTarget: +650,
    varianceVsTargetPct: +14.44,
    varianceVsForecast: +350,
    isNegativeDeviation: true,
    financialImpactMXN: -52000,
    severity: 'MEDIA',
    responsibleOwner: 'Lic. Laura Treviño (Marketing)',
    suggestedCorrectionAction: 'Depurar palabras clave genéricas en Google Ads y enfocar pauta en términos B2B exactos.',
    detectedAt: '2026-08-27T08:00:00Z',
  },
];

export const INITIAL_STRATEGIC_ALERTS: StrategicAlert[] = [
  {
    alertId: 'ALT-EST-001',
    type: 'DSO_RISK',
    severity: 'ALTA',
    metric: 'DSO Cartera Corporativa',
    threshold: '≤ 38.0 Días',
    actual: '42.5 Días (+4.5 días de desviación)',
    variation: '+11.8%',
    financialImpactMXN: 380000,
    owner: 'C.P. Mariana Rivas',
    department: 'Finanzas & Cobranza',
    recommendedAction: 'Aplicar política de bloqueo de nuevos pedidos a cuentas con facturas >60 días.',
    createdAt: '2026-08-27T07:15:00Z',
    status: 'ACTIVA',
  },
  {
    alertId: 'ALT-EST-002',
    type: 'CUSTOMER_CHURN',
    severity: 'CRITICA',
    metric: 'Riesgo de Churn en Cuenta Tier A (Braskem Idesa)',
    threshold: 'Health Score ≥ 75 pts',
    actual: '48 pts (35 días sin orden de compra)',
    variation: '-36.0%',
    financialImpactMXN: 850000,
    owner: 'Ing. Carlos Mendoza',
    department: 'Ventas Corporativas',
    recommendedAction: 'Agendar reunión presencial de Dirección Comercial y ofrecer auditoría técnica termográfica.',
    createdAt: '2026-08-27T08:00:00Z',
    status: 'ACTIVA',
  },
  {
    alertId: 'ALT-EST-003',
    type: 'INVENTORY_OVERSTOCK',
    severity: 'MEDIA',
    metric: 'Sobreinventario en Línea Lana Mineral',
    threshold: '≤ 45 días de inventario',
    actual: '68 días de inventario ($420,000 MXN inmovilizados)',
    variation: '+51.1%',
    financialImpactMXN: 420000,
    owner: 'Ing. Roberto Hernández',
    department: 'Almacenes & Compras',
    recommendedAction: 'Lanzar paquete promocional con 5% de descuento en volumen para proyectos petroquímicos.',
    createdAt: '2026-08-26T14:30:00Z',
    status: 'ACTIVA',
  },
];

export const INITIAL_EXECUTIVE_ACTIONS: ExecutiveActionItem[] = [
  {
    actionId: 'ACT-HOY-001',
    horizon: 'HOY',
    source: 'ALERTA_ESTRATEGICA',
    title: 'Autorizar plan de recuperación inmediata para cuenta Braskem Idesa',
    description: 'Validar propuesta de descuento especial por volumen y visita técnica con equipo termográfico.',
    ownerId: 'USR-001',
    ownerName: 'Lic. Fernando Garza',
    department: 'Dirección General',
    priority: 'CRITICAL',
    expectedImpact: 'Proteger contrato anual de $850,000 MXN y elevar Health Score a 80+.',
    expectedFinancialImpactMXN: 850000,
    deadline: '2026-08-27',
    status: 'PENDING',
    requiresHumanApproval: true,
    isHumanApproved: false,
  },
  {
    actionId: 'ACT-HOY-002',
    horizon: 'HOY',
    source: 'DESVIACION_BSC',
    title: 'Revisión y liberación de 4 órdenes de compra con retención por límite de crédito',
    description: 'Evaluar historial de pago y autorizar dispensa temporal para Ternium y CFE.',
    ownerId: 'USR-005',
    ownerName: 'C.P. Mariana Rivas',
    department: 'Finanzas',
    priority: 'HIGH',
    expectedImpact: 'Liberar facturación inmediata de $340,000 MXN sin comprometer riesgo crediticio.',
    expectedFinancialImpactMXN: 340000,
    deadline: '2026-08-27',
    status: 'IN_PROGRESS',
    requiresHumanApproval: true,
    isHumanApproved: false,
  },
  {
    actionId: 'ACT-SEM-001',
    horizon: 'ESTA_SEMANA',
    source: 'RECOMENDACION_IA',
    title: 'Ajuste de precio en lista +3.5% para materiales PRE-1080',
    description: 'Implementar nueva tarifa de lista validada en simulación What-If que aporta +$380k de EBITDA.',
    ownerId: 'USR-002',
    ownerName: 'Ing. Carlos Mendoza',
    department: 'Comercial',
    priority: 'HIGH',
    expectedImpact: '+ $380,000 MXN en EBITDA del trimestre.',
    expectedFinancialImpactMXN: 380000,
    deadline: '2026-08-31',
    status: 'PENDING',
    requiresHumanApproval: true,
    isHumanApproved: false,
  },
  {
    actionId: 'ACT-MES-001',
    horizon: 'ESTE_MES',
    source: 'DECISION_DIRECTOR',
    title: 'Cierre de licitación de transporte consolidado Norte-Noreste',
    description: 'Contratar línea de transporte dedicada para ahorrar 8% en costo por tonelada transportada.',
    ownerId: 'USR-003',
    ownerName: 'Ing. Roberto Hernández',
    department: 'Logística',
    priority: 'MEDIUM',
    expectedImpact: 'Ahorro anualizado de $290,000 MXN.',
    expectedFinancialImpactMXN: 290000,
    deadline: '2026-09-15',
    status: 'PENDING',
    requiresHumanApproval: true,
    isHumanApproved: false,
  },
];

export const INITIAL_STRATEGIC_FORECASTS: MultiMetricStrategicForecast[] = [
  {
    metricName: 'Ventas Mensuales Netas',
    metricCode: 'SALES_REVENUE',
    unit: 'MXN',
    points: [
      { periodLabel: 'Ene 2026', actualValue: 2150000, targetValue: 2100000, forecastConservative: 2100000, forecastExpected: 2150000, forecastOptimistic: 2200000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Feb 2026', actualValue: 2280000, targetValue: 2200000, forecastConservative: 2180000, forecastExpected: 2250000, forecastOptimistic: 2320000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Mar 2026', actualValue: 2450000, targetValue: 2350000, forecastConservative: 2300000, forecastExpected: 2400000, forecastOptimistic: 2500000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Abr 2026', actualValue: 2520000, targetValue: 2400000, forecastConservative: 2380000, forecastExpected: 2480000, forecastOptimistic: 2600000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'May 2026', actualValue: 2610000, targetValue: 2500000, forecastConservative: 2450000, forecastExpected: 2580000, forecastOptimistic: 2700000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Jun 2026', actualValue: 2685000, targetValue: 2550000, forecastConservative: 2500000, forecastExpected: 2650000, forecastOptimistic: 2800000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Jul 2026', actualValue: 2550200, targetValue: 2600000, forecastConservative: 2480000, forecastExpected: 2590000, forecastOptimistic: 2750000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Ago 2026', actualValue: 2600000, targetValue: 2650000, forecastConservative: 2520000, forecastExpected: 2620000, forecastOptimistic: 2800000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Sep 2026', targetValue: 2700000, forecastConservative: 2580000, forecastExpected: 2720000, forecastOptimistic: 2900000, unit: 'MXN', dataHonesty: 'PROJECTED' },
      { periodLabel: 'Oct 2026', targetValue: 2800000, forecastConservative: 2650000, forecastExpected: 2840000, forecastOptimistic: 3050000, unit: 'MXN', dataHonesty: 'PROJECTED' },
      { periodLabel: 'Nov 2026', targetValue: 2900000, forecastConservative: 2750000, forecastExpected: 2950000, forecastOptimistic: 3200000, unit: 'MXN', dataHonesty: 'PROJECTED' },
      { periodLabel: 'Dic 2026', targetValue: 3100000, forecastConservative: 2900000, forecastExpected: 3150000, forecastOptimistic: 3450000, unit: 'MXN', dataHonesty: 'PROJECTED' },
    ],
  },
  {
    metricName: 'EBITDA Mensual',
    metricCode: 'EBITDA_REVENUE',
    unit: 'MXN',
    points: [
      { periodLabel: 'Ene 2026', actualValue: 480000, targetValue: 470000, forecastConservative: 450000, forecastExpected: 480000, forecastOptimistic: 510000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Feb 2026', actualValue: 515000, targetValue: 495000, forecastConservative: 480000, forecastExpected: 510000, forecastOptimistic: 540000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Mar 2026', actualValue: 560000, targetValue: 530000, forecastConservative: 510000, forecastExpected: 550000, forecastOptimistic: 590000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Abr 2026', actualValue: 585000, targetValue: 550000, forecastConservative: 530000, forecastExpected: 580000, forecastOptimistic: 620000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'May 2026', actualValue: 605000, targetValue: 575000, forecastConservative: 550000, forecastExpected: 600000, forecastOptimistic: 650000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Jun 2026', actualValue: 630000, targetValue: 590000, forecastConservative: 570000, forecastExpected: 625000, forecastOptimistic: 680000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Jul 2026', actualValue: 580000, targetValue: 610000, forecastConservative: 560000, forecastExpected: 605000, forecastOptimistic: 660000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Ago 2026', actualValue: 595000, targetValue: 625000, forecastConservative: 580000, forecastExpected: 620000, forecastOptimistic: 680000, unit: 'MXN', dataHonesty: 'REAL' },
      { periodLabel: 'Sep 2026', targetValue: 650000, forecastConservative: 600000, forecastExpected: 660000, forecastOptimistic: 720000, unit: 'MXN', dataHonesty: 'PROJECTED' },
      { periodLabel: 'Oct 2026', targetValue: 680000, forecastConservative: 630000, forecastExpected: 695000, forecastOptimistic: 760000, unit: 'MXN', dataHonesty: 'PROJECTED' },
      { periodLabel: 'Nov 2026', targetValue: 710000, forecastConservative: 660000, forecastExpected: 725000, forecastOptimistic: 800000, unit: 'MXN', dataHonesty: 'PROJECTED' },
      { periodLabel: 'Dic 2026', targetValue: 760000, forecastConservative: 700000, forecastExpected: 780000, forecastOptimistic: 860000, unit: 'MXN', dataHonesty: 'PROJECTED' },
    ],
  },
];

export const INITIAL_SENSITIVITY_EFFECTS: SensitivityVariableEffect[] = [
  {
    variableName: 'Precio de Venta (+1%)',
    testShift: '+1.0% en Lista General',
    ebitdaImpactMXN: +198450,
    cashFlowImpactMXN: +198450,
    grossMarginImpactPct: +0.65,
    workingCapitalImpactMXN: +15000,
    impactLevel: 'HIGH_IMPACT',
    leverageRank: 1,
    commentary: 'El precio es la palanca financiera de mayor rendimiento (100% cae directo a utilidad bruta).',
  },
  {
    variableName: 'Costo de Ventas / COGS (+3%)',
    testShift: '+3.0% en Materia Prima',
    ebitdaImpactMXN: -365000,
    cashFlowImpactMXN: -365000,
    grossMarginImpactPct: -1.85,
    workingCapitalImpactMXN: +95000,
    impactLevel: 'HIGH_IMPACT',
    leverageRank: 2,
    commentary: 'Impacto severo. Requiere contratos cerrados a 6 meses con proveedores de fibra de vidrio y silicato.',
  },
  {
    variableName: 'Volumen de Ventas (+10%)',
    testShift: '+10.0% en Toneladas Colocadas',
    ebitdaImpactMXN: +760000,
    cashFlowImpactMXN: +620000,
    grossMarginImpactPct: +0.20,
    workingCapitalImpactMXN: +210000,
    impactLevel: 'HIGH_IMPACT',
    leverageRank: 3,
    commentary: 'Expansión de volumen diluye gastos fijos operativos significativamente.',
  },
  {
    variableName: 'Días de Cartera / DSO (+10 días)',
    testShift: '+10 días en ciclo de cobro',
    ebitdaImpactMXN: 0,
    cashFlowImpactMXN: -661500,
    grossMarginImpactPct: 0.0,
    workingCapitalImpactMXN: +661500,
    impactLevel: 'HIGH_IMPACT',
    leverageRank: 4,
    commentary: 'Deteriora liquidez de caja inmediatamente, aumentando necesidad de financiamiento bancario.',
  },
  {
    variableName: 'Costo Logístico de Reparto (-5%)',
    testShift: '-5.0% en flete y maniobra',
    ebitdaImpactMXN: +48500,
    cashFlowImpactMXN: +48500,
    grossMarginImpactPct: +0.25,
    workingCapitalImpactMXN: 0,
    impactLevel: 'MEDIUM_IMPACT',
    leverageRank: 5,
    commentary: 'Consolidación de rutas en el Noreste aporta ahorro sostenido sin inversión de capital.',
  },
  {
    variableName: 'Presupuesto Marketing (+20%)',
    testShift: '+20% en Pauta Google Ads / LinkedIn',
    ebitdaImpactMXN: -18000,
    cashFlowImpactMXN: -18000,
    grossMarginImpactPct: -0.10,
    workingCapitalImpactMXN: 0,
    impactLevel: 'LOW_IMPACT',
    leverageRank: 6,
    commentary: 'Aporta nuevos SQLs industriales a 60 días de ciclo de cierre.',
  },
];

export const INITIAL_PRIORITY_MATRIX_ITEMS: PriorityMatrixItem[] = [
  {
    id: 'PM-001',
    title: 'Ajuste de Precios en Líneas de Alta Densidad (+3.8%)',
    category: 'Comercial & Pricing',
    impactScore: 9,
    effortScore: 2,
    quadrant: 'QUICK_WINS',
    estimatedReturnMXN: 580000,
    estimatedCostMXN: 45000,
    roiRatio: 12.8,
    recommendedOwner: 'Ing. Carlos Mendoza',
    suggestedTimeframe: 'Inmediato (1-2 semanas)',
  },
  {
    id: 'PM-002',
    title: 'Consolidación de Ruteo Logístico Noreste',
    category: 'Logística & Cadena de Suministro',
    impactScore: 8,
    effortScore: 3,
    quadrant: 'QUICK_WINS',
    estimatedReturnMXN: 340000,
    estimatedCostMXN: 65000,
    roiRatio: 5.2,
    recommendedOwner: 'Ing. Roberto Hernández',
    suggestedTimeframe: 'Corto Plazo (30 días)',
  },
  {
    id: 'PM-003',
    title: 'Portal de Cobranza B2B y Conciliación Inmediata',
    category: 'Finanzas & Tesorería',
    impactScore: 9,
    effortScore: 5,
    quadrant: 'STRATEGIC',
    estimatedReturnMXN: 850000,
    estimatedCostMXN: 120000,
    roiRatio: 7.0,
    recommendedOwner: 'C.P. Mariana Rivas',
    suggestedTimeframe: 'Mediano Plazo (60-90 días)',
  },
  {
    id: 'PM-004',
    title: 'Auditorías Termográficas Gratuitas en Planta Tier A',
    category: 'Servicio & Postventa',
    impactScore: 10,
    effortScore: 6,
    quadrant: 'STRATEGIC',
    estimatedReturnMXN: 1400000,
    estimatedCostMXN: 150000,
    roiRatio: 9.3,
    recommendedOwner: 'Lic. Sofía Morales',
    suggestedTimeframe: 'Trimestral continuo',
  },
  {
    id: 'PM-005',
    title: 'Ampliación de Hub Logístico en Bajío (Querétaro)',
    category: 'Infraestructura',
    impactScore: 5,
    effortScore: 9,
    quadrant: 'LOW_PRIORITY',
    estimatedReturnMXN: 420000,
    estimatedCostMXN: 450000,
    roiRatio: 0.93,
    recommendedOwner: 'Ing. Roberto Hernández',
    suggestedTimeframe: 'Evaluar en 2027',
  },
  {
    id: 'PM-006',
    title: 'Campaña Masiva en Redes Sociales B2C (No Especializada)',
    category: 'Marketing',
    impactScore: 2,
    effortScore: 8,
    quadrant: 'AVOID',
    estimatedReturnMXN: 35000,
    estimatedCostMXN: 180000,
    roiRatio: 0.19,
    recommendedOwner: 'Lic. Laura Treviño',
    suggestedTimeframe: 'Descartar / Cancelar',
  },
];
